### PR TITLE
Fix JS race condition in tests

### LINKED ISSUE #3399: Fix intermittent Unmatched GET to /api/v0/dashboard/jane/ warning

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #3399

#### What's this PR do?
This is caused by a test in `DashboardPage_test.js` which didn't wait for all actions which were dispatched. This caused a fetch to happen after the sandbox was cleared, which meant that `fetchMock` handled it instead without any mock for that endpoint. This:
 - fixes the test to listen for the additional actions
 - Moves `fetchMock.restore()` into `global_init` `afterEach` so we aren't listening for actions in between tests anymore
 - adds commented out code to aid in debugging this issue in the future

#### How should this be manually tested?
N/A

### CODE REVIEW

**Comment by aliceriot** [comment]
do you happen to know which test in `DashboardPage_test.js` was causing the issue? Just want to confirm the fix

**Comment by noisecapella** [comment]
It's the `only if status is ${status}` one

**Comment by aliceriot** [comment]
cool, thx

**Comment by aliceriot** [comment]
confirmed fix works!

**Pull request merged**
