### PR TITLE
Release 0.3.0

### PR DESCRIPTION
**Pull request by annagav**
## Alice Pote
  - [x] Moved JS tests to npm scripts ([ba8f365a](../commit/ba8f365a869222695f5567a09b184006171f65aa))
  - [x] Added google analytics to base ui template ([85ce3a59](../commit/85ce3a590c45ae4d118b2624d17ca9586d2c52d8))
  - [x] Added redirect, &quot;/dashboard&quot; -&gt; &quot;/&quot; if user not logged in ([cc3e6f45](../commit/cc3e6f45e6629f2dbff51fd7b78100b4a4e37de4))
  - [x] Made log out button on dashboard log user out ([bed611ea](../commit/bed611ea8e119fbae59a09c47afb0af035ce24a7))

## George Schneeloch
  - [x] Implemented React component for dashboard API ([4e33953e](../commit/4e33953e9a42fb1de03880f7586f9f2adcb3bdc1))
  - [x] Added MIT Micromasters graphic and updated title ([2ef54b94](../commit/2ef54b9415ba6c73316960fef067b9dcb4a2b6d4))
  - [x] Added CourseRun to gen_fake_data ([6e765893](../commit/6e765893c767cd3f573934ee70a2a0c68e4974b7))
  - [x] Updated tox version ([b84645fd](../commit/b84645fdbda06ac11bf49f71658f6444cb556afa))
  - [x] Removed redux-actions ([e2078321](../commit/e207832154011617861056dd3099c2058bc69206))
  - [x] Added code coverage for javascript ([796f9924](../commit/796f9924636dadb4b1f994e79a2273e175681b08))
  - [x] Removed configureStore_test.js, use redux-asserts instead ([096766d4](../commit/096766d458ec22f09b7510a4bde57629fd6dd064))
  - [x] Updated django-server-status ([c8047a1b](../commit/c8047a1b5509a24ebde3e90f6c55ed14855e337c))
  - [x] Fixed LICENSE organization ([ef5b9383](../commit/ef5b9383c1f1c753e42384816264e35ced76191a))

## annagav
  - [x] Display student avatar and name ([d22fafaa](../commit/d22fafaaf6e427689ecb4ad6aa2fe9ab9f252959))

## Justin Abrahms
  - [x] Introduced new Course model to support CourseRuns ([a378cf80](../commit/a378cf802d4a3fb80d2d7e581e70f08c78cfea26))
  - [x] Added sign-in-with LinkedIn backend support. ([146194a0](../commit/146194a0be3257bc0f4b637df2502f85a29566d3))

### CODE REVIEW

**Comment by noisecapella** [comment]
@aliceriot for items regarding testing or dev-specific things feel free to just check off the item. This is just making sure the work we did exists in the release candidate

**Comment by aliceriot** [comment]
@noisecapella cool, I checked off the `npm` scripts change, should I test the other changes as well?

**Comment by noisecapella** [comment]
Yes, but we're not doing thorough testing here, just making sure the feature exists and that it doesn't conflict with another feature

**Comment by noisecapella** [comment]
@annagav Can you file an issue to handle the case where we show the default image if we can't get the profile image from edX? I think it's an edge case that slipped through the cracks

**Comment by annagav** [comment]
Sure

**Pull request merged**
