### PR TITLE
Added merchant_defined_data fields

### LINKED ISSUE #1726: Add merchant_defined_data fields
This might enable us to use the data in reporting, not sure yet. It won't hurt anything to add the fields though

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1726 

#### What's this PR do?
Adds Cybersource fields which may be useful in reporting

#### How should this be manually tested?
Nothing should break. You can test this by clicking the pay button for a course and verifying that you are redirected to Cybersource

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@noisecapella it is taking me to local edx instance instead of Cybersource

**Comment by noisecapella** [comment]
Ecommerce is only available for financial aid programs.

I've set up the database so you can test this on the PR build, you will need to use Digital Learning to test this

**Comment by amir-qayyum-khan** [comment]
can I get dump?

**Comment by amir-qayyum-khan** [comment]
code looks 👍 
only need to test actual functionality

**Comment by noisecapella** [comment]
It's fine, I'll ask @pdpinch to do the manual test since he's done that before regarding Cybersource

**Comment by amir-qayyum-khan** [comment]
sure

**Comment by noisecapella** [comment]
@pdpinch Can you go to the PR build and do a purchase? I'll get the email and verify that the new fields are there

**Comment by pdpinch** [comment]
Sorry I've been letting this linger so long. I'm redeploying the review app.

**Comment by pdpinch** [comment]
I'm still struggling with seeding the database in the review app. 

I install factory_boy: 

```
pdpinch$ heroku run --app micromasters-ci-pr-1727 pip install --user factory_boy
Running pip install --user factory_boy on ⬢ micromasters-ci-pr-1727... up, run.1451 (Hobby)
Collecting factory_boy
  Downloading factory_boy-2.7.0-py2.py3-none-any.whl
Collecting fake-factory>=0.5.0 (from factory_boy)
  Downloading fake_factory-0.7.2-py2.py3-none-any.whl (530kB)
    100% |████████████████████████████████| 532kB 1.3MB/s 
Requirement already satisfied: python-dateutil>=2.4 in ./.heroku/python/lib/python3.5/site-packages (from fake-factory>=0.5.0->factory_boy)
Requirement already satisfied: six in ./.heroku/python/lib/python3.5/site-packages (from fake-factory>=0.5.0->factory_boy)
Installing collected packages: fake-factory, factory-boy
Successfully installed factory-boy-2.7.0 fake-factory-0.7.2
```

but seed_db still won't run:

```
pdpinch$ heroku run --app micromasters-ci-pr-1727 ./manage.py seed_db
Running ./manage.py seed_db on ⬢ micromasters-ci-pr-1727... up, run.8193 (Hobby)
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/app/.heroku/python/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/app/seed_data/management/commands/seed_db.py", line 8, in <module>
    from factory.django import mute_signals
ImportError: No module named 'factory'
```

**Comment by noisecapella** [comment]
Blocked by #1745

**Comment by noisecapella** [comment]
@gsidebo Can you make a PR that just covers this issue? This is blocking other issues

**Comment by noisecapella** [comment]
@pdpinch this should be ready to test after the PR deploys. You may need to talk to @blarghmatey to increase the hours allowed

**Comment by pdpinch** [comment]
Ok, I made a purchase and I see the following in the transaction record in Cybersource:

screenshot 2016-11-23 15 06 38

So the data is passing through. Can we change the label for `Merchant-Defined Data 2` and `Merchant-Defined Data 3` (maybe as part of #1807) 

I still want to make sure this data gets into the reports, but it looks like I have to wait until tomorrow morning to see today's report.

**Comment by pdpinch** [comment]
I'm disappointed to find that the merchant-defined data **_does not_** show up in the reports!

https://www.dropbox.com/s/95d1okijz62b4td/TransactionDetailReport-4.csv?dl=0

I think we should merge this, and I'll have to follow up with IS&T and Cybersource support to figure out how to make this work.

**Comment by noisecapella** [comment]
Sounds good

**Pull request merged**
