### PR TITLE
Don't need to make pylint disable missing-docstring for serializer Meta

### PR DESCRIPTION
**Pull request by singingwolfboy**
[pylint-django](https://github.com/landscapeio/pylint-django) takes care of suppressing this

### CODE REVIEW

**Comment by giocalitri** [comment]
if I grep the code in your branch, there are several other places where that pylint disable is still present next to Meta classes

**Comment by singingwolfboy** [comment]
@giocalitri Unfortunately, Pylint is only smart enough to figure this out for Django models and DRF serializers. It doesn't know about Factory Boy factories, which also have a Meta class. [I started building a pylint plugin to teach it about Factory Boy](https://github.com/singingwolfboy/pylint-factory), based on `pylint-django`, but it's not working yet.

**Comment by giocalitri** [comment]
ok... that is fine. 
I did not give my 👍 before you merged though :-)
(no problem for this PR)

**Comment by singingwolfboy** [comment]
Oops! I saw you switched the label to "Waiting on Author", and for some reason my brain parsed that as "Waiting on Author to Merge". 🤦‍♂️

**Pull request merged**
