### PR TITLE
Standardize Log In / Sign Up buttons

### PR DESCRIPTION
**Pull request by asadiqbal08**
#### What are the relevant tickets?
fixes: #4860 

#### What's this PR do?
Standardize Log In / Sign Up buttons

screenshot-localhost_8079-2021 04 13-15_03_33

---------------------- 

screenshot-localhost_8079-2021 04 13-13_39_46

### CODE REVIEW

**Comment by pdpinch** [comment]
Screenshots, please?

Also a question: why are there 3 header templates? I would expect either just 1, or many more -- for example, for the benefits template.

**Comment by asadiqbal08** [comment]
@pdpinch added screenshots. Kindly ignore the second one as I am getting some issues in CMS when uploading backgroud images for a program.

**Review by pdpinch — APPROVED** [review]
Looks good to me!

**Review by annagav — APPROVED** [review]
👍

**Pull request merged**
