### PR TITLE
Fixed image size for faculty carousel

### LINKED ISSUE #1292: Faculty thumbnail images on the program page are cropping to the wrong size.
The faculty images on the program page are supposed to crop to an aspect ration of 500px wide and 385px tall. Currently they seem to be cropping to a square that is 385px by 385px.

Basically what we are shooting for is that a user uploads a hi-res image that is equal to or larger than 500x385 in both directions, and then they are cropped to the correct aspect ratio.

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1292 

#### What's this PR do?
Updates the size to 500x385 to match the help text on the CMS, and also fixes some CSS to allow the user to click the buttons on the left and right sides

#### Screenshots (if appropriate)
screenshot from 2016-10-07 15-56-49

### CODE REVIEW

**Comment by gsidebo** [comment]
just a question: is it wagtail that specifies the Image's title attribute as the default alt text?

**Comment by noisecapella** [comment]
The alt text comes from `default_alt_text` on the wagtail model `Image`, so yes but we can change it if we want in the future. I'll look into the description

**Comment by noisecapella** [comment]
The description tweaking is nontrivial (I'm not sure what the end result should look like) so I'll open another issue for it

**Comment by roberthouse54** [comment]
I have already fixed the text in another PR

**Comment by noisecapella** [comment]
Ok, all comments should be addressed

**Comment by gsidebo** [comment]
👍  ship it!

**Pull request merged**
