### PR TITLE
Release 0.23.0

### PR DESCRIPTION
**Pull request by gsidebo**
## Gavin Sidebottom
  - [x] Fixed dashboard API course status regression ([9d90b516](../commit/9d90b51601825826a8558611af7b958bec6e941d))

## Amir Qayyum Khan
  - [x] [learners profile] Allow period in url param (#1758) ([bbaddd37](../commit/bbaddd376101038592ddc55a3b0ce42810b0d671))
  - [x] Added environment variable to affect Elasticsearch pagination size (#1743) ([e7c3820f](../commit/e7c3820fa5371d833bfa1dea1394ed83f75f77cc))
  - [x] Removed empty education and work history cards on learners page (#1704) ([2d8be166](../commit/2d8be16650fc5ccc2f0cf7806a47ee09712560a0))
  - [x] Allowed annoAnonymous users to see public profiles (#1702) ([958aa4d1](../commit/958aa4d1339345bf6200380901eb58ba904fe2c6))
  - [x] Loaded username param of profile page url from SETTINGS (#1690) ([12183f22](../commit/12183f2226bec4b107f41c11a1709584c0d81a19))
  - [x] Profile: Load existing program enrollments for returning user (#1577) ([4c1f8deb](../commit/4c1f8deb6f76560824d68d640a3d374c041d2e00))

## George Schneeloch
  - [x] Filtered out reset FinancialAid statuses (#1779) ([8ef0a858](../commit/8ef0a8584cf8e78a1c20bb927d977a2551fd1d3c))
  - [x] Moved dashboard API call to DashboardPage (#1750) ([3f6a2b4a](../commit/3f6a2b4a282d74eb76d26e00e99729067bb6631d))
  - [x] Implemented auto approve for TierProgram where discount is $0 (#1723) ([5fe30c7d](../commit/5fe30c7dfb4a1aba853cacecef9e59966bb1d1a3))
  - [x] Fixed race condition bug with FinancialAidCalculator (#1732) ([0c994d32](../commit/0c994d3276b56a397220c17e1cd148d34efdaeb6))
  - [x] Fixed footer display while JS loads (#1720) ([25056a64](../commit/25056a643493c2996e7712f576e599f3014764cf))
  - [x] Implemented sending emails on order errors (#1679) ([27ebd920](../commit/27ebd920dc6aebcd268589ccc218e11517c5f679))
  - [x] Fixed use of /src in docker images (#1699) ([d73feee1](../commit/d73feee11d2ad1d9f1deb301275328bcc73054e4))

## David Baumgold
  - [x] Making profile form more accessible (#1718) ([6cb8a7ff](../commit/6cb8a7fff1322fed9476d5b9d065c46367227aa6))
  - [x] Correct buttons on cost calculator (#1790) ([3b45efc1](../commit/3b45efc14a9ddc66aa8d81b0c47b75252cfd544c))
  - [x] Hide icon text from screenreaders (#1763) ([4d43d807](../commit/4d43d807c28756817ae9809f8941edf5d36fa5e2))
  - [x] MAINTAINER is deprecated in Dockerfiles (#1759) ([27b95dc3](../commit/27b95dc3991b2648f66e0b422bbc86d094ec0b8d))
  - [x] Pass strings to React directly (#1756) ([0193a938](../commit/0193a938c45db40a8d4f2fff1a3beb6127c7e827))
  - [x] Turn profile links into buttons (#1754) ([7d90dd1c](../commit/7d90dd1c0b9ef8502df4327c9d7d4208c651c084))
  - [x] Fix a silly JS error ([96d7d1a3](../commit/96d7d1a39eee9edf39bd493b56e38e3f8ed5f4d6))
  - [x] Clean up unnecessary JS references in program page (#1715) ([773c5732](../commit/773c5732b8115f8b71eb053ccdc5aaca66ad6ca0))
  - [x] Make program list on homepage more accessible ([059774d1](../commit/059774d15cb4dd09f33671d66bc668d4c55febfd))
  - [x] Use &lt;button&gt; for header log in/sign up (#1714) ([82b6d908](../commit/82b6d908c4940549e12b6c173759df454f5894ea))
  - [x] Zendesk prepopulate program on program page (#1628) ([b6b93f33](../commit/b6b93f33fbcf46e8218d75d3b770199b3a7d3058))
  - [x] Make camera icon accessible (#1701) ([9a4f9100](../commit/9a4f9100e260d1422618e4a08b1b2c572f45eeb2))
  - [x] Upgrade pylint to 1.6.4 ([b8822f5c](../commit/b8822f5ce5f056b0d16d9798e22db07a31335ead))
  - [x] Add program name to links on home page (#1700) ([be1a2f4f](../commit/be1a2f4f2b02a7a6585767376525a6c694be7c21))
  - [x] Switch to `manage.py showmigrations` (#1703) ([083bc173](../commit/083bc173aff22e89dff97f3cba0c2be52c7640c1))
  - [x] Add repository and license fields to package.json (#1694) ([c441c626](../commit/c441c626903d7325d0445adaec6a58b0f22a3fe4))
  - [x] Allow all hosts in DEBUG=True mode ([719be465](../commit/719be465ee11d9494ddee32308c66211ce01a3c9))
  - [x] Import views instead of referencing dotted Python path ([8035038e](../commit/8035038ea5aa15aba435c460562428aa3dae171a))
  - [x] Upgrade Django to 1.10.3 ([51dd102d](../commit/51dd102da605c5895f4ffe0511339749e1ba4354))
  - [x] Python-Social-Auth now wants JSON as a dict, not a string (#1693) ([12af7421](../commit/12af7421a230a78b2546369dfab7c1e9135f9710))
  - [x] Course queries should be ordered by default (#1692) ([3f353625](../commit/3f353625c2cf46529f9132d1add2752813373a3a))
  - [x] Docker Compose version 2 (#1641) ([dc63b0df](../commit/dc63b0dfe98818be6f3cd26c1d9c45e9fae19451))

## Robert W House
  - [x] minor linting change ([3004cc6e](../commit/3004cc6eb66a5fdf1a155d1a9b8257e8d7c6e330))
  - [x] fixes minor spacing iussue with program selector in navbar ([dd23f1e4](../commit/dd23f1e49766e365d0c51c5d02606a4ad7868091))
  - [x] styles mm-minor-action button to look like link ([8f4ca645](../commit/8f4ca6458a6b709a43947de794752905f3944240))
  - [x] small style change to the course description popover ([97f6c5db](../commit/97f6c5db159d6e96e1e3a200be900133b15d783b))
  - [x] change link color ([52ce36c7](../commit/52ce36c76cb623e2a1a322b7b7ee610f0b790e1b))
  - [x] style changes to ToS page ([ef7cfe3e](../commit/ef7cfe3e28ae8a3326875fcc2625f98fc955739f))
  - [x] code formatting changes ([55f093f1](../commit/55f093f1400935376a5c9d9969c309df7f05450e))
  - [x] slightly move down dropdown error and fix lint error ([23f5e4a8](../commit/23f5e4a8d53691a6580492e0093cd596c9bebfee))
  - [x] react select styling ([afdc392d](../commit/afdc392dfe6021fa6e572f2e33887054af2ca4b1))
  - [x] moved a style declaration into a different scss file ([3ae9b836](../commit/3ae9b8364a7dec4085a87b5338d643218be0f291))
  - [x] fixed hits count javascript error ([32565d3f](../commit/32565d3fe0cf0572d8df9ffc5dc5e461c98560b2))
  - [x] style changes ([79cf2507](../commit/79cf250780fe55b509a111a97a925e2914f38907))

## Alice Pote
  - [x] Fixed gradient syntax error warning ([4b531f20](../commit/4b531f207b06827c6c4005c9f4936aea38d3113f))
  - [x] Added some new tests for financial aid frontend code ([a23fc8f5](../commit/a23fc8f5f33f3a85426657004e46b778225a5767))
  - [x] Fixed a regression on the settings page ([2b35831e](../commit/2b35831e19b1401e8959adb0c6adf9aaa740a59f))
  - [x] Updated sass-lint config ([6590f73f](../commit/6590f73f6ad1ccfec0f60bb7ebc1bfedd0ad0bf7))
  - [x] Added error display for financial aid API errors ([b22438c1](../commit/b22438c14ff1a1c2b1eeb7b89b36adf913160af0))
  - [x] Fixed error due to webpack config change ([6591e154](../commit/6591e154fa60cacf02d062d34043ad3f70edbd4e))
  - [x] Replaced Autocomplete with react-select ([72504a58](../commit/72504a58efe6d679e3e3f69f7d76e5a67a83e2f4))
  - [x] Changed webpack config for better splitting and smaller bundles ([718235c8](../commit/718235c8d967dac1316d4012af0a1bb0cdd8ac88))
  - [x] Added a script to update images on Docker Hub for travis ([66ab4af0](../commit/66ab4af0a03cd8f8b673c03d5f6471a205ce691e))

## Giovanni Di Milia
  - [x] Program agnostic final grade indexing ([8dbde3a5](../commit/8dbde3a536b06375c1997b5285c91a18bb7c0681))
  - [x] Added reset status to financial aid ([5853e361](../commit/5853e361ceddc87629f03dec92d4fb4c8831d28a))

## Tobias Macey
  - [x] Added conn max age and ssl settings to app.json (#1728) ([2ab7e657](../commit/2ab7e657fe4c7c07ea6df3cdab26a5ba03184391))
  - [x] Updated requirements to use pip-tool (#1649) ([8099e6de](../commit/8099e6de24d782457a85bce3ada311d0ba5a2e9f))
  - [x] Fixing values for PGBouncer in app.json ([c9b9711f](../commit/c9b9711fee01fe4584d7625ddf5a5e2259ec7301))
  - [x] Addressing pylint failures ([7db3b9cb](../commit/7db3b9cba4a5c70ee7c7d61da6d211adc0010f01))

## Peter Pinch
  - [x] PGBOUNCER_DEFAULT_POOL_SIZE and PGBOUNCER_MIN_POOL_SIZE need to be json strings (#1724) ([9db8c0e8](../commit/9db8c0e8a671eeffc7975fe007a36412b23730b3))

## Nathan Levesque
  - [x] Hide photo upload on public profile (#1603) ([6ad62afe](../commit/6ad62afec6d39b7f0aef6551a4df7a587e26e2d0))

## Anna Gavrilman
  - [x] Change &quot;preferred name&quot; to &quot;Nickname / Preferred Name&quot; (#1696) ([368d0277](../commit/368d0277f95cb7eae0b751182bd821ba69013117))

## annagav
  - [x] Employment Form: make space for date field error ([73aaaf66](../commit/73aaaf660649e606c137d0f13b3b282e59c85d64))

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@gsidebo getting 500 error, email amirq@mit.edu

  "ImproperlyConfigured: The program \"Digital Learning\" needs at least one tier configured"

**Comment by amir-qayyum-khan** [comment]
@gsidebo @pdpinch all commits are working except https://github.com/mitodl/micromasters/commit/958aa4d1339345bf6200380901eb58ba904fe2c6

```error
403 Sorry, we were unable to load the data necessary to process your request. Please reload the page.

Additional info: Invalid username/password.

If the error persists, please contact micromasters-support@mit.edu specifying this entire error message.
```

**Comment by aliceriot** [comment]
Is this going to be updated to include newer commits on master? As-is the fix I merged for the sign-in/up dialog isn't included.

**Comment by pdpinch** [comment]
Yes, but we have a couple of release blockers: #1655 and #1777. (It looks like #1785 isn't a blocker)

**Comment by singingwolfboy** [comment]
I can't validate #1628, because it requires a change on the Zendesk side. In that pull request, we decided to assume that the Zendesk ID for a program was the slugified version of the program title. Right now, Zendesk is still using `scm` as the ID for Supply Chain Management, and `dedp` as the ID for "Data, Economics, and Development Policy". Once the IDs are updated on Zendesk, then I can validate that pull request.

**Comment by amir-qayyum-khan** [comment]
verified my commits 👍

**Comment by singingwolfboy** [comment]
Now that @pdpinch has updated the values in Zendesk, I've verified all my commits. 👍

**Comment by aliceriot** [comment]
done!

**Comment by pdpinch** [comment]
@giocalitri @singingwolfboy you still have one or two boxes to check

**Comment by giocalitri** [comment]
done

screen shot 2016-11-21 at 10 51 51 am

**Comment by pdpinch** [comment]
I checked off @singingwolfboy 's boxes. 

I want to do a few manual tests before we release.

**Comment by pdpinch** [comment]
@gsidebo I'm done with the manual checks. Please finish the release.

**Pull request merged**
