### PR TITLE
Blarghmatey/circleci

### PR DESCRIPTION
**Pull request by blarghmatey**
#### What are the relevant tickets?
mitodl/saltops#246

#### What's this PR do?
Adds configuration for running our tests on CircleCI using their 2.0 beta system.

#### How should this be manually tested?
Review the build log at https://circleci.com/gh/mitodl/micromasters/134

#### Where should the reviewer start?
.circleci/config.yml

#### Any background context you want to provide?
We have been having issues with slow builds on Travis and want to move to a system that allows us to pay for more workers.

Of note in this configuration is that they do have a docker executor, but there are some limitations in terms of how tests get executed vs our current approach to running the tests. It may be worth considering an update to our compiled containers to support running with the docker executor because it can significantly reduce the amount of overhead for test startup. Documentation can be found here: https://circleci.com/docs/2.0/executor-types/ and here: https://circleci.com/docs/2.0/building-docker-images/

#### Screenshots (if appropriate)
(Optional)

### CODE REVIEW

**Comment by aliceriot** [comment]
does circleCI have any support for parallel jobs? running all the tests in order is going to be a pretty lengthy build - currently they run in three separate jobs.

**Comment by aliceriot** [comment]
do you have an idea what kind of changes we would need to make in order to use their built-in docker support? I read through the documentation quickly and I didn't see anything that would prevent our current setup from working, but I did not read it super deeply so I'm not sure if I missed anything.

**Comment by blarghmatey** [comment]
Unfortunately they don't have any means of parallelizing the build steps. In terms of the docker support, the issue is that, while you can specify multiple containers to be run, all of the build steps only happen in the first listed container. CircleCI also doesn't have any support for specifying different build configurations within a single application.

I've started trying again to get CodeShip to work but that is also proving to be quite frustrating.

**Comment by blarghmatey** [comment]
There doesn't seem to be much interest in CircleCI so I am going to close this.

**Pull request closed without merging**
