### PR TITLE
Properly rename migration file based on what it does

### PR DESCRIPTION
**Pull request by singingwolfboy**
Is this a good idea, or do we want to leave the migration files untouched after they merge? @aliceriot @rhysyngsun @blarghmatey

### CODE REVIEW

**Comment by singingwolfboy** [comment]
This was introduced in #2240.

**Comment by rhysyngsun** [comment]
I think this only would've got applied to CI at this point, but we could roll the old one back.

**Comment by aliceriot** [comment]
what's the benefit? just a little clarity?

**Comment by rhysyngsun** [comment]
This SO answer has a method, however since deploys automatically run the migration I don't think it would work for us: http://stackoverflow.com/a/30427833/140999

**Comment by singingwolfboy** [comment]
@aliceriot Yes. Particularly for future migrations that declare a dependency on this one.

**Comment by singingwolfboy** [comment]
Sounds like we don't actually want to do this.

**Pull request closed without merging**
