### PR TITLE
Added FAQs accordion

### LINKED ISSUE #1415: Restore accordions (hide/show) on Program FAQ pages
Not sure how this was lost, but the FAQs used to default to a state where the answers were hidden, making it easier to browse all the questions (like http://scm.mit.edu/micromasters/faqs).

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #1415
#### What's this PR do?
Restore accordions for faqs on the program page.

screen shot 2016-10-17 at 5 01 07 pm

screen shot 2016-10-17 at 5 03 23 pm

### CODE REVIEW

**Comment by noisecapella** [comment]
Can you fix the CSS lint warnings?

**Comment by noisecapella** [comment]
I'm unable to edit the FAQs in the CMS even after recreating my local micromasters instance. I'll try with the heroku PR build

**Comment by noisecapella** [comment]
I'm seeing this problem on the PR build too. Can you investigate? In the CMS I only see the title for the FAQ page

**Comment by noisecapella** [comment]
False alarm :)

**Comment by Ferdi** [comment]
@annagav 

- There is too much space between items 
- I think the answer text should be aligned vertically with the beginning of the Question

**Comment by annagav** [comment]
screen shot 2016-10-18 at 5 31 17 pm

**Comment by annagav** [comment]
I removed some padding between the questions.

**Pull request merged**
