### PR TITLE
Program Page: Move tabs to the top

### LINKED ISSUE #3173: Move tabs to the top of the page on Program pages
The tabs on the MicroMasters program pages are currently located underneath the hero image at the top of the page. This is an awkward place for tabs, and it also means that the hero image has to be on all pages.

The goal of this issue is to move the tabs to the top of the page. This means that the content of the page under the tabs will no longer include the hero image (except on the main tab).

We will also have to add the program name to the navbar title, next to the Micromasters logo, as shown in the mocks below.

tabs

tabs2

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #3173

#### What's this PR do?
Move the tabs on the program page above the hero image. Now the hero image is displayed only in the 'about' tab.

#### How should this be manually tested?
Go to the any program page. Play with the tabs.

screen shot 2017-05-12 at 2 50 59 pm

### CODE REVIEW

**Comment by pdpinch** [comment]
@roberthouse54 looking at this in a page, I can't help but get the feeling that there was a CSS glitch or something. The field of red is just too big. Can we get some kind of differentiation between the upper nav bar and the tabs?

**Comment by roberthouse54** [comment]
This is the style of material design. I realize it may look a bit odd at first, but this is a very common style that users will be familiar with. See: https://www.google.com/search?q=material+design+tabs&num=100&safe=off&rlz=1C5CHFA_enUS698US699&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjs1rjPjvLTAhUBxWMKHWQYBwAQ_AUICigB&biw=1091&bih=780

**Comment by roberthouse54** [comment]
Is this changed from how it was before? I believe the tabs were built as material design scrollable tabs. (see: https://material.io/guidelines/components/tabs.html#tabs-usage)

**Comment by rhysyngsun** [comment]
@roberthouse54 you're right, it just wasn't obvious to me that they scrolled looking at them. Assuming that's fine, :+1:

**Pull request merged**
