### PR TITLE
Respect DNT request header

### PR DESCRIPTION
**Pull request by singingwolfboy**
The "Do Not Track" request header indicates that a user does not wish to be tracked by the website they are visiting. This commit checks the DNT header to respect this wish. See http://donottrack.us for more information.

Note that this pull request may affect our analytics numbers.

### CODE REVIEW

**Comment by pdpinch** [comment]
I'd expect that Google already honors DNT, so what does this PR actually do?

FWIW, we don't/wouldn't use Smartlook in production.

**Comment by singingwolfboy** [comment]
@pdpinch Google does _not_ already honor DNT, unfortunately. There is an [unofficial plugin for Google Analytics that makes it honor DNT](http://www.outfox.com/do-not-track-for-google-analytics/), but since it's unofficial and unsupported by Google, it could stop working at any time.

In addition, we're going to be adding more analytics and tracking over time (see #2263), and scoping all of our analytics to one file (`analytics.html`) makes it easy to be sure that all of our analytics respect DNT. This pull request sets a good precedent for the future.

**Comment by aliceriot** [comment]
There is the [google analytics opt-out](https://tools.google.com/dlpage/gaoptout) which I use, but yeah, as DB said, GA does not respect DNT (which *is* irritating).

**Comment by pdpinch** [comment]
@singingwolfboy can you open an issue to go with this (can be brief)

**Comment by singingwolfboy** [comment]
@pdpinch I've created #2299 for this.

**Comment by amir-qayyum-khan** [comment]
@db https://github.com/mitodl/micromasters/pull/2263 is merged. I think you need to rebase this

**Comment by singingwolfboy** [comment]
@amir-qayyum-khan Thanks for the heads-up! I just rebased and included your change.

**Comment by singingwolfboy** [comment]
Blocked on feedback from @pdpinch and @Ferdi.

**Comment by singingwolfboy** [comment]
We'll come back to this in mid-February.

**Comment by pdpinch** [comment]
This is unblocked now.

**Comment by pdpinch** [comment]
👍 after rebase and tests run successfully.

**Pull request merged**
