### PR TITLE
Use container build in Travis for JS tests

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Part of #3318 

#### What's this PR do?
Runs the javascript tests and linting without docker which allows Travis to use container based builds, which should make them faster to run.

#### How should this be manually tested?
Look at the travis output and confirm that sudo is not used for the Javascript tests

### CODE REVIEW

**Comment by aliceriot** [comment]
I think we should be able to delete the travis-watch dockerfiles as well!

**Comment by aliceriot** [comment]
oh, maybe we'll still need them for the selenium tests actually

**Comment by noisecapella** [comment]
We could move the JS static bundle generation into Travis and then copy it into the docker containers we use for selenium tests

**Comment by noisecapella** [comment]
Closing this, it's much slower than just using docker

**Pull request closed without merging**
