### PR TITLE
Remove SETTINGS.username, update tests

### LINKED ISSUE #1869: Add tests for value of START_PROFILE_EDIT
We should test for this https://github.com/mitodl/micromasters/pull/1858/files#diff-92a6563e47b379f3b8fb212041af925dR111

And also fix a similar bug and add a similar test in `fetchUserProfile` in App.js

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1869 

#### What's this PR do?
Fixes `SETTINGS.username` reference that we forgot to remove earlier, adds tests to cover that case

### CODE REVIEW

**Comment by gsidebo** [comment]
code looks good. do you mind explaining a little more about what this is doing? the linked issue doesn't reveal much

**Comment by noisecapella** [comment]
We removed `SETTINGS.username` a little while back in favor of `SETTINGS.user.username` but we missed updating the reference in `App.js`. This fixes that bug and also updates the tests so that using the incorrect username like `/api/v0/profiles/undefined/` will cause an error in the tests

**Comment by noisecapella** [comment]
To verify that the test changes work, you can revert the change to `App.js` or a similar one mentioned in #1869 and some tests should break.

**Comment by gsidebo** [comment]
got it. looks great! 👍

**Pull request merged**
