### PR TITLE
Add video to home page

### PR DESCRIPTION
**Pull request by roberthouse54**
#### What's this PR do?

This PR adds a youtube embedded video to the Micromasters home page. It should be responsive and work at small device widths.

### CODE REVIEW

**Comment by roberthouse54** [comment]
I am waiting to hear back from MIT Video Productions about changing the default youtube image for the video.

In the page, I have put the video right under the header:

image

**Comment by pdpinch** [comment]
I spoke to Doug and he's going to take care of this. I don't think Joe in MVP has access to the YouTube account.

**Comment by noisecapella** [comment]
The video title is `MIT Micro Masters` but I think it should be `MITx MicroMasters`. Not sure who that should go to

**Comment by noisecapella** [comment]
Some of the left and right edges of the video is getting cut off on my phone: 
screenshot_20161221-111758

Not sure how important that is

**Comment by noisecapella** [comment]
Actually it looks like the video is ok, it's just the picture before the video loads which has its edges cut off

**Pull request merged**
