### PR TITLE
Marked required PR sections

### PR DESCRIPTION
**Pull request by rhysyngsun**
#### What are the relevant tickets?

None, this came out of our retrospective.

#### What's this PR do?

Updates this template to mark required sections

#### Where should the reviewer start?

pull_request_template.md

#### How should this be manually tested?

No way to test ahead of merge.

### CODE REVIEW

**Comment by pdpinch** [comment]
👍

**Comment by aliceriot** [comment]
I had thought we didn't want to make 'Where should the reviewer start?' required?

**Comment by rhysyngsun** [comment]
@aliceriot honestly, I can't remember, but I'm fine with that to keep the overhead down. I'll reorder them so all the required ones are at the top.

**Comment by rhysyngsun** [comment]
Updated to make "where to start" optional

**Pull request merged**
