### PR TITLE
Adding common FAQ section for Zendesk 

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#4887 

#### What's this PR do?
Adds link to Zendesk's HelpCenter(FAQ)
Pages that this PR adds the FAQ section to:
- Benefits Page (Main/HomeScreen). (this is usually accessed at `/benefits`)
- Program Page(s)/Tab(s) (This includes all the tabs that show under a program)
- Dashboard Page (`/dashboard`)
- Order Summary (`/order_summary/?<course_key>`)
- Learners Page (`/learners`)
- Settings Page (`/settings`)
- Profile Page (`/learner/<username>`)
- Financial Aid Admin/submissions Page (`/financial_aid`)

#### How should this be manually tested?
Check that the FAQ show just above footer on all the aforementioned pages just above And the FAQ link is functional.

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)

**Program Page**
mm_program_page

**Program Page without Instructors**
program_page_without_instructors

**Program FAQ's Tab/Page**
program_faq_page

**Benefits Page**
mm_benefits_page

**Dashboard**
mm_dashboard

**Order Summary Page**
mm_order_summary

**Learners Page**
learners_page

**Home Page**
mm_home_page

**Email Campaigns Page**
email_campaigns_page

**Profile Edit Page**
mm_profile_page

**Settings Page**
mm_settings_page

**Personal Price Admin page**
personal_price_admin_page

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@pdpinch Can you please take a look at the screenshots of the pages that would have a Zendesk's FAQ link?

Let me know what you about the screenshots and if there are any pages that I might have missed or maybe those that shouldn't have this FAQ link.

**Review by pdpinch — APPROVED** [review]
Very thorough, thank you!

**Comment by arslanashraf7** [comment]
Thanks for the review @pdpinch. I've just requested a technical review from @annagav.

**Review by annagav — APPROVED** [review]
LGTM 👍

**Pull request merged**
