### PR TITLE
Exam grades readme updates

### LINKED ISSUE #4862: Exams: update grades README
Now that we're done (more or less) with the transition to proctored exams on edx.org, we should update the README to capture the new process.

In particular, we should document:

- [ ] how to estimate the number of coupons needed for an exam run
- [x] how to import the coupons
- [ ] how the exam grades are adjusted
- [x] how the adjusted grades are imported 
- [ ] update the checklist
- [ ] remove anything about Pearson

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #4862

#### What's this PR do?
Updating some instructions for populating exam grades

#### How should this be manually tested?
read README

### CODE REVIEW

**Comment by pdpinch** [comment]
Do we need to do anything special for no-shows?

**Comment by pdpinch** [comment]
I think the checklist needs to be updated? https://github.com/mitodl/micromasters/blob/92f55c25c9b6b294cff64bdae60b7132628acc14/grades/README.md#checklist

**Comment by annagav** [comment]
@pdpinch I addressed your comment.

**Review by pdpinch — APPROVED** [review]
Thanks! Let's merge it.

**Pull request merged**
