### PR TITLE
Fixed errant enrollment delete signal (#3211)

### LINKED ISSUE #3211: Search: Remove learner from index when program enrollment is deleted
The Sentry error below has started cropping up recently. I believe it's related to my recent practice of deleting enrollments for learners who have asked to be "removed" from the site, mailing lists etc.

My presumption was that, without a program enrollment, they wouldn't be indexed. Given this exception, I'm not sure what's happening. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/250668014/

```
ValueError: Empty value passed for a required argument.
(2 additional frame(s) were not displayed)
...
  File "search/tasks.py", line 30, in remove_program_enrolled_user
    _remove_program_enrolled_user(program_enrollment_id)
  File "search/indexing_api.py", line 245, in remove_program_enrolled_user
    _delete_item(program_enrollment_id, USER_DOC_TYPE, index)
  File "search/indexing_api.py", line 126, in _delete_item
    conn.delete(index=index, doc_type=doc_type, id=document_id)

ValueError: Empty value passed for a required argument.
```

### PR DESCRIPTION
**Pull request by rhysyngsun**
Fixes #3211 

#### What's this PR do?
Switches to the pre_delete signal for enrollments so that we have a non-`None` record id.

#### How should this be manually tested?
- Enroll for a course, verify you show up in learner search.
- Delete the enrollment in the django admin, verify you no longer show up in learner search.

### CODE REVIEW

**Comment by noisecapella** [comment]
I guess we didn't catch this in the tests since we can't easily test `on_commit`, right? Can you also make a similar change for each delete signal in `search/signals.py`?

**Comment by rhysyngsun** [comment]
@noisecapella I think we should tackle that as a separate issue, I gave it a try, but unlike the changes on this PR it caused test regressions that I don't know how long it'll take to fix.

**Comment by noisecapella** [comment]
Ok I'll file an issue for that. Testing functionality now...

**Comment by noisecapella** [comment]
Looks good :+1:

**Pull request merged**
