### PR TITLE
add share and print bar for certificates

### LINKED ISSUE #4784: Certificates: share and print bar
As a learner, I'd like to be easily share and print my MicroMasters course and program certificates, the same as I can do with my certificates from edX

edX certificates have share and print buttons described in [this edX help article](https://support.edx.org/hc/en-us/articles/206504068-Can-I-get-a-paper-copy-of-my-certificate-). We'd like the MicroMasters to have similar features. We also have implemented similar functions in xPRO. 

#### Acceptance Criteria:

- [x] Simple buttons for social sharing. No service integration, just a link. 
- [x] Print button should use print stylesheet for creating a downloadable PDF 

#### Related issues

- the print stylesheet has some bugs (#4782)

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #4784 

#### What's this PR do?
add share and print bar for certificates

#### How should this be manually tested?
generate and view certificates

#### Screenshots (if appropriate)
Screenshot 2021-02-24 at 17 54 01
Screenshot 2021-02-24 at 18 04 09
Screenshot 2021-02-24 at 18 04 36
Screenshot 2021-02-24 at 18 04 42
Screenshot 2021-02-24 at 18 09 04
Screenshot 2021-02-24 at 17 54 17
Screenshot 2021-02-24 at 17 54 28
Screenshot 2021-02-24 at 18 33 09
Screenshot 2021-02-24 at 18 33 19
Screenshot 2021-02-24 at 17 54 46
Screenshot 2021-02-24 at 17 55 04
Screenshot 2021-02-24 at 17 55 21

### CODE REVIEW

**Comment by umarmughal824** [comment]
@pdpinch could you please review the attached screenshots?

**Comment by pdpinch** [comment]
Thanks @umarmughal824. The UI on the cert page looks good, but I think we can integrate a little better with the sharing services. I'd like the behavior to be the same as edX's (screenshots below). 

Rather than read up on the various APIs, I think it'd be easiest to look at what edX is doing to get the social posts to look like these:

Screen Shot 2021-02-24 at 8 32 31 AM
Screen Shot 2021-02-24 at 8 30 12 AM
Screen Shot 2021-02-24 at 8 34 44 AM

I think we'll have to replace "edX" with "MITx MicroMasters"

**Comment by umarmughal824** [comment]
@pdpinch yeah that would be good for sharing stuff like edX but can we do it in a separate ticket? I will have to discover the edX part for it then will be able to see anything. What's your opinion on that?

**Comment by umarmughal824** [comment]
@annagav could you please review that PR?

**Comment by umarmughal824** [comment]
@HamzaIbnFarooq can you please review that PR?

**Review by HamzaIbnFarooq — COMMENTED** [review]
@umarmughal824, Isn't the share-bar supposed to be only shown to owner of the certificate?

**Comment by umarmughal824** [comment]
> @umarmughal824, Isn't the share-bar supposed to be only shown to owner of the certificate?

yes, it should be. I guess I had missed that part.

**Comment by umarmughal824** [comment]
@HamzaIbnFarooq 
Screenshot 2021-02-25 at 17 31 42

Screenshot 2021-02-25 at 17 31 28

**Review by HamzaIbnFarooq — APPROVED** [review]
LGTM

**Pull request merged**
