### PR TITLE
Added full name search support

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
- fixes https://github.com/mitodl/micromasters/issues/2742

#### What's this PR do?
- Allows user to search learner on full name, first name, last name, email, username.

#### How should this be manually tested?
- run `docker-compose run web ./manage.py recreate_index`
- Go to `http://192.168.99.100:8079/learners/?q=full name` and search full name etc

@pdpinch 

#### Screenshots (if appropriate)
screen shot 2017-03-24 at 12 37 12 pm

### CODE REVIEW

**Comment by noisecapella** [comment]
In your screenshot there is a second result that doesn't match the full name. I think if a user puts in their full name it should only show cases where that name or a prefix matches. Can you add a separately indexed full_name field and add it to the prefix search?

**Comment by amir-qayyum-khan** [comment]
@pdpinch wants to handle this scenario without reindexing. This this the best solution i found without reindexing, 

if user enters first or last name, username, email it will show exact matches, but if input contain spaces it will go for all records which contain substring of input (splited by space) 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#type-cross-fields

**Comment by pdpinch** [comment]
I'm actually fine with a looser match, since the full name we get via ZenDesk may not be a strict match for any "full name" we construct for the index. 

I also want to avoid the elasticsearch upgrade that DB was suggesting that as necessary.

**Comment by noisecapella** [comment]
With the change in this PR the names only match when the entire first or last name is inserted:

screenshot from 2017-03-23 13-13-41

**Comment by noisecapella** [comment]
@pdpinch @singingwolfboy's suggestion wouldn't be necessary in any case. He was referring to the ability for ES to do data transformations within ES, but we can do the same transformations in Python since we control that code, so we don't need to upgrade ES

**Comment by noisecapella** [comment]
Looks good to me. @pdpinch are you ok with having the reindex?

**Comment by pdpinch** [comment]
Yeah, this is fine. Thanks for checking.

**Pull request merged**
