### PR TITLE
refactor: remove proctored exams card and FEATURE_TURN_PAYMENT_OFF flag

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Testing
  - [ ] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#5282 

#### What's this PR do?
- Refactored the code to remove `FEATURE_TURN_PAYMENT_OFF`
- Removed any conditions and the Proctored exam card from the dashboard

#### How should this be manually tested?
- Setup on this branch
- Load the dashboard and you should not see a `Proctored Exam` card on the dashboard
- Try to set `FEATURE_TURN_PAYMENT_OFF` to False and see that there should still be no proctored exam card
- As a matter of fact, adding `FEATURE_TURN_PAYMENT_OFF` in .env should not affect anything at all now
- Nothing should break

#### Where should the reviewer start?
Might be a good place to start testing by first enabling the `Proctored Exam` card as mentioned in the ticket by enabling `FEATURE_TURN_PAYMENT_OFF` so that it's visible on the dashboard, then shift to this branch

#### Any background context you want to provide?
We introduced this flag recently when we turned off the payments for MM, It was done in https://github.com/mitodl/micromasters/pull/5230/files

#### Screenshots (if appropriate)
**After refactoring and removal of `FEATURE_TURN_PAYMENT_OFF` flag**
image

### CODE REVIEW

**Review by annagav — CHANGES_REQUESTED** [review]
did you also remove "/components/dashboard/FinalExamCard.js"? It is not in this PR.

**Comment by arslanashraf7** [comment]
> did you also remove "/components/dashboard/FinalExamCard.js"? It is not in this PR.

No, I didn't remove it. Thought we'd do it in a cleanup PR. But I'll remove it since it might not need a lot of refactoring.

**Comment by arslanashraf7** [comment]
@annagav I've removed it in https://github.com/mitodl/micromasters/pull/5289/commits/a6f1f58774593d383e8ed361d45ea657fc695eaa.

**Review by annagav — APPROVED** [review]
👍

**Pull request merged**
