### PR TITLE
Fix for 404 page when passed exception kwarg

### PR DESCRIPTION
**Pull request by alvinsiu**
#### What are the relevant tickets?
#1248

### CODE REVIEW

**Comment by noisecapella** [comment]
Can you remove the code changes regarding the Cybersource signature? The `KeyError` you're guarding against shouldn't happen since Cybersource guarantees the field to exist

**Comment by alvinsiu** [comment]
Would it make more sense to leave it in so that it returns `403` instead of `500` if that endpoint is hit from not-Cybersource?

**Comment by alvinsiu** [comment]
I'll remove it for now, let me know if you'd like me to put it back in for the reason above! :]

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
