### PR TITLE
Reindex after deploy

### LINKED ISSUE #2178: Run recreate_index on post_deploy
This will rebuild the index after each release

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #2178 

#### What's this PR do?
Rebuilds the ES index after deployment

#### How should this be manually tested?
Look at the heroku logs for the PR build and verify that `recreate_index` was run successfully

### CODE REVIEW

**Comment by giocalitri** [comment]
I think this demonstrate that it runs 👍 :
```
2016-12-21T19:41:33.867997+00:00 heroku[run.5228]: Awaiting client
2016-12-21T19:41:33.899105+00:00 heroku[run.5228]: Starting process with command `(./manage.py migrate && ./manage.py recreate_index); echo "60dcf26a5d3f38c0320930926ca10b92 $?"`
2016-12-21T19:41:34.144463+00:00 heroku[run.5228]: State changed from starting to up
2016-12-21T19:41:43.521285+00:00 heroku[run.5228]: Process exited with status 0
2016-12-21T19:41:43.531389+00:00 heroku[run.5228]: State changed from up to complete
```

**Comment by noisecapella** [comment]
@blarghmatey Would this run after each deploy on release? I looked at the docs and it said it is only run once after the app is created, not after a deploy. Not sure what the distinction means here

**Comment by blarghmatey** [comment]
@noisecapella no, the postdeploy script will only be executed on a newly created app, such as the PR builds. Subsequent deploys won't execute the postdeploy commands. See https://devcenter.heroku.com/articles/app-json-schema#scripts

**Comment by noisecapella** [comment]
Ah, I guess we'll have to do this manually then

**Pull request closed without merging**
