### PR TITLE
Increase order fulfillment timeout

### LINKED ISSUE #1590: Increase order fulfillment timeout on frontend
I think I saw this take longer than 30 seconds for it to succeed, can't reproduce it unfortunately. I feel like we should set it higher, maybe 2 minutes

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #1590
#### What's this PR do?

Cannot test this until this #1697 is fixed.

### CODE REVIEW

**Comment by aliceriot** [comment]
this seems straightfoward enough that we could merge it before #1697 is fixed - @noisecapella thoughts?

**Comment by noisecapella** [comment]
I feel like we should wait since this isn't a critical PR. There are a lot of moving parts to the order fulfillment process and it would be good to do a run through every so often just in case

**Comment by aliceriot** [comment]
word sounds good to me

**Comment by noisecapella** [comment]
The other PR is merged so this isn't blocked anymore

**Comment by pdpinch** [comment]
@noisecapella Anna isn't back until Monday 11/28. Can this wait until this, or should some rebase it for her?

**Comment by noisecapella** [comment]
@annagav I reran the build, maybe that will fix the build. I'm not sure why it failed

**Comment by annagav** [comment]
@noisecapella does this need more review?

**Comment by noisecapella** [comment]
I'll do a functionality test

**Pull request merged**
