### PR TITLE
adds error handling for syncing exchange rates with API

### LINKED ISSUE #1267: Handle bad API calls for syncing currency rates
Syncing currency exchange rates (via openexchangerates.org) does not account for API failures. See DB's comment here: https://github.com/mitodl/micromasters/pull/1257#discussion_r82225605
Comment on tests: https://github.com/mitodl/micromasters/pull/1257#discussion_r82225774

### PR DESCRIPTION
**Pull request by mirfark**
#### What are the relevant tickets?

Fixes #1267.

#### What's this PR do?

Adds error handling for API calls made to Open Exchange Rates (openexchangerates.org) for currency conversion; includes error handling for maximum monthly API calls exceeded.

### CODE REVIEW

**Comment by mirfark** [comment]
@giocalitri @blarghmatey This is what we've implemented for API call errors received from Open Exchange Rates with regards to currency conversion. Does this work with the error handling you guys have set up for scheduled celery tasks?

**Comment by noisecapella** [comment]
Looks good to me, just waiting to hear from @giocalitri or @blarghmatey regarding @mirfark's question

**Comment by giocalitri** [comment]
this should work fine

**Comment by Ferdi** [comment]
Can we merge this ?

**Pull request merged**
