### PR TITLE
dashboard return promises

### LINKED ISSUE #2570: Dashboard functions should return promises where possible
The dashboard has a lot of functions that call `dispatch`, which returns a Promise. These functions should return these promises, rather than returning `void`, so that callers can chain these promises together. This is especially important for handling API errors effectively.

### PR DESCRIPTION
**Pull request by singingwolfboy**
#### What are the relevant tickets?
Fixes #2570.

#### What's this PR do?
Updates functions in `DashboardPage.js` to return Promise objects where possible. If a function generates multiple promises, a new Promise is returned that waits for all the others to complete (using `Promise.all()`).

#### How should this be manually tested?
No change in functionality -- I'm not sure this needs a manual test at all.

#### Where should the reviewer start?
`static/js/containers/DashboardPage.js`

### CODE REVIEW

**Comment by aliceriot** [comment]
Is this just a general refactor or are you trying to fix a specific error? Generally we return a promise from an API action dispatcher function if we need to chain off of it, and otherwise we haven't worried about it.

**Comment by aliceriot** [comment]
Also not all actions return a promise. We use a middleware with redux (called [redux-thunk](https://github.com/gaearon/redux-thunk)) which lets us use async actions that return a promise. But a normal action (i.e. one we create with `createAction` doesn't do that.

**Comment by aliceriot** [comment]
(some of the actions you're wrapping with `Promise.all` do not return a promise, and are simple synchronous actions)

**Comment by singingwolfboy** [comment]
@aliceriot It's just a general refactor. I'm trying to promote good habits: in this case, returning promises.

For a more specific example of why I want to do this, I was working on #2519, and I wanted to add a specific error handler. If the user clicks on the button to audit a course, and the fetch request gets an error response, the app should notify the user of the failure instead of failing silently. However, my `.catch()` handler wasn't being called, and it took me a decent amount of debugging to figure out that the dashboard function that wraps `dispatch()` wasn't actually _returning_ the Promise from `dispatch()`. As a result, the exception wasn't chaining properly, and the app thought that there was no problem with the fetch.

We should get into better habits, so that it's easier to write correct code and harder to write incorrect code.

**Comment by singingwolfboy** [comment]
@aliceriot if you can point out the synchronous actions, or show me how to determine which are synchronous and which are asynchronous, I'd be happy to clean up this PR to only return promises when there's a real promise to return.

**Comment by aliceriot** [comment]
sure, I'll read through the code, but I'm not convinced we should make this change at all, in cases where we do want to chain off the promise we already return them.

**Comment by singingwolfboy** [comment]
@aliceriot I'm happy to discuss this change, and potentially to be talked out of it. My goal is to avoid confusion, and when I was trying to write that error handler, I was very confused when it wasn't called.

**Comment by aliceriot** [comment]
I think in general the action dispatcher functions we use to wrap the API (like `sendCourseTeamMail` from `actions/email`) are where you would want to do your chaining.

**Comment by aliceriot** [comment]
Sorry, to clarify: I think all of our API-wrapping action dispatcher functions should return `Promise.resolve()` on success and `Promise.reject()` on error, but the same doesn't hold for wrapper functions at the container level.

**Comment by aliceriot** [comment]
Also, as far as telling synchronous action creators from async ones, simple action creators return an object literal, of the form:

```js
const myActionCreator = someValue => ({
  type: SOME_TYPE, payload: someValue
});
```

and async ones return a function, like this:

```js
const myAsyncActionCreator = someValue => {
  return dispatch => {
    dispatch(startAPIThing());
    return api.getTheThing().then(
      () => {
        dispatch(apiSuccessAction());
        return Promise.resolve(); 
      },
      () => {
        dispatch(apiFailAction());
        return Promise.reject();
      }
    );
  }
}
```

**Comment by aliceriot** [comment]
I forgot a thing! In JavaScript if you return a rejected promise from a function (or otherwise have a `Promise.reject()` without a function to call on rejection) it raises an error. So we don't really want to return `Promises` from things all over the place, but only in cases where we have error handling set up.

**Comment by aliceriot** [comment]
^^ the above comment makes me think we don't want to make these kinds of changes at all. I do think that the difficulty that you (@db) pointed out w/r/t figuring out how to chain some sort of on-error behavior off of an API action indicates we may have a need to write some documentation around the patterns we use with `fetch` and `redux`.

@noisecapella do you have any thoughts on this?

**Comment by noisecapella** [comment]
I agree with @aliceriot here about the rejected promises. I think we should update the functions individually at the point where there's a need for the promise

**Comment by singingwolfboy** [comment]
Fair enough. Closing this pull request.

**Pull request closed without merging**
