### PR TITLE
Upgraded yarn and Node to the latest version

### PR DESCRIPTION
**Pull request by giocalitri**
#### What are the relevant tickets?
N/A

#### What's this PR do?
Upgrades yarn and node to the latest version

#### How should this be manually tested?
Everything should keep working as usual

NOTE: I already updated the image on docker hub

### CODE REVIEW

**Comment by aliceriot** [comment]
you said in Slack that a few tests aren't passing after the upgrade - in that case, what we should do is change the name of the container that we push to docker hub (with `Dockerfile-travis-watch-build`) to be something like `mitodl/mm_watch_travis_next`, so that we can build a new image using the newer version, and get tests passing on that. then, after it merges, in like a week or two when all existing PRs have been either merged or rebased over the changes, we can rename the image back to `mitodl/mm_watch_travis`.

**Comment by giocalitri** [comment]
I pushed a old version of the container and in the meantime George is taking a look at the tests

**Comment by aliceriot** [comment]
cool

**Comment by noisecapella** [comment]
I pushed a commit to fix a couple race conditions affecting the tests

**Pull request merged**
