### PR TITLE
Added ZenDesk help button on MM

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
- Fixes https://github.com/mitodl/micromasters/issues/1106

#### What's this PR do?
- Adds ZenDesk help button

#### Where should the reviewer start?
- see home_page,

#### How should this be manually tested?
See 
- [x] Homepage
- [x] Program Page
- [x] TOS
- [x] Dashboard and search

@pdpinch @noisecapella @roberthouse54 
#### Screenshots (if appropriate)
screen shot 2016-10-04 at 5 12 47 pm
screen shot 2016-10-04 at 5 19 05 pm

### CODE REVIEW

**Comment by pdpinch** [comment]
Is there a reason why you didn't put the zendesk code in the header template?

**Comment by amir-qayyum-khan** [comment]
i was just trying different things, the button is by default floating. I think putting in header is good idea

**Comment by pdpinch** [comment]
@aliceriot do you have any comment on where the the widget code is put in the dashboard?

I still need to test functionality and @roberthouse54 needs to look at design.

**Comment by aliceriot** [comment]
do we want to have the zendesk thingy on every page? if so it would make sense to me to put it in the base html template instead of duplicating it on two templates.

**Comment by pdpinch** [comment]
Yes, every page. base.html sounds even better than header.html.

**Comment by aliceriot** [comment]
yea, that's included on the dashboard as well.

**Comment by amir-qayyum-khan** [comment]
Done @aliceriot @pdpinch

**Comment by roberthouse54** [comment]
Is there any way we can customize the color of that button? If so, it would be good to make it $mm-brand-bg

**Comment by aliceriot** [comment]
^^ I agree, the style of the button is pretty different than anything else we have on the site. It looks like the button is in an iframe though, so our ability to style it may be limited. Can we set a stylesheet to be used on Zendesk's website?

**Comment by amir-qayyum-khan** [comment]
@aliceriot @roberthouse54 this widget appears in and iframe. I dont thinks so we can change its color.

screen shot 2016-10-06 at 1 09 56 pm

**Comment by pdpinch** [comment]
Looking at the Zendesk docs (linked off the issue) it looks like I can set the color in Zendesk. I'll try that and give you updated code later this morning.

**Comment by amir-qayyum-khan** [comment]
sure, thanks @pdpinch

**Comment by pdpinch** [comment]
I don't see an easy way to override the stylesheet entirely, without rewriting the widget entirely (which is an option). 

I can change the color, but I have to give it a fixed value. I just changed it to the current value of `$mm-brand-bg` #30bb5c

**Comment by pdpinch** [comment]
I just checked the functionality, and it works as expected. We'll want to do some customizations later (like recognizing logged-in users, and detecting which program the question is about) but that can come later. 

Thumbs up from me if @aliceriot and @roberthouse54 can live with this for now.

**Comment by pdpinch** [comment]
I found this discussion forum about hacking the CSS, but it's not supported:

https://support.zendesk.com/hc/en-us/community/posts/207616307-Customize-the-Web-Widget-with-CSS

I'm pretty surprised, frankly, that they don't have a solution to this.

**Comment by aliceriot** [comment]
yeah it's not optimal but I think it's fine.

**Pull request merged**
