### PR TITLE
print program letter in portrait mode

### LINKED ISSUE #5008: Program letter prints in landscape mode in Chrome on a Mac
### Steps to Reproduce

- View a program letter on Chrome on a Mac. 
   - E.g. https://micromasters-rc.odl.mit.edu/letter/program/64b3a67f-954b-40f4-9592-937d495e5e60
- Select print to open the print dialog. Note that it tries to print in landscape mode.

Here's how it prints on different Mac browsers. (It has not been tested on Windows.)
- Mac Chrome: landscape
- Mac Safari: portrait
- Mac Firefox: portrait

Ideally, we'd be able to figure out why Chrome is trying to print in landscape mode and adjust the page to ensure it defaults to portrait mode. Additionally, we can look into this CSS: 
- [size attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size) - `@media print{@page {size: portrait}}`

### Expected Behavior

This page should print in portrait mode.

### Actual Behavior

It prints in landscape mode on Chrome on a Mac.

### Related Issues

#4988

### Screenshot or Screencast

Print dialog
image

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #5008 

#### What's this PR do?
print program letter in portrait mode

#### How should this be manually tested?
Just create a program letter and view it in Chrome preview

#### Screenshots (if appropriate)

**NOW**

Screenshot 2022-01-27 at 13 37 55

**BEFORE**

Screenshot 2022-01-27 at 13 38 30

### CODE REVIEW

**Review by arslanashraf7 — APPROVED** [review]
👍

**Comment by umarmughal824** [comment]
@briangrossman do you have any concerns?

**Comment by briangrossman** [comment]
@umarmughal824 LGTM 👍 

It would be good for you to check on several browsers if possible.

**Comment by umarmughal824** [comment]
> @umarmughal824 LGTM 👍
> 
> It would be good for you to check on several browsers if possible.

@briangrossman Yeah, I have tested it on several browsers one more time.

**Pull request merged**
