### PR TITLE
Add uWSGI settings

### PR DESCRIPTION
**Pull request by markbreedlove**
Sorry for flagging so many reviewers. I'm not sure exactly who should review this.

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?

https://trello.com/c/upfutK0A/44-update-all-uwsgi-configs-with-recommendations-from-bloomberg-article

#### What's this PR do?

It overrides some uWSGI default settings that are not ideal.

Most of the new settings were recommended by this article:
https://www.techatbloomberg.com/blog/configuring-uwsgi-production-deployment/

They have been added to our Django cookiecutter formula:
https://github.com/mitodl/cookiecutter-djangoapp/pull/163

We've made similar changes in `salt-ops` to configure some of our services that don't run in Heroku:
https://github.com/mitodl/salt-ops/pull/1193

#### How should this be manually tested?

No manual testing. If uWSGI runs in CI or RC, that should indicate success.

### CODE REVIEW

**Comment by umarmughal824** [comment]
@markbreedlove the build did not run fully with any status even after a few days. I guess you should restart the build. Builds seem ran successfully but not reflected here.

**Comment by markbreedlove** [comment]
Thanks, @umarmughal824 . It's odd -- Travis shows the build having succeeded when I click through to the build page, but it's not updating here. I'll re-run it now.

**Comment by markbreedlove** [comment]
Actually, Travis is telling me the build can not be restarted. 🤔

**Comment by markbreedlove** [comment]
I'll submit a commit that just changes some whitespace and another to change it back. That should start a new build.

**Comment by markbreedlove** [comment]
This Javascript test keeps failing with a timeout:
https://github.com/mitodl/micromasters/blob/f1d7b78279de06786bd7b4de418a632ea2565829/static/js/containers/FinancialAidCalculator_test.js#L290

The timeout is 2 seconds.

Note how it's failing on the test for "2Adb", which is the third element in the array -- the third string it tests. In other words, the first two strings succeed.

Do any of the reviewers flagged here know why this would time out?

**Comment by markbreedlove** [comment]
This is currently the test job that is failing with the timeout: https://travis-ci.com/github/mitodl/micromasters/jobs/308675296

**Comment by umarmughal824** [comment]
@noisecapella / @aliceriot could you please help him out here. As per git history says both of you have worked on `FinancialAidCalculator.

**Comment by aliceriot** [comment]
theres no javascript chages in this PR so I wouldnt worry about it here - we should probably just file a flaky test issue

**Comment by pdpinch** [comment]
I think there already is an issue for the flaky test: https://github.com/mitodl/micromasters/issues/4441

**Comment by pdpinch** [comment]
I just clicked on the details link next to the failed build and clicked re-run. We'll see what happens.

**Comment by umarmughal824** [comment]
It failed again.

**Comment by markbreedlove** [comment]
@pdpinch Yes, on the the same `FinancialAidCalculator` Javascript test as last time, at the same spot.

**Comment by umarmughal824** [comment]
@pdpinch @markbreedlove Do we need to wait for it to get the JS test bug fixed first or should we proceed with the review?

**Comment by markbreedlove** [comment]
I think the review should proceed because this is only touching the uWSGI configuration.

**Comment by aliceriot** [comment]
yeah this test failing should not be a blocker for merging this PR. we do need to figure out how to address these kinds of tests going forward but I don't think that has to happen here

**Comment by umarmughal824** [comment]
@markbreedlove this is the logs what I'm getting in
```WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0x55d48567bf50 pid: 1 (default app)
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 18, cores: 100)
spawned 2 offload threads for uWSGI worker 1
spawned uWSGI worker 2 (pid: 21, cores: 100)
spawned 2 offload threads for uWSGI worker 2
Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7f92d063eb90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 258, in _after_at_fork_child_reinit_locks
    _releaseLock()  # Acquired by os.register_at_fork(before=.
  File "/usr/local/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
    _lock.release()
RuntimeError: cannot release un-acquired lock
running "exec:touch /tmp/app-initialized" (accepting1)...
Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7f92d063eb90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 258, in _after_at_fork_child_reinit_locks
    _releaseLock()  # Acquired by os.register_at_fork(before=.
  File "/usr/local/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
    _lock.release()
RuntimeError: cannot release un-acquired lock
Python auto-reloader enabled
[pid: 21|app: 0|req: 1/1] 172.20.0.1 () {44 vars in 829 bytes} [Mon Apr  6 13:40:43 2020] GET / => generated 388236 bytes in 12201 msecs (HTTP/1.1 200) 6 headers in 668 bytes (1 switches on core 1)
[pid: 21|app: 0|req: 2/2] 172.20.0.1 () {42 vars in 729 bytes} [Mon Apr  6 13:40:55 2020] GET /background-images.css => generated 828 bytes in 88 msecs (HTTP/1.1 200) 5 headers in 275 bytes (1 switches on core 2)
[pid: 21|app: 0|req: 3/3] 172.20.0.1 () {46 vars in 822 bytes} [Mon Apr  6 13:40:56 2020] GET /static/images/favicon.ico => generated 14846 bytes in 116 msecs via offload() (HTTP/1.1 200) 3 headers in 128 bytes (0 switches on core 4)```

**Comment by umarmughal824** [comment]
@markbreedlove **FYI**: This comes on starting / restarting the server.

**Comment by umarmughal824** [comment]
These are the logs for `master branch`.
```WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x56064831be50 pid: 1 (default app)
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 18, cores: 100)
spawned 2 offload threads for uWSGI worker 1
spawned uWSGI worker 2 (pid: 21, cores: 100)
spawned 2 offload threads for uWSGI worker 2
running "exec:touch /tmp/app-initialized" (accepting1)...
Python auto-reloader enabled
[pid: 21|app: 0|req: 1/1] 172.20.0.1 () {44 vars in 829 bytes} [Mon Apr  6 13:49:07 2020] GET / => generated 388235 bytes in 10080 msecs (HTTP/1.1 200) 6 headers in 656 bytes (1 switches on core 4)
[pid: 21|app: 0|req: 2/2] 172.20.0.1 () {42 vars in 740 bytes} [Mon Apr  6 13:49:17 2020] GET /background-images.css => generated 828 bytes in 165 msecs (HTTP/1.1 200) 5 headers in 275 bytes (1 switches on core 17)```

**Comment by markbreedlove** [comment]
@umarmughal824 : Do you get a different result if you delete or comment out the line that says `py-call-osafterfork = true` in `uwsgi.ini`?

**Comment by umarmughal824** [comment]
> @umarmughal824 : Do you get a different result if you delete or comment out the line that says `py-call-osafterfork = true` in `uwsgi.ini`?

Let me try it.

**Comment by umarmughal824** [comment]
@markbreedlove that previous error gone but now start to get a new error
```

Request Method: | GET
-- | --
http://mm.odl.local:8079/complete/edxorg/?state=pg7AvJkZzMr1W1vviq7KwvQFmUcHz2gp&code=y2vqKeENHxTMXW1g4f3HsA44VQRpsG
2.2.9
ConnectionError
Error -2 connecting to redis:6379. Name or service not known.
/usr/local/lib/python3.7/site-packages/redis/connection.py in connect, line 515
/usr/local/bin/uwsgi
3.7.6
['/src',  '.',  '',  '/usr/local/lib/python3.7/site-packages/_pdbpp_path_hack',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
Tue, 7 Apr 2020 17:31:56 +0000

```

Will further investigate it tomorrow.

**Comment by markbreedlove** [comment]
Hi, @umarmughal824 : Can you say what version of Python you're using?  There's apparently a bug in Python < 3.7.4 that could result in this behavior. https://bugs.python.org/issue36533

**Comment by umarmughal824** [comment]
@markbreedlove It's using `3.7.2`
Reference
https://github.com/mitodl/micromasters/blob/master/runtime.txt#L1
https://github.com/mitodl/micromasters/blob/master/Dockerfile#L1

**Comment by umarmughal824** [comment]
> @markbreedlove this is the logs what I'm getting in
> 
> ```python
> spawned uWSGI master process (pid: 1)
> spawned uWSGI worker 1 (pid: 18, cores: 100)
> spawned 2 offload threads for uWSGI worker 1
> spawned uWSGI worker 2 (pid: 21, cores: 100)
> spawned 2 offload threads for uWSGI worker 2
> Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7f92d063eb90>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/logging/__init__.py", line 258, in _after_at_fork_child_reinit_locks
>     _releaseLock()  # Acquired by os.register_at_fork(before=.
>   File "/usr/local/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
>     _lock.release()
> RuntimeError: cannot release un-acquired lock
> running "exec:touch /tmp/app-initialized" (accepting1)...
> Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7f92d063eb90>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/logging/__init__.py", line 258, in _after_at_fork_child_reinit_locks
>     _releaseLock()  # Acquired by os.register_at_fork(before=.
>   File "/usr/local/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
>     _lock.release()
> RuntimeError: cannot release un-acquired lock
> Python auto-reloader enabled
> [pid: 21|app: 0|req: 1/1] 172.20.0.1 () {44 vars in 829 bytes} [Mon Apr  6 13:40:43 2020] GET / => generated 388236 bytes in 12201 msecs (HTTP/1.1 200) 6 headers in 668 bytes (1 switches on core 1)
> [pid: 21|app: 0|req: 2/2] 172.20.0.1 () {42 vars in 729 bytes} [Mon Apr  6 13:40:55 2020] GET /background-images.css => generated 828 bytes in 88 msecs (HTTP/1.1 200) 5 headers in 275 bytes (1 switches on core 2)
> [pid: 21|app: 0|req: 3/3] 172.20.0.1 () {46 vars in 822 bytes} [Mon Apr  6 13:40:56 2020] GET /static/images/favicon.ico => generated 14846 bytes in 116 msecs via offload() (HTTP/1.1 200) 3 headers in 128 bytes (0 switches on core 4)```
> ```

@markbreedlove that error exists in `xPRO` as well.
Screenshot 2020-04-08 at 12 44 53

**Comment by blarghmatey** [comment]
@umarmughal824 can you try rebuilding your docker container to get a new point release of 3.7? That bug should be fixed in 3.7.4, so anything newer than that should work. Thanks!

**Comment by umarmughal824** [comment]
@blarghmatey I already tested it rebuilding but I might have missed something but now sure. Now retrying it once again.

**Comment by umarmughal824** [comment]
@blarghmatey I got. that same error even after rebuiilding with
`docker-compose build --no-cache`.

**Comment by blarghmatey** [comment]
@umarmughal824 can you confirm the specific version of Python that is running in the rebuilt container?

**Comment by umarmughal824** [comment]
@blarghmatey here what can I see.
``` ✘ ⚙ umerasghar@A006-00274  ~/arbisoft/MIT/micromasters   mbreedlove/add-uwsgi-settings ●  docker-compose run web bash
Starting micromasters_db_1 ...
Starting micromasters_sftp_1    ... done
Starting micromasters_elastic_1 ... done
Starting micromasters_redis_1   ... done
mitodl@31730f18fc6e:/src$ python
Python 3.7.6 (default, Feb  2 2020, 09:00:14)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>```

**Comment by umarmughal824** [comment]
@blarghmatey **FYI:** When I remove py-call-osafterfork = true I get rid off from worker error, but start to get redis one.

**Comment by umarmughal824** [comment]
@noisecapella I am having faced some issues with it but I started to get `redis` error which does not seems related to that change, Could you please give it a try if you have the capacity for it.

**Comment by markbreedlove** [comment]
@blarghmatey  I've just built and run the containers myself, modifying `Dockerfile` to explicitly use `python:3.7.7-buster`, and I get the same error that Umar's been getting, `cannot release un-acquired lock`.

**Comment by markbreedlove** [comment]
This appears to be relevant: https://github.com/unbit/uwsgi/issues/1978

I am still analyzing that issue...

**Comment by markbreedlove** [comment]
They created this PR to try to fix the issue, but it's been open for months: https://github.com/unbit/uwsgi/pull/1995

It's going to have uWSGI _ignore_ the `py-call-osafterfork` setting on Python 3.7, because it's going to implement the behavior that that parameter would have turned on automatically. Until that PR is merged and there's a release of uWSGI that fixes this problem, we should remove the `py-call-osafterfork` setting from the config file.

**Comment by umarmughal824** [comment]
@markbreedlove After making that change did you get any `redis` error? You should just try to login.

**Comment by umarmughal824** [comment]
@markbreedlove I have rebuilded and retested it now only `redis` error left.

**As build started to pass but I can see it's not deployed to micromaster-CI-4569**, once we deploy it successfully, it can be tested on `http://micromasters-ci-4569.odl.mit.edu/`.

```
[2020-04-09 08:30:56] ERROR 19 [django.request] log.py:228 - [6ea5dc8d2ed2] - Internal Server Error: /complete/edxorg/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 510, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 537, in _connect
    socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "./backends/views.py", line 37, in complete
    con.hdel(CACHE_KEY_FAILURE_NUMS_BY_USER, user_key)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2705, in hdel
    return self.execute_command('HDEL', name, *keys)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1043, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 515, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
[2020-04-09 08:30:56] ERROR 19 [django.request] log.py:228 - [6ea5dc8d2ed2] - Internal Server Error: /complete/edxorg/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 510, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 537, in _connect
    socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "./backends/views.py", line 37, in complete
    con.hdel(CACHE_KEY_FAILURE_NUMS_BY_USER, user_key)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2705, in hdel
    return self.execute_command('HDEL', name, *keys)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1043, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 515, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.```

**Comment by markbreedlove** [comment]
@umarmughal824 : I'm not seeing that redis error.

I'm running these commands:

```
docker-compose build
docker-compose up -d
docker logs -f micromasters_web_1
```

This is the end of the log output from `docker logs`:

```
*** Operational MODE: preforking+threaded ***
[2020-04-09 15:58:10] DEBUG 1 [raven.contrib.django.client.DjangoClient] base.py:270 - [8325122cb18e] - Configuring Raven for host: None
[2020-04-09 15:58:10] INFO 1 [raven.contrib.django.client.DjangoClient] base.py:218 - [8325122cb18e] - Raven is not configured (logging is disabled). Please see the documentation for more information.
[2020-04-09 15:58:10] DEBUG 1 [raven.base.Client] base.py:270 - [8325122cb18e] - Configuring Raven for host: None
[2020-04-09 15:58:10] INFO 1 [raven.base.Client] base.py:218 - [8325122cb18e] - Raven is not configured (logging is disabled). Please see the documentation for more information.
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x55784c327820 pid: 1 (default app)
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 18, cores: 100)
spawned uWSGI worker 2 (pid: 19, cores: 100)
spawned 2 offload threads for uWSGI worker 2
spawned 2 offload threads for uWSGI worker 1
running "exec:touch /tmp/app-initialized" (accepting1)...
Python auto-reloader enabled
```

**Comment by markbreedlove** [comment]
The deployment to https://micromasters-ci-pr-4569.herokuapp.com/ worked and it looks like it's functioning. I don't have an account so I haven't logged in, but I don't think it could be serving any of the various pages that I'm loading without uWSGI running.

**Comment by umarmughal824** [comment]
@markbreedlove the error comes right after login successful and when it redirects back to `mm.odl` from `edx devstack`.

**Comment by markbreedlove** [comment]
@blarghmatey or @noisecapella : Can you comment on the Redis errors above?

The errors apparently happen only on this branch. Umar helped me out with some dev environment configuration, but I'm having trouble replicating it quickly due to account password reset and signup issues.  My changes are limited to `uwsgi.ini` but the errors above are triggered after you log in at `micromasters.d.mitx.mit.edu` and then get redirected back to the webapp. (The webapp loads and uwsgi runs, but Umar says the error after redirect only happens on this branch.)

**Comment by markbreedlove** [comment]
Alert for all reviewers: I have just rebased and pushed my branch.

There was a commit on `master` for a Redis upgrade and I want to bring that in.

**Comment by markbreedlove** [comment]
For whatever it's worth, all of the Travis tests are successful now after my rebase, where one had been failing before.

**Comment by umarmughal824** [comment]
> For whatever it's worth, all of the Travis tests are successful now after my rebase, where one had been failing before.

yes it always better to rebase if you face any awkward behavior. But the build was failing because of `py-call-osafterfork = true`.

Thanks.

**Pull request merged**
