### PR TITLE
Release 0.14.0

### PR DESCRIPTION
**Pull request by annagav**
## Robert W House
  - [x] Style changes for the home page (#1056) ([8a9a93fa](../commit/8a9a93fad61641dd163fa1d9d55eae4af0b7c06f))
  - [x] Added a style sheet for responsive layout (#1001) ([748acc80](../commit/748acc800b5788368f46353fb57a969c34619907))
  - [x] Various css changes to colors, fonts, margins (#995) ([52a2dcd5](../commit/52a2dcd5e2cd84fc86bfb600f1e98dd05711fafc))
  - [x] Made Css changes to the user search page (#982) ([0c474548](../commit/0c474548f9557d5e70f4f0a8d673aaefd7ca6112))
  - [x] Made some basic css changes (#887) ([cffb73f1](../commit/cffb73f1406e3a55301f028958d72d3c27a1e176))

## Giovanni Di Milia
  - [x] Bumped edx-api-client requirement to latest version ([fc8c07ce](../commit/fc8c07ce65ce60ac392c29c00db58d30dd70db1c))
  - [x] Only one role per User can be assigned ([fbaac2f8](../commit/fbaac2f81af57f2eec4129094baeb40f3b2fed8c))
  - [x] Added Financial Aid basic models ([3b0c3524](../commit/3b0c35248f540b0545dc8b61b775bbe450c1840e))
  - [x] Sending one email per recipient ([bee8f7ac](../commit/bee8f7acc38e349f70aa0a87f7ea674cb51a0e42))
  - [x] Added elastisearch auth ([d6f155f4](../commit/d6f155f416436cbb6470dbff0a07d4f3ec669dda))
  - [x] Comments on PR ([efab73e3](../commit/efab73e3a524f467a64c2ead9bdd3b42e878138a))
  - [x] Small comment change ([43f8445e](../commit/43f8445e232599ac4df20ca45b0edd3853c57730))
  - [x] Fixed linting ([452bd5e5](../commit/452bd5e501076d4e07db0c4f768a7d1a1090a707))
  - [x] Added tests ([ba7ebe3c](../commit/ba7ebe3cce90f33174fd01878d7e1df28afac2dc))
  - [x] Added POST support for program enrollments ([aec4e59a](../commit/aec4e59a8b3a3eea81190bff5fc7766700e8ad01))
  - [x] fixed linting ([0cd5cf20](../commit/0cd5cf20b0237a00797400161dd6fabddf8e348f))
  - [x] Added tests ([6dfe8b34](../commit/6dfe8b34ba4baea313e9810641790bd3579d93bf))
  - [x] Changed docstring ([7cc6aae6](../commit/7cc6aae641a7436470ffa8484464cc73c1ea31f3))
  - [x] Added REST API for user enrolled programs ([c39a0939](../commit/c39a0939c660cd0525e5ac8f82c7be436391e9b2))
  - [x] Celery now loads the environment in Docker ([4e50ff50](../commit/4e50ff50a491ed17041624302200460f3f2b4c5c))
  - [x] Added security and tests to the Search Rest API ([a11fe4e5](../commit/a11fe4e5299ae5a9ae0007ea6632cc299033d874))
  - [x] Added Search REST API ([603bb14b](../commit/603bb14bed50c3373f10d7273b6c46044eb1b178))

## Amir Qayyum Khan
  - [x] Fixed rotation of progress widget circle (#1088) ([10041484](../commit/10041484cd617b7ca59e446048849f7f2c8d7d85))
  - [x] Fixed learners layout (#1026) ([18e361c6](../commit/18e361c653414cbe7c16a361427c7e1049e6c488))
  - [x] Made progress widget get values from respective program (#1072) ([e18f0794](../commit/e18f0794b8a0886a845e6614086dbf6e1c76be5c))
  - [x] Fixed course display on dashboard (#997) ([1d68860b](../commit/1d68860b2ee3c24396e863f3ebdb5ec57b66feca))
  - [x] Fixed settings page styling (#1014) ([a859e3d9](../commit/a859e3d9b83f66044f755036a6b98c67834bb6ee))
  - [x] Refactored dashboard page (#993) ([fd4f59a1](../commit/fd4f59a1148ac9fa8143bd7fa3d0c962d9919fe4))
  - [x] Style changes for user page (#864) ([7ff85027](../commit/7ff850279ff32f117ea11b5b85f258442525e321))
  - [x] Added course price in listing (#960) ([b1a04e29](../commit/b1a04e2991d54fd76a0a4830aff62392e7abd377))
  - [x] Added background task that run every 6 hours and update all MM users data from edx-platform (#771) ([77fbf79d](../commit/77fbf79dbd3ae60a7ef0094b22dd9b1d0e4f2dcd))
  - [x] Added widget for progress (#817) ([e548b672](../commit/e548b672792d2549f4bd858a3a23f4565aca8a36))

## Tobias Macey
  - [x] Updated Elasticsearch to use HTTP Basic Auth ([ed3946b0](../commit/ed3946b0485c4f7f33b1207a1af9ca4cacc5fb82))

## George Schneeloch
  - [x] Refactored Toast component (#1084) ([3a9feb07](../commit/3a9feb074e35cef503eaa28e674bf0a346f2ad43))
  - [x] Added order fulfillment API for CyberSource (#913) ([15fcad80](../commit/15fcad802d0954a98c892c2d8f2c4d8ba059e15c))
  - [x] Removed wow.js (#1062) ([b99e0d20](../commit/b99e0d20527782d096a50c01eb11018673213c93))
  - [x] Renamed CoursePrice to CourseStatus (#1037) ([7aa86c22](../commit/7aa86c225059ed82d84f2208a23d11ffca10b07b))
  - [x] Removed course status (#1033) ([4a01973d](../commit/4a01973d6be412dab8c75dbcdcc1dc9c57bc3767))
  - [x] Renamed dashboard API statuses (#1028) ([b51590d2](../commit/b51590d2372abe0f51fbc3b2fa75d22a79463c7b))
  - [x] Updated CMS help text, updated thumbnail size (#1016) ([a07ff7b1](../commit/a07ff7b1f280a4aeb22364e8aea60410f4f1916c))
  - [x] Added enrollment dialog (#1000) ([44529b3c](../commit/44529b3cffd4a63617ca3989a477a979574d7772))
  - [x] Added program selector menu (#976) ([a8feab98](../commit/a8feab987456c69ca6926d53dbacbb5463be37a6))
  - [x] Filtered out programs which are not live from program enrollments API (#979) ([4697a326](../commit/4697a32627d90ab9e6abc7841505cd7fd81db403))
  - [x] Fixed course tests (#978) ([7f80d6ee](../commit/7f80d6eeca70484a71f1a62d64fe55e35181e610))
  - [x] Made edx_level_of_education read only (#972) ([56e282ca](../commit/56e282ca4a23266bde7ff8e5e91a7b28fa200f4e))
  - [x] Added code to get and add program enrollments (#968) ([dcb9a297](../commit/dcb9a297c0a542a81285bd590dc86593494e472d))
  - [x] Removed signals creating or deleting a ProgramEnrollment (#964) ([3450320f](../commit/3450320f34f25bbc37a7bb67b91491a4761820cb))
  - [x] Added some server side verification for profiles (#956) ([1619407b](../commit/1619407baf8a902f53ab6fb82983614610a9d702))
  - [x] Added nationality, removed birth city and state (#961) ([e1106c0d](../commit/e1106c0d131b0e96f69958995330958955883d4e))
  - [x] Split long line into multiple lines (#962) ([ad232ca3](../commit/ad232ca3caa3f19f5de60ddc7d136d7dff2f4d19))
  - [x] Added test case to mock out elasticsearch (#902) ([615250a4](../commit/615250a4d8e46f7bbdbe00f66ab0a112f8df0f8a))
  - [x] Switched Heroku to Python 3.5 (#959) ([30ead584](../commit/30ead5845d343088999e1245f5ef59147612a356))
  - [x] Removed CLIENT_ELASTICSEARCH_URL environment variable (#947) ([2066b992](../commit/2066b99214f1d8af309622b501ace091c4c287f3))
  - [x] Fixed react warnings, added check to error on React warnings (#942) ([dd1c981c](../commit/dd1c981c67ad68e5fe8a03add447533ef087bf43))
  - [x] Added generic type to Dispatcher (#945) ([c0a4357c](../commit/c0a4357c460c84baee2f50c3a4363914c20ebc64))
  - [x] Added API to create an order and a button to purchase via CyberSource (#897) ([5ae57e82](../commit/5ae57e829b97f4accd5b3bb4121973c4d75f16e1))
  - [x] Switched to use enzyme in IntegrationTestHelper (#911) ([5bbc8c73](../commit/5bbc8c736df3562fa723a0ddca4aa7c9746b1244))
  - [x] Updated node version in heroku (#907) ([9fe735fd](../commit/9fe735fdbb74487c58415ce75b61bb3154a13048))
  - [x] Added CoursePrice model (#895) ([f8dc67a9](../commit/f8dc67a982808bc7df97b9d9a2b29ce12953e3d8))
  - [x] Added ecommerce models (#894) ([2d2b1d49](../commit/2d2b1d49b68894619e2f6480ac0a24ee8819264a))
  - [x] Moved material-design-lite CSS import before our CSS imports (#886) ([c60a655c](../commit/c60a655c6ecd901b6275a6fc231f8a37dd25e937))
  - [x] Fixed CSS for dashboard user card (#868) ([cbab6106](../commit/cbab6106acf2ea06b2c3ec6e94641b46ee5c5b52))
  - [x] Implemented redesign of dashboard page (#836) ([35f5f329](../commit/35f5f329a8df4100a96a0d0c9130c662af74a00d))
  - [x] Fix CSRF handling ([46258c23](../commit/46258c23c5245c1560f1a720e825423f49bb8cf6))
  - [x] Replaced filtering with hierarchical filtering (#815) ([07d95681](../commit/07d9568160bed8d0bb9307b871d036928f1c30a9))
  - [x] Enforced permissions on profiles REST API (#790) ([c19149da](../commit/c19149daffc95cd6e8db87dd93828e39626dfdd1))

## Alvin Siu
  - [x] Implemented backbone for review financial aid page (#1071) ([35d7cc61](../commit/35d7cc617bf5f25746f3e6b878f31a1544bee88c))
  - [x] Financial Aid: creating new requests (#1053) ([d45a13b4](../commit/d45a13b44162660f1fa32938a200eec59a790c27))

## David Baumgold
  - [x] Standardize on dash separators for Sass ([3e31e120](../commit/3e31e120a8737250c50f4cbedd66808597f61a53))
  - [x] Updated section numbering ([30972721](../commit/309727218b33959898922c08d2a0846ad0f33cc6))
  - [x] Improvements to installation process documentation ([0e06e2d9](../commit/0e06e2d93033b0d74115f19056ede98ead7435bd))

## Gavin Sidebottom
  - [x] Realistic user fixes for social username and program enrollments ([28ebe985](../commit/28ebe9850a93ee2d6bbe11917c75ff304f67be44))
  - [x] Added faculty CMS models ([5c6d4e6c](../commit/5c6d4e6cf79711db738a5d39d7c4bfb447b61557))
  - [x] Set &quot;Place of Birth&quot; facet to accept multiple values ([d4d4b9e7](../commit/d4d4b9e7c01288d7cbdfff6df3a8492ca0e6e6b0))
  - [x] Set search facets to be open by default ([c7b07881](../commit/c7b078816c37501d1b6b47f75d7e35232612a8ee))
  - [x] Removed privacy page from signup flow ([7a15f058](../commit/7a15f0588d7a135c862802d5853ddcef72596d6f))
  - [x] Updated UX for work history page of the signup flow ([e9edfa6e](../commit/e9edfa6e23f87cd27f5d650cdb66fab216dc7851))
  - [x] Updated UX for education signup screen ([68b05d9b](../commit/68b05d9bfd352b03a9948ae26373367978255237))
  - [x] Removed TOS checkbox and validation from signup page ([516123ec](../commit/516123ec2654ce7158d90da59d4c5bafd0a1a874))
  - [x] Fixed key name for search request API param ([de94d5cb](../commit/de94d5cba8e1c8b372d8cc831bf4ba7b77e4c45e))
  - [x] Hooked up front end to mail API endpoint ([7f611374](../commit/7f611374cba80d515a7fbc65ebf61f8757817d25))
  - [x] Added API endpoint to send text email to a list of recipients ([d10614f8](../commit/d10614f8afa9e2774f92424c7f7da4ad1fcd6681))
  - [x] Added program grade filter and histogram to UI ([cb76b37a](../commit/cb76b37a9facd02f44af09b3328a90d7d177ef5e))
  - [x] Fixed program and social username creation in realistic search data generation ([61f21c3c](../commit/61f21c3c5fce90aafbbb31126fbf34927641910b))
  - [x] Added program grade to search result UI ([06a67c2f](../commit/06a67c2f84a92c0a63c7c42f948307796c78dc45))
  - [x] Added program grade to ES index to support filtering by grade ([94695497](../commit/94695497347dabcb26b3c995f2fb696091578a2b))
  - [x] Updated realistic user data to include users with different current country and birth country ([130bc1c2](../commit/130bc1c2753a8ef30a56dff92187caa440ec012a))
  - [x] Changed indexing structure and logic to use a user&#39;s program enrollments ([663d8726](../commit/663d872695c5a49b0120b2f6ed7feab07cbf575d))

## Alice Pote
  - [x] Deleted Jumbotron ([3afab80f](../commit/3afab80f0ea5e9226616df7a592dee230e2f95bb))
  - [x] Implemented redesign of program page ([ee0086e5](../commit/ee0086e568118c7f88490357d0057496976e54e6))
  - [x] Changed travis.yml around a little ([969de5b5](../commit/969de5b5b1edff201a49f6cec26ba2e5eb2ff733))
  - [x] Implemented &#39;personalized pricing&#39; box on dashboard ([868867af](../commit/868867af45e64678fabbbbba01d9e2ab2d9822b3))
  - [x] Added signup dialog to homepage and program pages ([9a5e17e3](../commit/9a5e17e36a4d8586dbd18e19eac918ec52e734a7))
  - [x] Disabled SanctuaryJS run-time type checking in production ([38430f62](../commit/38430f62a4a4e8e4ee4710544f897fc8a8780fae))
  - [x] Installed sass-lint and started configuring ([e85a751e](../commit/e85a751e887e19c3ff59bc183a4f5ebeadd0601b))
  - [x] Fixed improper JSON formatting ([0a4d8eb8](../commit/0a4d8eb89f9cbcd6c317afe1919135e0b90e5b2c))
  - [x] Rewrote actions to use &#39;redux-actions&#39; ([37932bc3](../commit/37932bc3ece485e838d98626c43e4a7cfee3ebc8))
  - [x] Added link to ToS page ([6803e9d5](../commit/6803e9d51bded05ae089bd11e44e93ecde5cb596))
  - [x] Added celerybeat-schedule to gitignore ([e883357d](../commit/e883357d0bf38db4b0235fc17825f265a17d8208))
  - [x] Added new ToS page ([0e879632](../commit/0e879632e6efe46a0fea58976963731b7760fd05))
  - [x] Added validation for the email composition dialog ([28594ace](../commit/28594ace9c2d8d416f1a91ef8ecfa66a67a089c8))
  - [x] Removed switch validation from profile flow ([ccca0744](../commit/ccca0744332fe94b3f39d1608a04b7dee46b9ba0))
  - [x] Removed &#39;new group from selected&#39; button ([c9e899db](../commit/c9e899db88dcfbfb2cf8d0eefe6a0879d9adb718))
  - [x] Added functionality for composing emails on the LearnerSearch page ([b1b107b5](../commit/b1b107b50e424b80ebd9cefb2a300a57d4752511))
  - [x] Implemented a sort dropdown menu for the Learners search ([d8b57306](../commit/d8b573064a091859e099119a9fe94c0d7ca0d0ed))
  - [x] Implemented new design for the profile progress widget ([84d12bab](../commit/84d12babe5bdba99eddbea285818e1315703c637))
  - [x] Made LearnerResult avatars round ([a8bb322c](../commit/a8bb322c57c54ca7e093b0ecf6f8a76c82607f59))
  - [x] Set the cursor to &#39;pointer&#39; on the filter visibility toggle ([a3524865](../commit/a3524865504bc43be19485a1483782c5272060aa))
  - [x] Added &#39;clear all filters&#39; to learner search ([3318dd0d](../commit/3318dd0d0e67194a18f73ba2722f0f8df1d8fc97))
  - [x] Added UserChip to search results ([c9461c4f](../commit/c9461c4ff223272a9d58f31780571e6bd41c8873))
  - [x] Fixed webpack hot-reload config ([08177748](../commit/081777484ff2ffbc1b7bde087311b9102e36b71f))
  - [x] installed flow v0.30.0 ([4db4af52](../commit/4db4af522099bb4d68d7450ef0ce97d8ac60221d))
  - [x] fixed JS console error (&#39;key&#39; prop required) ([ae2d5808](../commit/ae2d5808efddb78da684960f359b15f74cd82416))
  - [x] Passed onRequestClose callback to ToS Dialog ([05460891](../commit/054608915d09c2dc3d103a096ada4b6cc863c513))
  - [x] Added TermsOfServiceDialog to Profile flow ([f1f4922d](../commit/f1f4922d5e18fbfec894fd17477d38c40c1c5601))
  - [x] Implemented new profile form design ([854bd070](../commit/854bd0708982f6ae2b78c234c5f4ba9b072ccf15))

## annagav
  - [x] Fix mailchimp signup bug ([32ebb9e8](../commit/32ebb9e8d69de74fea0aae7f695bebda904356ad))
  - [x] Changed Homepage design ([35c56ba6](../commit/35c56ba61fcc3f2b1f2f0bcb053a7149b881cc7a))

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@annagav where is this release deployed?

**Comment by noisecapella** [comment]
micromasters-rc.herokuapp.com

**Comment by amir-qayyum-khan** [comment]
@pdpinch can you assign admin rights to my user to verify https://micromasters-rc.herokuapp.com/learners/ and price related things

```
You are authenticated as amir_qayyum, but are not authorized to access this page. Would you like to login to a different account?
```

**Comment by noisecapella** [comment]
@annagav check off your boxes! :ballot_box_with_check: 
I'll look at @singingwolfboy's changes

**Comment by giocalitri** [comment]
done!

**Pull request merged**
