### PR TITLE
Added faq on error pages

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#4915 

#### What's this PR do?
- Adds the FAQ footer link to `404`, `500` error pages

#### How should this be manually tested?
To test it locally you will need to set `DEBUG` to false and then generate any of 404 or 500 error pages.

#### Screenshots (if appropriate)
screencapture-mm-odl-local-8079-digital-learning-faq-2021-06-07-15_52_03

### CODE REVIEW

**Review by pdpinch — APPROVED** [review]
Thanks!

**Comment by pdpinch** [comment]
Can you add my commit https://github.com/mitodl/micromasters/pull/4917/commits/ffdb0fc61ddd61e684638f8cbc3d5c5babb78614 to add a FAQ link to the error response here? I don't know why the test don't pass. I hope you can figure it out.

**Comment by arslanashraf7** [comment]
Sure, I'll add it in here.

**Comment by arslanashraf7** [comment]
@pdpinch, I've added your commit in here and also attaching the screenshot of how it looks now, with the FAQ link that you added and the FAQ footer part (should I remove the FAQ footer section from here?).

Additionally, Clicking on the `Frequently Asked Questions` opens https://mitx-micromasters.zendesk.com/hc/en-us in a new browser tab which is what we want I suppose.

screencapture-mm-odl-local-8079-abc-2021-06-07-17_17_18

Waiting on tests to pass, I suppose the test that failed is a flaky one.

**Comment by arslanashraf7** [comment]
@pdpinch, All the tests are passed on this one now, Just need your approval on the above comment and I'll merge it after that.

**Comment by pdpinch** [comment]
Thanks Arslan. I think I it's best to have the link and the footer. Please merge

**Pull request merged**
