### PR TITLE
Removing pearson communication code

### LINKED ISSUE #4754: Remove legacy pearson code
We should investigate what is required to remove the unused pearson code. One key thing is we don't want to lose any data during this.

- [ ] Take a look at what code is present and categorize it
- [ ] Evaluate w/ the team how much of this code can be safely removed
- [ ] Remove that code

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #4754

#### What's this PR do?
Remove legacy pearson code
Should also reomve the following config variables:
```
EXAMS_AUDIT_S3_BUCKET
EXAMS_AUDIT_AWS_ACCESS_KEY_ID
EXAMS_AUDIT_AWS_SECRET_ACCESS_KEY
```

#### How should this be manually tested?
nothing should break

### CODE REVIEW

**Comment by pdpinch** [comment]
Can you change the typo in the PR title and your commits? It should be "pearson" with an "a". I'm just planning ahead for when we might have to search the repo for this change.

**Review by rhysyngsun — CHANGES_REQUESTED** [review]
Functionally looking good but a few extra things we should get rid of:

- Move `exams/pearson/constants.py` to `exams/constants.py`
- In `exams/tasks.py` remove the `PEARSON_*` constants
- Remove unused pearson exam settings from `settings.py`
- Remove unused pearson exam env var definitions from `app.json`

**Comment by rhysyngsun** [comment]
@annagav looks like there's a test failure due to the removal of some `settings.py` stuff

**Comment by annagav** [comment]
@rhysyngsun I fixed the tests. Thank you!

**Review by rhysyngsun — APPROVED** [review]

**Pull request merged**
