### PR TITLE
#4455 Home: grow your network

### PR DESCRIPTION
**Pull request by ahmed-arbisoft**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#4455 

#### What's this PR do?
Adds a "grow your network" icon and text in the "Why should I enroll" section on the home page.

#### How should this be manually tested?
Visit the home page. The added content should show up. If the benefits page exists, there should be a link to it with the anchor title "Learn more" at the end of the added content. If the page does not exist this anchor should not be visible.

#### Screenshots (if appropriate)
Screenshot from 2019-11-13 17-43-45
Screenshot from 2019-11-13 17-39-36

### CODE REVIEW

**Comment by ahmed-arbisoft** [comment]
@pdpinch could you please confirm if this is okay? Personally I don't really like the blue anchor color on top of the red, it's not really readable. Please let me know if I should change the color here.

**Comment by pdpinch** [comment]
can you try the same link color as the footer? I think it has a little better contrast.

**Comment by ahmed-arbisoft** [comment]
@pdpinch doesn't seem to help
Screenshot from 2019-11-13 18-04-47

**Comment by ahmed-arbisoft** [comment]
What do you think about this? It's simply white, with a slightly higher font weight.

Screenshot from 2019-11-13 18-07-37

**Comment by pdpinch** [comment]
@abdulkdawson says bold white and underline.

**Comment by pdpinch** [comment]
Please go ahead and merge this after the style change. I'd like to get this up on RC as soon as possible on Thursday.

**Pull request merged**
