### PR TITLE
Remove 'new group from selected' button

### LINKED ISSUE #852: Remove "New Group from Selected" button in search results
We don't have a feature that uses this yet. 

image

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #852 

#### What's this PR do?

removes an unimplemented button

#### How should this be manually tested?

Just make sure the button's absence looks ok!

### CODE REVIEW

**Comment by noisecapella** [comment]
The learner page looks a little odd. On my laptop:

screenshot from 2016-08-25 18-05-50

Not sure if that's caused by removing the button though. If we have an issue to address learner page style issues then :+1:

**Comment by noisecapella** [comment]
Specifically the sort and the pagination buttons don't quite line up with each other, and I'm not sure where the Email Selected button wants to be, it's odd to see it just floating there not aligned with anything

**Comment by aliceriot** [comment]
I think the email button will be sorted out in Rob's pr, not sure about the
pagination/sort buttons.

**Comment by amir-qayyum-khan** [comment]
👍

**Pull request merged**
