### PR TITLE
fix broken link on dashboard view on Mitx Online

### LINKED ISSUE #5164: "View on MITx Online" links on dashboard are broken
### Steps to Reproduce

- Log in to MM as a user who is enrolled in (or has been enrolled in a MM course that is hosted on MITx Online
- View your MM dashboard: https://micromasters.mit.edu/dashboard/
- Click on the link for a course that says `View on MITx Online` (see image below)

### Expected Behavior

- It will take you directly to the course on edX on MITx Online 
   - e.g. `https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+14.310x+1T2022`

### Actual Behavior

- It takes you to this link: `https://mitxonline.mit.edu/dashboard/course-v1:MITxT+14.310x+1T2022`

### Related Issues

- https://github.com/mitodl/micromasters/issues/4993
- https://github.com/mitodl/micromasters/issues/5134 - pay careful attention to this one as it looks like this is what may have broken this link. Ensure that your fix doesn't recreated this issue.

### Screenshot or Screencast

Screen Shot 2022-02-03 at 2 07 23 PM

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #5164 

#### What's this PR do?
fix broken link on dashboard view on Mitx Online

#### How should this be manually tested?
It requires mitxonline integration with micromasters

#### Screenshots (if appropriate)

**Please verify the links at the left bottom of the page**

Screenshot 2022-02-15 at 20 22 55

Screenshot 2022-02-15 at 17 55 59

### CODE REVIEW

**Comment by umarmughal824** [comment]
> @umarmughal824 These screenshots look fine. I just want to confirm:
> 
> * The `View on MITx Online` link will take the learner to the course e.g. `https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+14.310x+1T2022`
> * The `MITx Online dashboard` link will continue to take learners to their dashboard on MITx Online `https://mitxonline.mit.edu/dashboard/`

yeah you got it right that's how the link gonna redirect

**Review by rhysyngsun — CHANGES_REQUESTED** [review]
The code looks good, but I haven't been able to functionally test it tonight because my MM setup is broken somehow. Feel free to have someone from arbisoft smoke test it if they're able.

**Comment by umarmughal824** [comment]
> The code looks good, but I haven't been able to functionally test it tonight because my MM setup is broken somehow. Feel free to have someone from arbisoft smoke test it if they're able.

They didn't have mitxonline integrated with micromasters ever. I am not sure if we have enough time to wait for them to do that setup.

**Comment by pdpinch** [comment]
@annagav could you take a look at this?

**Review by annagav — APPROVED** [review]
Functionality works for me 👍

**Pull request merged**
