### PR TITLE
Upgrade wagtail to 1.6.3

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
#1286

### CODE REVIEW

**Comment by Ferdi** [comment]
@annagav did you do any testing if anything breaks ?

**Comment by annagav** [comment]
Yes it breaks, but I haven't looked into it closely...

**Comment by pdpinch** [comment]
@annagav this is passing tests. What's failing?

**Comment by annagav** [comment]
It does not fail for me anymore. It might have been a different issue.

**Comment by giocalitri** [comment]
I do not see any problem after the upgrade. 👍

**Pull request merged**
