### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by annagav**
## George Schneeloch
  - [x] Added semicolon enforcement rule ([eb33aac3](../commit/eb33aac37c2ff83e4cffccb2dd3cee8912f84236))
  - [x] Removed unused authentication state, use profile state instead for name ([560e0338](../commit/560e0338646f34684598ad539bdbe6da10590e33))
  - [x] Updated frontend for changes to dashboard API ([2dbd6135](../commit/2dbd61352897f18dce4695df05c18b2c42d89737))
  - [x] Added page for terms of service ([7b802f70](../commit/7b802f70002a4e793a61c1fee8c54c7024e547b6))
  - [x] Moved onUpdate from Route to Router ([bebba21d](../commit/bebba21d77eba15865b63df94d08cb4caf8e618a))
  - [x] Added script to run development server on OS X without docker ([695891ef](../commit/695891ef0d8e293da479a99f75b2c02180424a8e))

## Alice Pote
  - [x] Added employment to profile model, expanded employment tab ([46945ea7](../commit/46945ea7a7ebe0e3cdc4311e68bd44c0e7ec7a5d))
  - [x] Fixed JS console error with react-router history ([18192559](../commit/18192559e24591e74579dc9f5518fd75cc6dd80d))
  - [x] Added `singleTest` to package.json for running a single JS test file ([92211c27](../commit/92211c27718164ebe2ea1f6178cc6ff0f6e6d496))
  - [x] Made `npm test` run the tests ([65b49d6b](../commit/65b49d6bcc888814951d231302e3d711fcf69311))
  - [x] Incorporated updated homepage design ([91241ed8](../commit/91241ed8ee7bf941150ea4325acc6716f59a9df1))
  - [x] Added ProfileTab utility class ([f5ac422c](../commit/f5ac422ca85172e2a712ec7c8523f44b9e647e00))

## annagav
  - [x] osx_run script ([975f06b3](../commit/975f06b34679f0a1cbede468d435cb6d42c7bc76))

## Giovanni Di Milia
  - [x] Dashboard JSON refactored ([99953fef](../commit/99953fef4ebbd92d86c17a5955e7ddaf43991038))
  - [x] Pointing the edx-api-client requirement to release ([f6d18329](../commit/f6d1832984dc5c67165243937a8b4d0a23a39d7d))
  - [x] After login the user is redirected to dashboard ([49599fec](../commit/49599fec0851728e06c346e197f1705b2347b676))

### CODE REVIEW

**Comment by annagav** [comment]
Please verify your commits!

**Comment by giocalitri** [comment]
I think my commit c78da45c was also in the 0.6.0 release.
Are we sure this release is correct?

**Comment by annagav** [comment]
This probably happened due to my tagging mistake. Let me fix it!

**Comment by annagav** [comment]
Release notes updated!

**Pull request merged**
