### PR TITLE
Removed 13px Adwords iframe height and added Adwords tags to only home page and program page

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
- fixed https://github.com/mitodl/micromasters/issues/2390

#### What's this PR do?
- Moved Adwords tag to bottom and given white background.
- Limited Adwords tag only to home and program pages.

@pdpinch @roberthouse54 
#### Screenshots (if appropriate)
screen shot 2017-01-23 at 4 21 16 pm

### CODE REVIEW

**Comment by roberthouse54** [comment]
I am not seeing this in the deployed version (or am I missing something?) Also, I thought you were suggesting leaving it at the top and just adding "display: none"? Did that not work?

**Comment by roberthouse54** [comment]
Also, I just want to check... the goal is to have this on all pages in the app? Or just on the marketing site?

**Comment by amir-qayyum-khan** [comment]
@roberthouse54 
- deployed version? this is PR is not merged yet.
- yes i was, people suggested that that hiding iframe dont change the functionality of adwords. But i thought that they are using it i may have a purpose.

**Comment by roberthouse54** [comment]
I clicked the "View Deployment" link. I then checked the page source and I did not see the code. Maybe I am missing something.

I am just wondering why, instead of hiding the div, you instead moved it to the bottom of the page with a white background.

**Comment by amir-qayyum-khan** [comment]
>I clicked the "View Deployment" link. I then checked the page source and I did not see the code. Maybe I am missing something.

it seems environment variable is not fix for https://micromasters-ci-pr-2410.herokuapp.com/. locally it is working  


>I am just wondering why, instead of hiding the div, you instead moved it to the bottom of the page with a white background.

i did is because of views like these:
- `This may actually stop some browsers loading the tracking iframe, so I'd suggest testing this across all the common browsers before deploying to a live site.`
- `Google do a lot of checking for simulated fake data. I wouldn't be suprised if google filtered out results when the iframe is hidden. There is a reason they put the iframe there.`
- `the problem is I don't know and I wouldn't like to get banned. After some time of digging I found a solution that seems to work (insert script in a hidden div)`

**Comment by roberthouse54** [comment]
OK, I am now able to see this on the deployment. I do not see any programs, so I cannot test the Program page. But I assume the program page would have a white line separating the "Instructors" slideshow and the footer, both of which have dark backgrounds.

And again... just to clarify: this is only on the home page and the program page, correct?

**Comment by amir-qayyum-khan** [comment]
- yes, this is only on home and program

**Comment by roberthouse54** [comment]
Yes, but if you go to an actual micromasters site, you will see that there is an Instructors section at the bottom, which has a black background.

image

**Comment by amir-qayyum-khan** [comment]
@roberthouse54 i made color transparent, so that it will be work on both black and white

**Comment by roberthouse54** [comment]
Can you post a screenshot of how this looks on the program page when there are some faculty in a program?

**Comment by roberthouse54** [comment]
I think a slightly better solution might be to change the background to match the footer background color (#000), as in your current implementation, "transparent" means it will inherit the page background which is white. So on the program page, I think there will be a white stripe between the Instructor section and the footer. As long as this always shows up immediately above the footer, I think a black background would be preferable.

**Comment by amir-qayyum-khan** [comment]
Done @roberthouse54

**Comment by roberthouse54** [comment]
looks good 👍

**Comment by singingwolfboy** [comment]
Since you're changing this code anyway, can you change the template variable `APIKEYS. ADWORDS_CONVERSION_ID` to `APIKEYS.GOOGLE_ADWORDS`, the way I've done in #2280? The `APIKEYS` dictionary should have keys named after the API that is being used.

**Pull request merged**
