### PR TITLE
raising 404 for records

### PR DESCRIPTION
**Pull request by HamzaIbnFarooq**
#### What are the relevant tickets?
https://github.com/mitodl/internal/issues/31

#### What's this PR do?
raise 404 for anonymous users on records

#### How should this be manually tested?
Just anonymously access some records, it should be giving 404.

### CODE REVIEW

**Review by arslanashraf7 — APPROVED** [review]
👍 Works well.

**Comment by arslanashraf7** [comment]
@HamzaIbnFarooq, I've reviewed and tested your latest commit and things work as intended. With the latest change the `Send Learner Record` and `Share` and functionality would probably become invalid as well, Should we hide these buttons?

cc: @pdpinch

**Comment by pdpinch** [comment]
> With the latest change the Send Learner Record and Share functionalities would probably become invalid as well, Should we hide these buttons?

This is true, but we can address that in a follow-up.

**Review by arslanashraf7 — APPROVED** [review]
👍

**Pull request merged**
