### PR TITLE
add support for multiple signatories in certificate design

### PR DESCRIPTION
**Pull request by HamzaIbnFarooq**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots

#### What are the relevant tickets?
https://github.com/mitodl/micromasters/issues/4788

#### What's this PR do?
add support for 4 signatories in certificate design, previously the design started to break at 4.

#### How should this be manually tested?
Create a certificate with 4 signatories and see if the print works well.

#### Screenshots (Printed Version)
image

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@HamzaIbnFarooq, Although the code changes are fine I believe there is a noticeable difference in the look & feel of the spacing and overall border of certificate & signatories and that best can be seen when we have less than 4 signatories e.g 3.

I think it would be a good idea to add more screenshots(**Old vs New**) for both normal view and print view in the description of the PR and I think we'll have to wait for @pdpinch to review them.

Just to add a thought, A solution could be to support the old design for 3 signatories, and when there are 4 signatories we add these styling classes on the runtime. 

I'm adding some screenshots that I took just to give an idea.
**(Old Print with 3 signatories)**
Screenshot 2021-03-09 at 7 37 21 PM
**(New Print with 3 signatories)**
Screenshot 2021-03-09 at 7 38 37 PM

**Comment by HamzaIbnFarooq** [comment]
Thanks @arslanashraf7 for pointing this out. I think rather than looking at a comparison with previous versions, we should have a comparison with edX:
**3 Signatories in edX:**
image

**3 Signatories in MM:**
image


**4 signatories in edX:**
image

**4 Signatories in MM:**
image

**Comment by pdpinch** [comment]
Thank you both for your care and diligence on this. 

The goal is to have our certificates look the same as edX’s. Looking at the screenshots from Hamza, I think this is OK as is, with one stylesheet and the signatures crowded at the top when there are only 2.

**Review by arslanashraf7 — APPROVED** [review]
Looks good 👍

**Pull request merged**
