### PR TITLE
Changed location order to Country -> State -> City

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

#281 

#### What's this PR do?

Changes the order of the location fields on the personal and education tabs (they were changed in #312 for employment).

#### Where should the reviewer start?

The changes are in `PersonalTab.js` and `EducationTab.js`.

#### How should this be manually tested?

Make sure that you can edit the location fields on both of these tabs, and that nothing got mushed up.

### CODE REVIEW

**Comment by giocalitri** [comment]
it looks good
I noticed that the `state or region` in the education tab does not provide suggestions as in the personal tab. 
I suppose this problem is not related, but I would like a confirmation

**Comment by noisecapella** [comment]
@giocalitri it's not related, I filed an issue earlier for this: #318

**Comment by noisecapella** [comment]
Actually, we should probably just knock out that problem too, as the fix is a one liner

**Comment by giocalitri** [comment]
I am fine keeping it separated, since you already filed an issue for it.
👍

**Comment by giocalitri** [comment]
please next time put `closes` or `fixes` <story_number>, so the story can be closed when the PR is merged

**Pull request merged**
