### PR TITLE
Remove x scroll on program page

### LINKED ISSUE #1561: Odd scrollbar on program page
From micromasters-rc, it's a horizontal scrollbar right below the hero image

screenshot from 2016-10-25 16-55-24

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #1561
#### What's this PR do?

Fix x scroll that appears under the tabs on the program page.

### CODE REVIEW

**Comment by roberthouse54** [comment]
There is a bug here, but I think this may be related to the fact that we wanted the tabs to be scrollable, so that they do not wrap on mobile. This is per material design convention for "scrollable tabs" see: https://material.google.com/components/tabs.html#tabs-usage

Ideally the tabs could scroll, but not display a scroll bar.

@aliceriot

**Comment by noisecapella** [comment]
Can you rebase on master to fix the tests?

**Comment by annagav** [comment]
I updated the code to keep the scroll and hide it.

**Comment by pdpinch** [comment]
So, how can we test this? Look at it on a phone and swipe?

**Comment by annagav** [comment]
If the bug was present on your laptop you can test it there. Otherwise, I could see it on windows machine.

**Pull request merged**
