### PR TITLE
Removed rejected status

### LINKED ISSUE #1250: Remove rejected status from FinancialAid

### PR DESCRIPTION
**Pull request by alvinsiu**
#### What are the relevant tickets?
Closes #1250 

#### What's this PR do?
Removes `FinancialAidStatus.REJECTED` as a valid status for a `FinancialAid` object.

#### Any background context you want to provide?
The original idea was to allow staff to either accept a financial aid application at a certain tier or reject the application (which would automatically assign them with the zero discount tier).  The new idea is to remove the idea of a rejected application and change "accept" into "save".  This way, staff don't "accept" or "reject" applications, but rather "save" them at whatever tier they deem correct (which can be the zero discount tier).

### CODE REVIEW

**Comment by noisecapella** [comment]
It looks like this needs a migration for the change in the statuses

**Comment by noisecapella** [comment]
Ah, beat me to it :)

**Comment by alvinsiu** [comment]
Haha, literally just seconds before :]

**Comment by noisecapella** [comment]
Can you update the docstring in `generate_financial_aid_email` to remove reference to `REJECTED`?

**Comment by alvinsiu** [comment]
Doh!  Good catch - I thought I found all of the results for "REJECT" in the code base - I'll do another search.

**Comment by noisecapella** [comment]
Looks good :+1:

**Comment by alvinsiu** [comment]
@noisecapella It seems `travis-ci/push` errored out during the build before any tests are run:

`The command "docker-compose -f travis-docker-compose.yml run watch npm install --quiet" failed and exited with 1 during .`

Not sure if this is a larger issue, or just a one time problem.  How should I move forward?

**Comment by noisecapella** [comment]
It looks like a one time problem. I restarted the travis build

**Comment by alvinsiu** [comment]
Thanks!  Where is the button for that?

**Pull request merged**
