### PR TITLE
Refactored dashboard page

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
- Fix some issues from https://github.com/mitodl/micromasters/issues/925 
- Fixes https://github.com/mitodl/micromasters/issues/780

#### What's this PR do?
- [x] Remove histogram widget
- [x] Remove tab navigation
- [x] Fix Firefox CSS issue (#780) 

#### Where should the reviewer start?
- See ``App.js, Nav.js``

#### How should this be manually tested?
- see ``/dashboard/`` page

@pdpinch @noisecapella @aliceriot 

#### Screenshots (if appropriate)
screen shot 2016-09-07 at 11 18 18 pm

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@pdpinch @noisecapella 

- Currently on clicking MIT logo it takes user from other pages to dashboard.
- Should i add dashboard link to ``user Menu``, when users are on other pages?

**Comment by pdpinch** [comment]
Amir, unless I'm misunderstanding, changing the logo or the user menu seems out of scope for this PR.

In any case, @roberthouse54 should answer your question.

**Comment by amir-qayyum-khan** [comment]
@pdpinch logo is not changed, I just added Link to existing logo. So that when user click it it will take them to dashboard.

Looking forward to @roberthouse54  answer.

**Comment by pdpinch** [comment]
I see a couple of issues with this screenshot:

- [ ] The text "You need to upgrade..." is suppose to only appear when the user clicks on the question mark. But more importantly, we should check with @roberthouse54 to see if this is needed at all, when the program doesn't offer financial aid.
- [ ] If we do want the (?) icon, it's the wrong color, and it should be next to the price, not in the left column. 
- [ ] It shouldn't say "(enrolled)" in parentheses after the course title. 
- [ ] Where's the start date? Or is that another for another PR?
- [ ] The buttons look wrong

@roberthouse54

**Comment by amir-qayyum-khan** [comment]
@pdpinch these issues are from master branch. And these things was not part to this PR. These are part of point ``Match design``. 
I was planing to make another PR for that. 
But now let me add this point in this PR as well.

**Comment by noisecapella** [comment]
I can confirm the Firefox issue is fixed, and everything else looks good to me :+1:

**Comment by amir-qayyum-khan** [comment]
let me merge this and open new pr for dashboard UI fix, what do you say?

**Comment by pdpinch** [comment]
It's fine to merge. 

You might also want to check with Rob. He just opened a PR that adjust the dashboard CSS.

**Comment by amir-qayyum-khan** [comment]
ok,  i will talk to him on hipchat.  Thanks

On Sep 8, 2016 10:58 PM, "Peter Pinch" <notifications@github.com> wrote:

It's fine to merge.

You might also want to check with Rob. He just opened a PR that adjust the
dashboard CSS.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/mitodl/micromasters/pull/993#issuecomment-245683628>,
or mute the thread

**Comment by amir-qayyum-khan** [comment]
@noisecapella I added dashboard link to ``MicroMasters Portal`` text along with logo

**Comment by amir-qayyum-khan** [comment]
@noisecapella can you please review it?

**Comment by noisecapella** [comment]
This is fine with me :+1:

**Comment by noisecapella** [comment]
@pdpinch I made an issue for your comments: #1009

**Pull request merged**
