### PR TITLE
upgraded uwsgi for incompatibility with mac env

### PR DESCRIPTION
**Pull request by giocalitri**

### CODE REVIEW

**Comment by noisecapella** [comment]
What's the issue being fixed here?

**Comment by giocalitri** [comment]
this was happening while creating my virtualenv 
```
ate);ULEP(stats_pusher_socket);"
    *** uWSGI compiling server core ***
    core/utils.o is up to date
    core/protocol.o is up to date
    [thread 1][clang] core/socket.o
    core/logging.o is up to date
    [thread 2][clang] core/master.o
    [thread 3][clang] core/master_utils.o
    [thread 5][clang] core/emperor.o
    [thread 7][clang] core/notify.o
    [thread 4][clang] core/mule.o
    [thread 6][clang] core/subscription.o
    [thread 0][clang] core/stats.o
    core/socket.c:713:28: error: use of undeclared identifier 'SOL_TCP'
                    if (setsockopt(serverfd, SOL_TCP, TCP_FASTOPEN, (const void *) &uwsgi.tcp_fast_open, sizeof(int)) < 0) {
                                             ^
    1 error generated.

    ----------------------------------------
Command "/Users/gdimilia/.virtualenvs/micromasters/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/private/var/folders/5c/dfbctwk14vsdvbym2xyych0w0000gn/T/pip-build-scm8gu8b/uwsgi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/5c/dfbctwk14vsdvbym2xyych0w0000gn/T/pip-sp380pao-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/gdimilia/.virtualenvs/micromasters/bin/../include/site/python3.4/uwsgi" failed with error code 1 in /private/var/folders/5c/dfbctwk14vsdvbym2xyych0w0000gn/T/pip-build-scm8gu8b/uwsgi
```

**Comment by noisecapella** [comment]
:+1:

**Comment by noisecapella** [comment]
@giocalitri it looks like the test is failing from an issue that was fixed, can  you rebase against master and repush?

**Comment by giocalitri** [comment]
yep, I figured that out only 5 minutes ago

**Pull request merged**
