### PR TITLE
Updates to the program letter

### LINKED ISSUE #4479: Update Program Letter template
As a course team member, I'd like to have a more flexible template for program letters. 

#### Designs and Mockups

Exampe of the current letter (SCM): https://micromasters.mit.edu/letter/program/ab1a5c1d-4b23-4a94-9e04-dbbf0e5a3694

Desired letter (SDS): [SDS_letter_accomplishment_12.9.2019.pdf](https://github.com/mitodl/micromasters/files/3946022/SDS_letter_accomplishment_12.9.2019.pdf)

#### Acceptance Criteria:

- [ ] Allow for a wider logo graphic (but keep right alignment). This should accomodate the IDSS logo and address shown in the "desired letter" above
- [ ] Move the closing "Cordially Yours" out of the template and into the letter content. This will allow the SDS team to use a different closing than SCM. 
  - [ ] when this commit is deployed, we will plan to make any necessary updates to the SCM-specific data
- [ ] Review the spacing and image requirements for the signatures, so that three will fit in a vertical list, as displayed in the "desired letter" above. 
- [ ] would be nice: replace the current template footer (the name of the program) with another CMS image, similar to the header. 
- [ ] would be nice: the current CMS form has a required field for institution, which doesn't appear in the letter. Can it be removed, or at least made not required? 
- [ ] any changes need to avoid regressions in the SCM letter, since that is already in production.

### PR DESCRIPTION
**Pull request by annagav**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
Fix #4479

#### What's this PR do?
The following changes:
- [x] Allow for a wider logo graphic (but keep right alignment). This should accomodate the IDSS logo and address shown in the "desired letter" above
- [x] Move the closing "Cordially Yours" out of the template and into the letter content. This will allow the SDS team to use a different closing than SCM. 
  - [ ] when this commit is deployed, we will plan to make any necessary updates to the SCM-specific data
- [x] Review the spacing and image requirements for the signatures, so that three will fit in a vertical list, as displayed in the "desired letter" above. 
- [ ] would be nice: replace the current template footer (the name of the program) with another CMS image, similar to the header. 
- [x] would be nice: the current CMS form has a required field for institution, which doesn't appear in the letter. Can it be removed, or at least made not required? 
- [ ] any changes need to avoid regressions in the SCM letter, since that is already in production. 

#### How should this be manually tested?
Create a program letter and set up the CMS to be able to view it, enter the signatories and corresponding images. Make sure it looks as described in the issue.

### CODE REVIEW

**Comment by annagav** [comment]
Screen Shot 2019-12-11 at 3 50 33 PM

**Comment by pdpinch** [comment]
Thanks Anna. Will the new template be able to accommodate this header:

image

and this footer:

image

**Comment by annagav** [comment]
I added footer and header text:
Screen Shot 2019-12-12 at 2 41 40 PM
Screen Shot 2019-12-12 at 2 19 44 PM
Screen Shot 2019-12-12 at 2 18 55 PM

**Comment by noisecapella** [comment]
I'm setting some browser console errors:
Screenshot from 2019-12-12 14-52-01

**Comment by annagav** [comment]
@noisecapella this error seems to be present in production as well. Should I try to fix it here?

**Pull request merged**
