### PR TITLE
implement a sort dropdown

### LINKED ISSUE #759: Search: Implement sort of search results
As a faculty or staff member, I'd like to be able to sort the search results by any of the fields that appear in the results. To be specific: 

> Name A-Z, Name Z-A Grade High-to-low, Grade Low-to-High. 

For location, sort alphabetically by country, then by city. 

The proposed UI is at https://invis.io/9B804AMXA#/172058723_Instructor_User_Search : 

image

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #759 

#### What's this PR do?

This adds a sorting option to the 'Learners' page. SearchKit provides a sorting component which we're using, we just basically pass it an array of objects describing the fields we want to sort on, their labels, etc.

### CODE REVIEW

**Comment by giocalitri** [comment]
screen shot 2016-08-22 at 11 55 56 am

Grade High to Low does not work.

**Comment by aliceriot** [comment]
ah, indeed it does not >_<

**Comment by aliceriot** [comment]
I'll look into it, but I have no idea why it's not working

**Comment by giocalitri** [comment]
screen shot 2016-08-22 at 11 55 56 am 2

The sort box is different from the other and its font looks different as well

**Comment by giocalitri** [comment]
Sorting by Location sorts by Country and then by city: this is not clear by the title.
Same for Sorting by Name (Last Name and then First Name).
@roberthouse54 , any input on this?

**Comment by Ferdi** [comment]
My suggestion:   

- Sort by country only
- Make 2 separate sorting , first name  and last name.

**Comment by giocalitri** [comment]
@Ferdi
> Make 2 separate sorting , first name and last name.

This means that if I sort by Last name and then by first name, the second sorting will override the first: is this ok?

**Comment by Ferdi** [comment]
Yes, treat them as independent sorting. That's what I meant. Just a suggestion though.

**Comment by aliceriot** [comment]
sounds good

**Comment by aliceriot** [comment]
sort for the grade fields should be fixed, I had just made a pretty silly error 😛

**Comment by giocalitri** [comment]
👍

**Pull request merged**
