### PR TITLE
Implemented new user menu design

### LINKED ISSUE #724: implement new user menu design
nav_header

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

this closes #724 

#### What's this PR do?

This implements the new design for the user menu. This is just react + css, I removed the bootstrap components from this completely.

#### Where should the reviewer start?

Take a look over `UserMenu.js`, read through all the CSS.

#### How should this be manually tested?

Make sure the look and feel matches what's shown in the screenshots in the associated issue.

### CODE REVIEW

**Comment by giocalitri** [comment]
code seems reasonable to me

**Comment by giocalitri** [comment]
Problem 1: if I click outside the menu, the menu does not disappear.

screen shot 2016-07-28 at 11 18 21 am

**Comment by giocalitri** [comment]
Problem 2: the cursor on the menu is wrong.

**Comment by aliceriot** [comment]
@giocalitri thanks for the feedback, I fixed the cursor issue and I'm looking into solutions for detecting outside clicks in React easily, I'll let you know when it's ready for review again.

**Comment by giocalitri** [comment]
ok

**Comment by aliceriot** [comment]
@giocalitri I added a package to enable to the click-outside behavior. Now it should close the menu if you click anywhere outside of it while it's open. Clicking on the user name / portrait component when the menu is open should also close it.

**Comment by giocalitri** [comment]
LGTM 👍

**Pull request merged**
