### PR TITLE
Replace MicroMaster's certificate text with MicroMaster's credential in app

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/micromasters/issues/381

#### What's this PR do?
- Replace text "MicroMaster's certificate" with "MicroMaster's credential".

#### Where should the reviewer start?
- Personal Tab
@aliceriot @pdpinch @noisecapella 
#### How should this be manually tested?
- open /profile, see header of personal tab.

#### Screenshots (if appropriate)
screen shot 2016-05-27 at 3 08 01 pm

### CODE REVIEW

**Comment by pdpinch** [comment]
Is that the only place "certificate" appears in user-facing text?

**Comment by amir-qayyum-khan** [comment]
yes, i searched whole app, this is the only place in current mster.

**Comment by pdpinch** [comment]
:+1:

**Comment by noisecapella** [comment]
I'm going to merge this since @amir-qayyum-khan is out and my PR may conflict with it

**Pull request merged**
