### PR TITLE
Learner dashboard: elective courses

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Related to #4251

#### What's this PR do?
Adding elective courses to the learner dashboard.

#### How should this be manually tested?
Create a passing grade for a course and pay for it to see the progress widget circle fill up:
```
final_grade = FinalGradeFactory.create(user=user, course_run=course_run, passed=True, status='complete', grade=0.8)
CourseRunGradingStatus.objects.create(course_run=course_run, status='complete')
set_course_run_to_paid(user, course_run)
```
Screen Shot 2019-07-19 at 4 50 24 PM
Screen Shot 2019-07-22 at 9 41 39 AM
Screen Shot 2019-07-22 at 9 51 08 AM

### CODE REVIEW

**Comment by pdpinch** [comment]
For courses that are not electives, can we add a similarly-styled label with the text "Core" 

If we do that, will it affect all courses in all programs? That's OK, I'm just asking.

**Comment by pdpinch** [comment]
How does the label work with a longer title, i.e. "Foundations of Development Policy: Advanced Development Economics"

**Comment by annagav** [comment]
@pdpinch yes, we could add the label to core courses as well, and make it conditional on the program having electives.

**Comment by annagav** [comment]
Screen Shot 2019-07-23 at 9 18 19 AM

**Comment by annagav** [comment]
Screen Shot 2019-07-23 at 9 19 36 AM
Screen Shot 2019-07-23 at 9 19 59 AM
Screen Shot 2019-07-23 at 9 20 12 AM

**Comment by pdpinch** [comment]
The wrap behavior isn't ideal, but I don't want to spend time now tweaking it.

**Comment by annagav** [comment]
Added the "Core" label as well
Screen Shot 2019-07-24 at 10 09 36 AM

**Comment by aliceriot** [comment]
@annagav maybe this is really obvious, but I don't see anything in the Django admin: how do I make a course into an elective or core course?

**Comment by annagav** [comment]
@aliceriot In the django Admin create an `ElectivesSet` for the program. Then create `ElectiveCourse` objects for courses that should be elective, also set the `num_required_courses` on the `Program` model to the required number of courses needed to pass the program.

**Comment by aliceriot** [comment]
got it working! the UI works as expected, and the 'core' and 'elective' courses are correctly labelled.

**Pull request merged**
