### PR TITLE
Moved material-design-lite CSS import before our CSS imports

### LINKED ISSUE #885: Move material design lite CSS import before our CSS imports
Right now this file is imported in dashboard.js which is executed after style.js

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #885

### CODE REVIEW

**Comment by aliceriot** [comment]
I support this plan!

**Comment by giocalitri** [comment]
didn't we already (partially) do this and then go back to the current situation? 
Anyway it looks good to me 👍

**Comment by aliceriot** [comment]
:+1:

**Comment by aliceriot** [comment]
oh ok

**Pull request merged**
