### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by annagav**
## Giovanni Di Milia
  - [x] Certificates taken in account in dashboard ([c78da45c](../commit/c78da45c6732d7f21985305aece21495c3d053e5))

## George Schneeloch
  - [x] Fixed striptags requirement issue ([f0bc99d4](../commit/f0bc99d4e512a9411c63af7a598450a3cacfb889))
  - [x] Removed node-sass rebuild step ([cbbe0a0f](../commit/cbbe0a0f482bdc433d86e6181c82174ad251f965))
  - [x] Added fields to factory ([17b07089](../commit/17b07089bfd40b81cd04304a0430853ab27ec171))
  - [x] Added course progress indicator for dashboard ([0d8db9e0](../commit/0d8db9e0e2f9c2fb9a4b94ba15f8c6df6ed74558))
  - [x] Added country and city fields ([c7d30e1f](../commit/c7d30e1fc84152404e82caad6bd2ca6694085279))

### CODE REVIEW

**Comment by annagav** [comment]
Please verify your commits! @noisecapella @giocalitri

**Comment by noisecapella** [comment]
There's a bug in the dashboard which causes it not to display at all. I'll make a PR to fix it

**Comment by annagav** [comment]
This PR was updates. Please verify your commits! @noisecapella @giocalitri

**Comment by giocalitri** [comment]
the edX instance works fine: this is good to go 👍

**Pull request merged**
