### PR TITLE
Installed celery

### LINKED ISSUE #113: Install celery
Requirement for #53

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #113 

#### What's this PR do?
Installs celery so we can use it for updating enrollment data later (#53) .

#### Where should the reviewer start?
micromasters/celery.py

#### How should this be manually tested?
Go to /status/?token=... and verify that the celery setting exists and it's up and running

#### What GIF best describes this PR or how it makes you feel?
http://i.imgur.com/xdPg9kp.gifv

### CODE REVIEW

**Comment by bdero** [comment]
The build failed as expected on heroku because the PR was created before django-server-status was released:
```
No matching distribution found for django-server-status==0.3.2 (from -r requirements.txt (line 6))
```

@noisecapella - there seems to be no way to manually fire off builds for PR apps. Can you trigger a new deployment by pushing to this branch? If there's no change, maybe just rewrite the latest commit with no changes and --amend/force-push.

**Comment by noisecapella** [comment]
Actually I'm not sure we want celery anymore? cc @pdpinch

**Comment by pdpinch** [comment]
Just backlogged for now.

**Comment by amir-qayyum-khan** [comment]
@noisecapella please rebase it.

**Pull request closed without merging**
