### PR TITLE
fix broken link to MITx Online Dashboard

### LINKED ISSUE #5134: broken link to MITx Online Dashboard
### Steps to Reproduce

1. Log in to RC
2. Authorize yourself for the 14.750x exam:
   1. link your account to rc.mitxonline.mit.edu
   2. enroll in 14.750x
   3. pay for 14.750x (if you have trouble with the test Visa account on CyberSource, I found success by using the admin to change the status of my order to `fulfilled`)
   3. using the admin, create a passing grade for yourself
   4. you should be authorized for the exam now
3. Load the dashboard
4. You should see the message "you can access your exam through your MITx Online Dashboad"
5. click the link

### Expected Behavior

- Browser navigates to the mixonline dashboard. For RC this would be at rc.mitxonline.mit.edu/dashboard/
 
### Actual Behavior

- browser navigates to /courses on open edX, a page this is blank (by design) 

If it requires a lot of effort (like, adding yet another setting) to make this link work, I suggest keeping things simple. Just remove the anchor tag and leave the text. This message was originally added to compensate for the fact that the prior link, to register for the course, was single use only. Since that's no longer the case, we don't really need this link any more.

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
fixes #5134 

#### What's this PR do?
fix broken link to MITx Online Dashboard

#### How should this be manually tested?
Will be tested on RC, just check the build is passing

NOTE: After performing all the steps mentioned in the PR description, I found out that we have set up the environment variable MITXONLINE_BASE_URL to https://courses-qa.mitxonline.mit.edu/. But that should be set to https://rc.mitxonline.mit.edu/ and for the dashboard link, I have created the PR.

### CODE REVIEW

**Comment by pdpinch** [comment]
@annagav what links do we use `MITXONLINE_LINK_BASE` for? Should it be pointing to open edX, or to the mitxonline app? (I know, the world was simpler when we were just dealing with edx.org)

**Comment by umarmughal824** [comment]
> @annagav what links do we use `MITXONLINE_LINK_BASE` for? Should it be pointing to open edX, or to the mitxonline app? (I know, the world was simpler when we were just dealing with edx.org)

I did not find any other usage of that environment variable.

**Comment by annagav** [comment]
> MITXONLINE_LINK_BASE

We use it point to Open edX

**Review by annagav — CHANGES_REQUESTED** [review]
You would need to add a new environment variable here to point to MITxOnline and then pass it to the dashboard, and link it wherever there is a link to view MITxOnline dashboard.

**Comment by annagav** [comment]
Please do not change `MITXONLINE_BASE_URL` because we use it for making api calls to open edX

**Review by annagav — APPROVED** [review]
👍

**Pull request merged**
