### PR TITLE
Added timestamp fields to ExamProfile

### PR DESCRIPTION
**Pull request by rhysyngsun**
#### What are the relevant tickets?
#3025 

#### What's this PR do?
This adds `updated_on` and `created_on` fields to `ExamProfile`. We need this because we previously sent the value of `Profile.updated_on` when syncing `ExamProfile` records and we need to be able to update that without affecting the user's `Profile`.

#### How should this be manually tested?
- Create an `ExamProfile` for your user
- Run the command `./manage.py resync_exam_profiles --ids=678,567,567`, which shouldn't match any records
- Run the command `./manage.py resync_exam_profiles --ids=?`, passing your `ExamProfile.id` which shouldn't match the one record
- Run the command `./manage.py resync_exam_profiles`, which should match all records

#### Where should the reviewer start?
See exams/models.py, but bulk of changes are to exams/pearson/writers.py

### CODE REVIEW

**Comment by annagav** [comment]
Would it make sense to put all three operations into one migration file?

**Comment by rhysyngsun** [comment]
Yeah, that's a good idea.

**Comment by rhysyngsun** [comment]
@annagav at most, I'd be able to get it down to 2 migrations, because of the transactions wrapping the migration I can't update the database and change the schema in 1 transaction.

**Comment by rhysyngsun** [comment]
@annagav could you give this another quick look? I separated the latter two migrations to another branch to avoid the data race condition, so the only migration being applied here is to add nullable versions of `created_on` and `updated_on`. The changes I made are the inverse of this diff: https://github.com/mitodl/micromasters/compare/nl/3025-updatable-exam-profiles...nl/3025-exam-profile-timestamp-values

**Comment by rhysyngsun** [comment]
@annagav sorry for all the churn on this. Last change I promise. PR is now just the first migration and the command.

**Comment by annagav** [comment]
works great! 👍

**Pull request merged**
