### PR TITLE
Fixed settings page styling

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
Fixes https://github.com/mitodl/micromasters/issues/936

#### What's this PR do?
- [x] remove tab navigation
- [x] remove avatar header
- [x] separate content into two distinct cards

#### Where should the reviewer start?
- See settingpage.js 

#### How should this be manually tested?
- From menu go to settings page

@aliceriot @pdpinch @gsidebo 

#### Screenshots (if appropriate)
screen shot 2016-09-13 at 6 21 28 pm

### CODE REVIEW

**Comment by aliceriot** [comment]
this generally looks good, but I think the spacing and font sizes are a little off. Can you remove the `margin-top` from `.privacy-form-heading`, decrease the font size for `.privacy-form-heading` to `20px` and set the font-size on `.profile-radio-group` to be `14px`? I think that will bring it in line with the mockup.}

without those changes:

without_changes

with those changes:

changes

mockup:

changes_mockup

**Comment by aliceriot** [comment]
the font-weight should probably be a little higher on `.privacy-form-heading` as well.

**Comment by aliceriot** [comment]
Code looks good, except for making the changes I outlined above. Back to you!

**Comment by amir-qayyum-khan** [comment]
Done @aliceriot

**Comment by aliceriot** [comment]
cool, ui looks good. I'll look through the code again now.

**Comment by amir-qayyum-khan** [comment]
ok

**Comment by aliceriot** [comment]
LGTM :shipit: :+1:

**Comment by aliceriot** [comment]
oh looks like there's a css style error, take a look at the travis build

**Comment by amir-qayyum-khan** [comment]
yes looking
```
static/scss/profile.scss
  42:1  error  Space expected between blocks  empty-line-between-blocks
```

**Comment by aliceriot** [comment]
:+1:

**Pull request merged**
