### PR TITLE
Remove deprecated object handling code for Celery tasks

### LINKED ISSUE #2171: Add celery setting to silence warning
celery_1   | [2016-12-20 16:50:44,434: WARNING/MainProcess] /usr/local/lib/python3.5/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
    celery_1   | Starting from version 3.2 Celery will refuse to accept pickle by default.
    celery_1   | 
    celery_1   | The pickle serializer is a security concern as it may give attackers
    celery_1   | the ability to execute any command.  It's important to secure
    celery_1   | your broker from unauthorized access when using pickle, so we think
    celery_1   | that enabling pickle should require a deliberate action and not be
    celery_1   | the default choice.
    celery_1   | 
    celery_1   | If you depend on pickle then you should set a setting to disable this
    celery_1   | warning and to be sure that everything will continue working
    celery_1   | when you upgrade to Celery 3.2::
    celery_1   | 
    celery_1   |     CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
    celery_1   | 
    celery_1   | You must only enable the serializers that you will actually use.
    celery_1   | 
    celery_1   | 
    celery_1   |   warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

### LINKED ISSUE #2718: Refactor tasks to pass database ids instead of object instances
After talking with @rhysyngsun there is the potential for serialization and memory use problems when passing instances to celery workers. https://github.com/mitodl/micromasters/pull/2701/files#r103470608

We need to do this in two steps to preserve the ability to deal with old Celery tasks which are still in the queue:
 - refactor task to take an id or an object instance, and pass only ids
 - After all old Celery tasks are completed remove the code that handles the object instance

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #2718 
Fixes #2171

#### What's this PR do?
After a release puts the new tasks in place, this code can remove the logic to handle objects in Celery tasks. 

#### How should this be manually tested?
Update your profile and save it. The change should be reflected in the learner search

### CODE REVIEW

**Comment by giocalitri** [comment]
should we set the JSON serializer for celery in this PR?
```
celery_1   | Starting from version 3.2 Celery will refuse to accept pickle by default.
celery_1   |
celery_1   | The pickle serializer is a security concern as it may give attackers
celery_1   | the ability to execute any command.  It's important to secure
celery_1   | your broker from unauthorized access when using pickle, so we think
celery_1   | that enabling pickle should require a deliberate action and not be
celery_1   | the default choice.
celery_1   |
celery_1   | If you depend on pickle then you should set a setting to disable this
celery_1   | warning and to be sure that everything will continue working
celery_1   | when you upgrade to Celery 3.2::
celery_1   |
celery_1   |     CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
celery_1   |
celery_1   | You must only enable the serializers that you will actually use.
celery_1   |
celery_1   |
celery_1   |   warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
```

**Comment by giocalitri** [comment]
Also please rebase

**Comment by noisecapella** [comment]
@giocalitri Yes that's a good idea

**Comment by giocalitri** [comment]
can you please rebase this?

**Comment by giocalitri** [comment]
this should be deployed one release after #2984 and not in the same release, right?

**Comment by noisecapella** [comment]
Yes, to give the old tasks in the redis queue time to execute

**Comment by giocalitri** [comment]
well: this is 👍  but to be merged tomorrow

**Pull request merged**
