### PR TITLE
Make status text consistent with acceptance of faxed FA documents.

### PR DESCRIPTION
**Pull request by asiplas**
#### What are the relevant tickets?
#3392

#### What's this PR do?
Changes wording for consistency with acceptance of both mailed and faxed financial aid documents.

#### How should this be manually tested?
Peer review, perhaps.

### CODE REVIEW

**Comment by asiplas** [comment]
This may be useful in reviewing changes.

[Chicago Manual of Style Ch.6§104](http://www.chicagomanualofstyle.org/16/ch06/ch06_sec104.html)
> 6.104: Slashes to signify alternatives

**Comment by aliceriot** [comment]
Hi @asiplas, thanks for the contribution!

@roberthouse54 what do you think of this wording change?

**Comment by roberthouse54** [comment]
I think it makes sense.

**Comment by aliceriot** [comment]
Cool, gonna go ahead and merge then. @asiplas thanks again for the contribution!

**Comment by asiplas** [comment]
Happy to contribute, I appreciate the work you've all done to pull this
together!

**Pull request merged**
