### PR TITLE
Add unique constraint on coupon code

### LINKED ISSUE #2441: Coupons: coupon code should have a unique constraint
Coupons do not require a coupon code, but there should be only one coupon with a given coupon code in the database

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #2441 

#### What's this PR do?
Adds a unique constraint on coupon code. Note that a unique constraint doesn't apply to null values

### CODE REVIEW

**Comment by giocalitri** [comment]
Just a question: how we'll generate coupon codes to be sure that they are unique?

Anyway 👍 as soon as #2401 is merged

**Comment by noisecapella** [comment]
Currently the user has to use the Django Admin. At some point we would create a script to generate them, maybe a few one time scripts

**Comment by giocalitri** [comment]
if I am not wrong, this can be merged

**Comment by noisecapella** [comment]
Yes, I missed the :+1:

**Pull request merged**
