### PR TITLE
Release 0.49.3

### PR DESCRIPTION
**Pull request by annagav**
## Giovanni Di Milia
  - [x] Added handling of can-upgrade status for past courses ([3cb72cb1](../commit/3cb72cb1a96db8b922344e955d841211e1633d71))
  - [x] Modified user dashboard to handle 400 and 401 http errors ([534b40e6](../commit/534b40e617fb68d04270d8ad36966ab736114dbb))

### CODE REVIEW

**Comment by pdpinch** [comment]
Does this include some commits from the last release?

**Comment by annagav** [comment]
no, its just the tag got attached to the wrong commit.

**Comment by giocalitri** [comment]
is it ready to be tested?

**Comment by giocalitri** [comment]
done!

**Pull request merged**
