### PR TITLE
Added logging and email config

### LINKED ISSUE #32: Add logging and email config
The logging and email config is still missing from the cookiecutter template, so we need to pull it in from teachersportal.

### LINKED ISSUE #35: Configure secure SSL redirect

### PR DESCRIPTION
**Pull request by bdero**
#### What are the relevant tickets?
Closes #32 
Closes #35 

#### What's this PR do?
Adds logging and email configuration settings, as well as app.json

#### Where should the reviewer start?
This is essentially copied from TeachersPortal configuration, so it should only require light review. A good place to start is to check that the application emits logs when `DEBUG` is set to `False`.
Also, that there are no "MICROMASTERS" spelling errors from when I typed it out a couple of times.

#### How should this be manually tested?
In addition to the above, one could set one of the valid `MICROMASTERS_...` vars to true in the docker-compose environment (docker-compose config) and verify that the corresponding setting was applied in the django settings.

#### Any background context you want to provide?
This is one of those things I need to get around to adding to the cookiecutter.

### CODE REVIEW

**Comment by bdero** [comment]
Corresponding PR in teachersportal: https://github.com/mitodl/teachersportal/pull/102/files

**Comment by giocalitri** [comment]
Build is failing

**Comment by bdero** [comment]
Yup, still actively trying to fix it

**Comment by bdero** [comment]
@giocalitri I'm going to pull the TLS redirect out of this PR and put it in another one, since it's causing the build to fail and this PR contains stuff that's essential for testing other PRs in flight/micromasters-ci.

**Comment by bdero** [comment]
Nevermind, I believe I've fixed the issue and kept it in.

**Comment by bdero** [comment]
Ok, this is all set. The TLS redirect piece can be tested by just navigating to http://micromasters-ci-pr-33.herokuapp.com. Notice it 301's to https://micromasters-ci-pr-33.herokuapp.com.

**Comment by justinabrahms** [comment]
:+1: looks good to me. Can you also update the cookie cutter when you have a chance?

**Comment by bdero** [comment]
@justinabrahms Yup, thanks.

**Pull request merged**
