### PR TITLE
New Elective tags for program page

### LINKED ISSUE #4427: Electives restyling
As a learner, I'd like it to be clearer which courses are core and which ones are electives. 

#### Designs

https://invis.io/USUG2T5R7H9#/389364308_Artboard_1

#### Acceptance criteria

- [x] restyle "core" and "elective" labels, with different styling for each
- [x] move labels before course titles on program page
- [x] align labels and course titles on program page 
- [ ] for the PR review, screenshots of the program page, dashboard page and learner record

#### Questions

- **Q:** How can we implement different styling for "core" and "elective" with the current data model for electives?

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #4427

#### What's this PR do?
Redesign of elective tags for courses.

#### How should this be manually tested?
Set up the program page to have electives. Check the program page in the course widget for new electives labels.

Screenshot 2019-10-28 at 5 32 15 PM

### CODE REVIEW

**Comment by tasawernawaz** [comment]
@annagav I am moving with forward.

**Comment by tasawernawaz** [comment]
@pdpinch could you please take a look at the screenshot. I have fixed the build.

**Comment by pdpinch** [comment]
Thanks Tasawer. I have a couple of questions/requests:

1. Can you make one of the course titles longer, so it wraps onto two lines?
2. I should have mentioned this to @abdulkdawson but I think the line spacing is a little too loose. In particular, the course availability should be closer to course titles. 
3. Does this affect the display on the dashboard and the learner record pages at all? Ideally, we'd like to keep the existing layout there, but change the colors to match this (can be a separate issue). 
4. Can you open an issue to update the seed data to include some electives?

**Comment by tasawernawaz** [comment]
> Can you make one of the course titles longer, so it wraps onto two lines? & line spacing is a little too loose. In particular, the course availability should be closer to course titles.

Screenshot 2019-10-29 at 5 26 34 PM

> Can you open an issue to update the seed data to include some electives?

Created https://github.com/mitodl/micromasters/issues/4438

> Does this affect the display on the dashboard and the learner record pages at all? Ideally, we'd like to keep the existing layout there, but change the colors to match this (can be a separate issue).

@annagav could you please answer this?

@pdpinch, @abdulkdawson please take a look at updated screenshot.

**Comment by tasawernawaz** [comment]
FYI @pdpinch Builds were failing intermittently due to a flaky test, I have opened up a new issue for it https://github.com/mitodl/micromasters/issues/4439.

**Comment by abdulkdawson** [comment]
@tasawernawaz This looks good to me. Thank you.

**Comment by pdpinch** [comment]
@abdulkdawson and I are good with the CSS changes -- I just need to know if there any side-effects (good or bad) on the dashboard and learner record.

**Comment by tasawernawaz** [comment]
@pdpinch I chatted yesterday with @annagav and she was pretty sure that we haven't done anything related to dashboard or learner's record. I tried to get screenshots by on my local machine I am having some configurations issue. Can we approve this so that we can merge this, we can confirm on RC once it is merged.

**Pull request merged**
