### PR TITLE
Implemented new design for the profile progress widget

### LINKED ISSUE #820: Update profile progress widget to latest design
as seen here: https://projects.invisionapp.com/share/9B804AMXA#/screens/178066345

pulled out of #769

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

this closes #820 

#### What's this PR do?

This implements the latest design for the profile progress `<svg>` thingy. Pretty much just changing colors and adding check-marks.

#### How should this be manually tested?

Make sure it looks like the mockup! See the issue.

### CODE REVIEW

**Comment by pdpinch** [comment]
Screenshot?

**Comment by aliceriot** [comment]
widget

**Comment by gsidebo** [comment]
code looks good, but it looks like the white checkmark isn't showing up in safari? 

ss 2016-08-19 at 15 13 46

**Comment by aliceriot** [comment]
oh dear

**Comment by aliceriot** [comment]
looks like IE support isn't there either probably: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject#Browser_compatibility

**Comment by aliceriot** [comment]
(the checkmark is inside of a `foreignObject` tag)

**Comment by aliceriot** [comment]
whew that was weird! a chrome extension was replacing the unicode character so I was getting some strange behavior.

should be sorted now.

**Comment by gsidebo** [comment]
@aliceriot is this ready for review again, or are we still in unicode hell?

**Comment by aliceriot** [comment]
I haven't come up with a satisfactory solution yet, I'll ping you when I get something working!

**Comment by aliceriot** [comment]
@gsidebo I downloaded the SVG for the material-icons checkbox from here: https://design.google.com/icons/#ic_check and then ended up just inlining it. I tried to get the svg `<use>` tag to work but had issues with it.

**Comment by noisecapella** [comment]
Did you try [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject)?

**Comment by noisecapella** [comment]
Nevermind, should read up a few more comments next time

**Comment by aliceriot** [comment]
haha, yeah that was the first attempt :P

**Comment by aliceriot** [comment]
then Mac OS unicode support was problematic

**Comment by gsidebo** [comment]
👍  🔥 🔥 🔥 🔥 🔥

**Pull request merged**
