### PR TITLE
update docker to use stretch

### LINKED ISSUE #4293: update docker to Stretch Debian
Travis can't run with the current version of Debian we specify.

The PR to fix this should be similar to mitodl/mitxpro#92

See the related issue #4286 and #4293

### PR DESCRIPTION
**Pull request by tasawernawaz**
#### What are the relevant tickets?
Fixes #4293 

**What's this PR do?**

- Bumps docker to use stretch
- Upgrade python to 3.6.8
- Update python dependencies to fix tests.
- Upgrade `yarn` and `node`
- Upgrade images for selenium tests
- Fix formatting issues with updated `prettier`

**How should this be manually tested?**

- Travis should pass,
- docker-compose build web and docker-compose up app should still work
- App should work.

### CODE REVIEW

**Comment by tasawernawaz** [comment]
@mbertrand I am getting following error on travis and local
```
yarn install v1.0.2
[1/5] Validating package.json...
error micromasters@0.0.0: The engine "node" is incompatible with this module. Expected version "10.15.1".
error micromasters@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.13.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
After some research I got couple of suggestions 

- Use `npm`
- Use `docker-compose run watch yarn --ignore-engines`

Both worked on my local machine. Could you please help on this.

**Comment by mbertrand** [comment]
The docker images on dockerhub needed updating via `travis/update-docker-hub.sh`.  I ran that, and changed the following lines on my branch:

`Dockerfile-travis-web`:
```
FROM mitodl/micromasters_web_travis_c815e5
```

`Dockerfile-travis-watch`:
```
FROM mitodl/micromasters_watch_travis_c815e5
```

But there are lots of new test errors (lint, flow) that need to be fixed.  I get most of those errors locally too (`docker-compose run watch npm run-script flow`)

**Comment by tasawernawaz** [comment]
@mbertrand thanks for help, I will move forward with fixing those errors.

**Comment by tasawernawaz** [comment]
@mbertrand I am seeing following error while running `flow`
```
static/js/components/email/EmailCompositionDialog.js:5
  5: import { Editor } from "react-draft-wysiwyg"
                            ^^^^^^^^^^^^^^^^^^^^^ react-draft-wysiwyg. Required module not found
```

I have confirmed that it is installed in listed in packges.json `"react-draft-wysiwyg": "^1.13.2"` (I have tried removing it and install latest version)

**Comment by tasawernawaz** [comment]
@gsidebo I am getting this error `Exception: The test suite is attempting to use the database 'postgres'.The test database should have a name that begins with 'test_'. Exiting...` while running selenium tests, which is raised from https://github.com/mitodl/micromasters/blob/master/selenium_tests/util.py#L228-L232. I did not understand the issue or why we have this check, could you please take a loot at it ?

**Comment by tasawernawaz** [comment]
@pdpinch This PR includes much larger change set then we expected initially. It requires extensive testing of the app alongside the code review.

@gsidebo @rhysyngsun @aliceriot Looking forward for your review.

**Comment by aliceriot** [comment]
I have tested the profile functions and things seem to be working alright there, no issues with adding information to the profile or anything like that. I'm not seeing any results for the discussions frontpage widget, but that seems to be broken on master as well (I may have something misconfigured, I'm taking a look at our documentation for mm <-> discussions comunication now).

**Comment by rhysyngsun** [comment]
@tasawernawaz after testing, it looking like gpg is pretty broken at least under this container version, talked with @pdpinch and @mitodl/devops and we've decided we're going to swap out the encryption algorithm for a better one in this PR since currently it just quietly writes out empty files.

I'll work on that the rest of today and hopefully have a commit to contribute that to this PR soon.

**Comment by tasawernawaz** [comment]
@rhysyngsun thank you. Looking forward to it.

**Comment by aliceriot** [comment]
nvm, discussions <-> micromasters frontpage stuff seems ok

**Comment by rhysyngsun** [comment]
To test the encyption changes:

Run `docker-compose build` to get the latest changes

Run `./manage.py create_nacl_keypair`, record the public and private somewhere.

In your `.env`, set `EXAM_AUDIT_NACL_PUBLIC_KEY` to your public key, then start a new shell and run this script:

```python
from exams.pearson.audit import ExamDataAuditor
from nacl.public import PrivateKey, SealedBox
from nacl.encoding import Base64Encoder
from django.test import override_settings

auditor = ExamDataAuditor()

with override_settings(EXAMS_AUDIT_ENABLED=True):
    auditor.audit_request_file("<FILENAME>")

b = auditor.store.get_bucket()
k = b.get_key("exam_audits/request/<FILENAME>.nacl")
assert k.exists()

with open('/src/<FILENAME>.nacl', 'wb') as f:
    k.get_contents_to_file(f)

pk = PrivateKey("<base64 private key>", encoding=Base64Encoder)
sb = SealedBox(pk)

with open('/src/<FILENAME>.nacl', 'rb') as f:
    print(sb.decrypt(f.read()))
```

The printed contents should match your original document and the `<FILENAME>.nacl` file contents should be encrypted.

**Comment by gsidebo** [comment]
@tasawernawaz I think this might have had something to do with a pytest fixture mirroring the name of a fixture provided by `pytest-django`. Something may have changed in the way pytest handles that scenario. When I changed the fixture name, I could run the suite without the manual test database name setting. You can give it a try as well. You may have to remove the `--reuse-db` parameter in `pytest.ini` as indicated in the README.

**Comment by tasawernawaz** [comment]
@gsidebo @aliceriot @rhysyngsun do you guys think we can merge this ?

**Comment by tasawernawaz** [comment]
@pdpinch My bad :( In excitement, I have merged it without squash. :(

**Pull request merged**
