### PR TITLE
Switch to Django JSONField

### LINKED ISSUE #1095: Switch to Django JSONField
Currently we're using the field with the same name from the `jsonfield` package. Switching would make it easier to query within the JSON

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1095 

#### What's this PR do?
Switches to Django's JSONField which would allow people to query the receipt data more flexibly

#### How should this be manually tested?
Everything should still work. These migrations should be non-destructive

### CODE REVIEW

**Comment by aliceriot** [comment]
migrated, nothing blew up. is that all I need to test?

**Comment by noisecapella** [comment]
If there was any data in any of the fields before, make sure that the data still exists afterwards

**Comment by aliceriot** [comment]
I don't think I had data in any of those fields, unfortunately

**Comment by noisecapella** [comment]
Try reversing the migration then creating a `Receipt` object with something in the `data` field

**Comment by aliceriot** [comment]
yup, it worked!

**Comment by aliceriot** [comment]
(merge conflict tho)

**Pull request merged**
