### PR TITLE
Upgrade Django and Wagtail

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/micromasters/issues/4150

#### What's this PR do?
- it upgrades django so that we can assign user permission and admin models.

#### How should this be manually tested?
- [x] Run all tests
- [x] Check student views of MM
- [x] check staff views of MM
- [x] test cms and upload pics/docs

@pdpinch

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
blocked on https://github.com/mitodl/edx-api-client/pull/46 release

**Comment by pdpinch** [comment]
@amir-qayyum-khan edx-api-client has been updated

**Comment by amir-qayyum-khan** [comment]
@pdpinch it is ready for review. Successfully tests django 2.1.2 and wagtail 2.3

**Comment by pdpinch** [comment]
Are there any migrations?

**Comment by amir-qayyum-khan** [comment]
yes @pdpinch need. You need to run docker-compose run web ./manage.py migrate

**Comment by annagav** [comment]
@amir-qayyum-khan, I am getting this error when try to login as different user through the admin
screen shot 2018-11-07 at 11 47 52 am

**Pull request merged**
