### PR TITLE
Modified FAQ field to have rich text

### LINKED ISSUE #603: Allow HTML in FAQ answers, in program page
Some of the FAQ answers need HTML, especially links.

### PR DESCRIPTION
**Pull request by giocalitri**
#### What are the relevant tickets?
closes #603 

#### What's this PR do?
Allows HTML in the FAQ answers`

#### Where should the reviewer start?
`cms/models.py`

#### How should this be manually tested?
Just test you can add a link in the FAQ answers

#### Screenshots (if appropriate)
screen shot 2016-06-29 at 12 14 21 pm

### CODE REVIEW

**Comment by gsidebo** [comment]
are these supposed to render as HTML as well? 

**edit screen**
ss 2016-06-30 at 17 31 19

**preview**
ss 2016-06-30 at 17 30 54

**Comment by noisecapella** [comment]
Yes, I think he needs to add `|richtext` to the faq fields in the template to convert from HTML

**Comment by giocalitri** [comment]
fixed

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
