### PR TITLE
Release 0.17.0

### PR DESCRIPTION
**Pull request by annagav**
Release 0.17.0

## mirfark
  - [x] adds has_delete_permission to financial aid django admin model (#1326) ([411528a2](../commit/411528a205c7fc7d7040dac1e63304bdc032388e))
  - [x] fix the failing currency exchange rate command test (#1321) ([9a711677](../commit/9a71167754a2796c750d8a44357ce6ff4d04a14f))

## annagav
  - [x] Limit HomePage to have only PrgramPage as a child page ([f87b1668](../commit/f87b1668cbef4f05054781d660f682931d933091))
  - [x] Add ga tracking to program pages ([6091e248](../commit/6091e24835e350eec6336cf3da26a5a1446ed5c7))
  - [x] Upgrade wagtail to 1.6.3 ([3031c3fb](../commit/3031c3fbbb49ab5db11732ef5afe9bf4e7a48301))
  - [x] Created FaqsPage ([51f450dc](../commit/51f450dc05b0ab9003c8344e4b7f9b5811effe8b))

## Robert W House
  - [x] Fixes hero image to not scroll on home page (#1348) ([92fa3c4f](../commit/92fa3c4f5acf453b875648441e3378b3671f9dd6))
  - [x] Adds a gradient overlay on the faculty carousel (#1319) ([8c317752](../commit/8c317752c109555993efdde83c67c3087dae92ee))

## Tobias Macey
  - [x] Added sentry to app (#1306) ([0cabdf1b](../commit/0cabdf1b1a2b13b0d36f59916fc77aaf2a233366))

## George Schneeloch
  - [x] Fixed console warning (#1345) ([e962d247](../commit/e962d247abd7aeda49100ec14c54d5184d781be6))
  - [x] Fixed image size for faculty carousel (#1300) ([deeecc32](../commit/deeecc3236640d18f8d8599f60764bd0ae654fc1))
  - [x] Replaced hard coded support email (#1330) ([46317505](../commit/46317505bab5e25c1bef06bf5196cb44562ff34d))
  - [x] Implemented enroll links (#1289) ([405acda3](../commit/405acda3d1ecc1fbd8347e1e0317068d7f8022d5))
  - [x] Added logging for IsSignedByCyberSource (#1241) ([b1d6d6d0](../commit/b1d6d6d02431bdd6b9bbe87f22070116fd996a49))
  - [x] Implemented passed course display (#1268) ([626a41a0](../commit/626a41a0c8a7a551204ba5b546a27fe3ee7ff800))
  - [x] Switched to hosted jquery and bootstrap (#1274) ([d1f489da](../commit/d1f489da4f1a75bd152dbee4b75fd65053e992b4))

## Alice Pote
  - [x] Fixed user menu wideness ([aecdfb40](../commit/aecdfb4016a5a250df39a6ae712bc2a6e43709b5))
  - [x] Hid program selector on certain pages ([87fc3c00](../commit/87fc3c0018bf1f9561ed496d1f646a6f4b12ab4b))
  - [x] Updated financial aid document address slightly ([71ed50d4](../commit/71ed50d4e307c87245585409f165d198b2247d2a))
  - [x] Made photo uploader only accept image files ([c329e38c](../commit/c329e38c94759f1833a7b1c45ef1b60a9120b854))
  - [x] Switched profile button order ([e2e2f9f1](../commit/e2e2f9f13ad5e7569ea281c548560cc359cf2904))
  - [x] Fixed income verification required display ([0fc88ae9](../commit/0fc88ae9e82fa17f4f11ed064accaaa33bf1063b))
  - [x] Added default currency (based on country) to calculator ([ca64a000](../commit/ca64a0005c01f62fc3bf9b933b6be96a28be415e))

## Alvin Siu
  - [x] Added test cases (#1335) ([b2969afc](../commit/b2969afc245d61ebb69b52c696c37680e214c7bd))
  - [x] Fixed bug in financial aid request for determining tier (#1314) ([6af03a6b](../commit/6af03a6b49a4336de2c13758d1c6f4de8668f21d))
  - [x] Expand country code to country name on review page (#1297) ([f91e4d6b](../commit/f91e4d6b3d53afa2b6dc76e5ade7993a9bb39115))
  - [x] Moved &quot;Show:&quot; outside the dropdown on financial aid review page label and made table responsive (#1284) ([f97d0ffd](../commit/f97d0ffd988e1f8c81fa83c3a41f0ec7c2ab6909))
  - [x] Fix for 404 page when passed exception kwarg (#1277) ([466301ee](../commit/466301ee3a0eb68865965cb8f959e0d207913d96))

## Gavin Sidebottom
  - [x] Added currently-enrolled dashboard course states ([dffc6b32](../commit/dffc6b327e10a4248c7974fa6dcaa1bb63b2d6f8))
  - [x] Enabled &#39;View on edX&#39; link on dashboard ([7c1313f0](../commit/7c1313f0e108eeaeb184001469d04316c2f7804a))

## Miriam Farkas
  - [x] add dollar sign to email body text for financial aid ([76853936](../commit/76853936e25f3baba42b62709541ae064c56148f))
  - [x] changes /users/ to /learner/ ([57267770](../commit/5726777027cf529a108218c238e9bb7739aa71a3))
  - [x] adds error handling for syncing exchange rates with API ([4d543b67](../commit/4d543b67cda3450797cc8024f021352e957149e4))
  - [x] changed names and description ([ff25def6](../commit/ff25def638896c57af8817160edff864a8ed26b8))
  - [x] adding test coverage for currency exchange rate management command ([ca3b1ba8](../commit/ca3b1ba8e91d6b7ab20c3275ac8dd1bd031d27f5))
  - [x] management command for generating exchange rate objects ([5c7c898f](../commit/5c7c898f4da9d4eb1c2cd33bfbf2e065f309390b))

## Amir Qayyum Khan
  - [ ] Removed zendesk widget from homepage ([67b3e9ba](../commit/67b3e9ba78e443e0835b81a8c06c29a9f57c3afd))
  - [x] Remove fields from homepage object and CMS (#1165) ([326a85c3](../commit/326a85c36883fc301b3b2fa275b5284e9124d252))

## Giovanni Di Milia
  - [x] Limited the course grade cache refresh to the enrolled runs ([364bed3a](../commit/364bed3a357d9155594a654aa33db36890ee645a))
  - [x] Added support for token authentication ([5deed589](../commit/5deed5897ad7b3eabbc953b1af046df7c456d816))

### CODE REVIEW

**Comment by aliceriot** [comment]
done

**Comment by pdpinch** [comment]
@amir-qayyum-khan's commit has a bug. I'm looking into it. 

> Removed zendesk widget from homepage (67b3e9ba)

**Comment by noisecapella** [comment]
done

**Comment by giocalitri** [comment]
done

**Comment by amir-qayyum-khan** [comment]
@pdpinch 

screen shot 2016-10-13 at 12 28 25 pm

#### Page is not able to open javascript file, giving 404 error
https://micromasters-rc.herokuapp.com/static/bundles/js/zendesk_widget.js

**Comment by noisecapella** [comment]
done

**Pull request merged**
