### PR TITLE
update readme with details on how to adjust exam grades

### PR DESCRIPTION
**Pull request by pdpinch**
#### What are the relevant tickets?

#4036

#### What's this PR do?

adds some more detail to the shell commands for adjusting the proctored exam grades.

#### How should this be manually tested?

You can test this on CI or RC with a one-line csv file

#### Where should the reviewer start?

I'd just like a second opinion on the copy-and-paste method. Is there a better way to do this?

### CODE REVIEW

**Comment by pdpinch** [comment]
@shaidar or @annagav any advice on this?

**Comment by annagav** [comment]
When I adjusted the exam grades in past I had to make few extra steps to make sure that the file I copied to the server is identical to the original one. (Just copy/pasting the file was not resulting in a file identical to the original).
Locally:
- base64 -i original_file.csv -b 70
On heroku shell:
- cat > temp.txt
- base64 -d temp.txt > updated_grades.csv
Use `md5sum` to verify that the file is identical to the original file.

**Comment by pdpinch** [comment]
In what way was the file incorrect?

**Comment by pdpinch** [comment]
@annagav can you answer my question above? I don't understand what the problem was that you saw earlier.

**Comment by annagav** [comment]
I was not able to copy (just with copy-paste) the file so that the resulting file on the server was the same as the provided file. But if you didn't run into this issue, then that's ok.

**Comment by pdpinch** [comment]
FYI @annagav I added steps about checking the md5sum. I'm going to go ahead and merge.

**Pull request merged**
