### PR TITLE
Release 0.16.0

### PR DESCRIPTION
**Pull request by annagav**
## Alvin Siu
  - [x] Updated financial aid review page frontend (#1161) ([b175542a](../commit/b175542a34b761bfd3f6cfc5b0220bf04defaced))
  - [x] Added ImproperlyConfigured (#1256) ([8a4af499](../commit/8a4af499103f937d3e4510b2603abed85373cf94))
  - [x] Fixed course price API output (#1255) ([ae220ddb](../commit/ae220ddb400f756817f0b0f084fcce5e38fb9c9f))
  - [x] Removed rejected status (#1253) ([177e49d5](../commit/177e49d5b70053a605ebaabe50a6b00911fea23d))

## mirfark
  - [x] Zagaran/financialaidadminlogging (#1263) ([38f13a5a](../commit/38f13a5a0ebc17a9c0df1e1c935ef0b0f998b22b))
  - [x] makes fields read_only in django admin for financialaidaudit objects (#1258) ([457722e7](../commit/457722e70afc88a783073d8f3dba19e30afc6d9b))
  - [x] fixes FinancialAidAudit JSONfields (#1244) ([4a890242](../commit/4a890242bb65bf02fbe5358b6ea7f02bdd872c25))

## George Schneeloch
  - [x] Fetch course prices and dashboard after every relevant change on the server (#1271) ([9e4c9a3b](../commit/9e4c9a3be52b2f1ab5ca5bc71646f70662d2a44d))
  - [x] Implemented document sent date (#1207) ([fa372ed4](../commit/fa372ed4a725efb58bc4512978298cbedea29bbb))
  - [x] Add back terms of service link in dialog, and change Log in link to act the same as signup (#1182) ([4ba86765](../commit/4ba86765abac424da5fc091a1b20f40f7586c6b4))

## Robert W House
  - [x] Home Page, Program page and App with MIT Brand colors (#1246) ([fedf6dee](../commit/fedf6dee0c4a98349cbcf44e17592d53639d02e1))

## Giovanni Di Milia
  - [x] Added Rest API to audit enroll a user in a course ([2f7b5a02](../commit/2f7b5a02d735403806adb0b04d2d8919be4d36df))
  - [x] Added log.error for every ImproperlyConfigured exception raised ([aa2afb28](../commit/aa2afb28972005fa6fd7d1ac338f16cf29b936e7))

## Amir Qayyum Khan
  - [x] Added ZenDesk help button on MM (#1211) ([a45821f7](../commit/a45821f7d7c1706b00d141455e87fe21d1e87d6e))
  - [x] Fixed Style of mailchimp form (#1166) ([cd4b2d6a](../commit/cd4b2d6a81e1e117bcffa3694471c43b7c4fc185))
  - [x] Updated my dashboard link (#1233) ([86e9e87d](../commit/86e9e87d6f77475588c819c7484ba6959927f00c))

## Alice Pote
  - [x] Added confirmation dialog for skipping financial aid ([120aab65](../commit/120aab650712cb696c8d0e709e04f7e42e769759))
  - [x] Added &#39;skip financial aid&#39; feature ([fa925b4b](../commit/fa925b4bd75b904397a5bca7630bb8352e74fc48))

### CODE REVIEW

**Comment by aliceriot** [comment]
done!

**Comment by annagav** [comment]
@giocalitri, @amir-qayyum-khan, @noisecapella, @mirfark, @alvinsiu Please verify you commits!
https://micromasters-rc.herokuapp.com/

**Comment by giocalitri** [comment]
done

**Comment by noisecapella** [comment]
done

**Comment by pdpinch** [comment]
All done!

I verified Amir's commits.

**Pull request merged**
