### PR TITLE
Release 0.19.0

### PR DESCRIPTION
**Pull request by annagav**
## George Schneeloch
  - [x] Fixed detect_missing_migrations.sh (#1583) ([7e7351f2](../commit/7e7351f2cc27f0ea135b499ba7f6f0a0394c8124))
  - [x] Refactor test code (#1572) ([5b46ae0e](../commit/5b46ae0ed0e7f13bf5b6e1faf1efe4e9c63671ed))
  - [x] Moved ddt into test_requirements.txt (#1576) ([edb19bbc](../commit/edb19bbc520c2dd8d579f3fc6dcb3b73426e1b16))
  - [x] Added programpage_url to /api/v0/programs/ (#1571) ([44028e08](../commit/44028e081eb5d717ee516978335fe1acf6922210))
  - [x] Remove detect_missing_migrations.sh from build temporarily (#1581) ([3cbc77cc](../commit/3cbc77cc3359e925e41789f3273e5a16d79dbac7))
  - [x] Protected detect_missing_migrations.sh against hanging for console input (#1573) ([54bdc1b6](../commit/54bdc1b6f4238e4733e9254f7c88392d95e37154))
  - [x] Removed course run view (#1570) ([6153382b](../commit/6153382be22911beb9c16c8fb1e40e7601cf1df3))
  - [x] Prevented an enrollment failure from failing the order (#1552) ([82ca51b3](../commit/82ca51b3307eeabcd4a90166310267602435982a))
  - [x] Use bulk indexing for seed_db (#1544) ([f0adcce1](../commit/f0adcce16ed88175e88bba0168be2461ed53cb99))
  - [x] Refactored course tests (#1492) ([0c3a3c18](../commit/0c3a3c182462a2042cc815869148923fe3b80c95))
  - [x] Logged exception being handled in custom_exception_handler (#1532) ([878c895b](../commit/878c895b78afa56e35c1f6f78c5ab3f132bf4fab))
  - [x] Added check for missing migrations (#1491) ([9660156a](../commit/9660156ab33650d5ef47e4f5ce11773d247f76af))
  - [x] Protected audit tables (#1488) ([d4ab0c29](../commit/d4ab0c29a663897577d0f0555e58f0ba19bd548d))
  - [x] Added ability to mark orders as refunded (#1483) ([7fe742f2](../commit/7fe742f257b3a2ab42242c0043534b138eff167b))
  - [x] Removed filler-text tooltip (#1484) ([05388ea1](../commit/05388ea13f90a31c69bff8e8537734a15b8050d5))
  - [x] Added audit table for Order, Line (#1456) ([af964aca](../commit/af964aca2096410c9a7db199fdaa3d04df79400a))
  - [x] Fixed IE11 support for image upload (#1402) ([7e114322](../commit/7e1143221175c62600e3558fd35327d966dacdcf))
  - [x] Added serialize_model, replaced to_dict (#1447) ([95eeddde](../commit/95eeddded726febfa2df25c382f53120bd25fc4b))
  - [x] Make program selector use full dialog width (#1388) ([5e67a903](../commit/5e67a903fd4ebbaa55dd2dc15ca32df546f911e6))
  - [x] Added line items to cybersource payload (#1438) ([45ffe46f](../commit/45ffe46f3ab2450581478691168a06a9bfaa24e0))
  - [x] Added tracking_id to silence warnings (#1403) ([52b3cdb7](../commit/52b3cdb721a765c99887b97a15ac92ab9ba829a0))
  - [x] Added webpack_public_path (#1404) ([72b3dc76](../commit/72b3dc76f33faae07199219cdb34aee12cda547b))
  - [x] Fixed console warning for faculty carousel (#1406) ([aea20586](../commit/aea20586c31ee8072fdc72063ba0cb1b42553668))
  - [x] Sorted programs in id order (#1387) ([8d780c65](../commit/8d780c65beb316fecfebccb0c45253d691c35515))

## Alice Pote
  - [x] Fixed input bug with the FinancialAidCalculator ([2bd37d32](../commit/2bd37d32e8aa70fb701ab53c750f94ed362cf980))
  - [x] Reorganized JS code ([babeb3a3](../commit/babeb3a301d54afc62cb9a23f58ab10d18634572))
  - [x] Refactored date validation ([c09aec73](../commit/c09aec738f43deb815f507f3e0df603ffeebc290))
  - [x] Implemented mobile sidenav ([35f3364d](../commit/35f3364d2c0f03c4bb695ff853e4c6f94a883d40))
  - [x] Added complete financial aid instructions ([ef20d269](../commit/ef20d2691a0d4eca6f4d7e26b2a61d6c14f9af1c))
  - [x] Added flow to travis ([3a3b6b17](../commit/3a3b6b17c92cd8b62bc3694a85afc97cf4ed02e2))
  - [x] Fixed error in year validation logic ([e69675e2](../commit/e69675e22810095a70fa4d0f3bb3bdc2df5831b9))
  - [x] Changed copy for financial aid stuff ([f583113f](../commit/f583113ff6c186fa56fa42a98b02c45011ffad6a))

## Peter Pinch
  - [x] pinned elasticsearch in docker to 2.4.1 (#1580) ([49a3e7d5](../commit/49a3e7d5f0612612d3037c8357fc52e15388b9d8))

## Amir Qayyum Khan
  - [x] Omitted program staff from search results (#1502) ([727d9140](../commit/727d9140cbabb37b78d3af32bf8a0a5b41ed01aa))
  - [x] Footer consistency all over app (#1503) ([bcbbffc4](../commit/bcbbffc4e99a7b4de69d24e2004d09e18089e21e))
  - [x] Fixed size of image upload container (#1471) ([87eb6313](../commit/87eb6313dc791d6d20aa1ffbe0e6c797312d5163))
  - [x] Removed dashboard links from profile page header (#1505) ([9df6a503](../commit/9df6a5031456db1056840fac29381439eefc1930))
  - [x] update style: removed top padding from searched page (#1504) ([4b05ac1d](../commit/4b05ac1deb13d26a42543dc05c16120117b30fed))
  - [x] Removed mm id from dashboard (#1493) ([6def7624](../commit/6def76243130c7c85004c979087e484a453c0a1b))
  - [x] Fixed preferred Language options (#1475) ([74cced2f](../commit/74cced2f8d3a535f136b15f8b0e1e956f98c41b2))
  - [x] hid facets when they have no hits (#1407) ([26ac4b03](../commit/26ac4b038a1fcfa704d5c30304ebb6f758440df8))

## Robert W House
  - [x] Copy changes per maria&#39;s request (#1557) ([3744ee4a](../commit/3744ee4a75c6d8f0ca89d019bb6b7db4dd2636fb))
  - [x] fixed layout bug with footer Give to MIT buttons (#1554) ([8a74f535](../commit/8a74f535cfcfdede9d1bc9b7f5639bbb1e981c07))
  - [x] Refactored buttons html and css and other style changes (#1446) ([0c7e5086](../commit/0c7e508660bdc64d3185cc153297316cc181be89))
  - [x] line-height fix for Course list on program page (#1480) ([4aab2d48](../commit/4aab2d482eb20d4ffcb4815eaa068c1d6113eff9))
  - [x] Partial Fix for Responsive Styles in Dashboard (#1386) ([fb9ef798](../commit/fb9ef79828f15c3eb83e9cc0eeffae847ead48bd))

## annagav
  - [x] Custom Tabs for ProgramPage ([037cc0da](../commit/037cc0dabc5ec69ec0ae96b04c5b5d09bfc84aa2))
  - [x] Customize More Info card ([4e535eec](../commit/4e535eec3a5b4008081e49df12b6df6f4bdbf873))
  - [x] Show only published children pages on the ProgramPage ([336e554f](../commit/336e554f4dcfeb896c45790058732dd1ecd640bb))
  - [x] Add Smartlook tracking ([110b0cb7](../commit/110b0cb72dad09716cf4e80d227feba99913f5aa))
  - [x] Reverting cms migrations ([219cdc09](../commit/219cdc0907a7e65fe5c4b7cba3e7d8933f5830f7))
  - [x] Make footer mit logo a link ([defa1ac0](../commit/defa1ac068e00b26778039cc6c1879e4202671cb))
  - [x] Make position_in_program required ([63af1910](../commit/63af191018640dbe5478d8d824365581411caae6))
  - [x] Added FAQs accordion ([f581f9d0](../commit/f581f9d01d1932c4edff8fc3910194b33dc59468))

## Gavin Sidebottom
  - [x] Fixed course description JS bug ([951d2ed0](../commit/951d2ed09db2e2cfb164613108640ba144f832f4))
  - [ ] Fixed course run edx key save issue ([5a5c5990](../commit/5a5c5990fd176f0bc4cac547db1d0e82feee8798))
  - [x] Added unique constraint to CourseRun edx_course_key ([45a24e7a](../commit/45a24e7ae2c405498f421335b98d6d13ec41587b))
  - [x] Added past course run UI to dashboard ([d7f095e9](../commit/d7f095e9020dd97fd5ba07d637001b5893907c61))

## David Baumgold
  - [x] Add alt text to logos (#1553) ([8e6d0ad4](../commit/8e6d0ad43369e0105b9a2fb2de40513f8ed4baa8))
  - [x] Clarify title for average grade filter (#1539) ([7be4efe5](../commit/7be4efe547ca9685ec93128f416c18c3531579e4))
  - [x] Note Flow incompatibility within Docker (#1469) ([076e5980](../commit/076e5980e4e3581e94da725add87036204ccefc6))
  - [x] Improve profile factories using Faker library (#1476) ([bab397e4](../commit/bab397e4793fdc3167d711fbd3c998d5c3267f08))
  - [x] Add app config for seed_data app (#1473) ([5e616b3a](../commit/5e616b3a1c064f5f44fb2db67daf533b1e0852d7))
  - [x] Seed data app (#1463) ([160b4268](../commit/160b42686b9d9c3cbeb6cdd9b2667ffd695dc12f))
  - [x] Fix a bug in course enrollment text (#1416) ([706d42f7](../commit/706d42f78ecc8866c4c7f252ee37bffb1a32ad0f))
  - [x] Remove deprecated TEMPLATE_CONTEXT_PROCESSORS setting (#1236) ([4d449b86](../commit/4d449b862b6757d877c8cbbca606e6accce202b7))
  - [x] Course description popover (#1392) ([2e31567b](../commit/2e31567b8aecbcf561678e1723d2783096481cef))

## Anna Gavrilman
  - [x] Remove subtype for ProgramPage (#1535) ([43ecb159](../commit/43ecb159aaaec0767803342aebc3f06f0b727b35))
  - [x] Add/remove custom tabs on program page (#1436) ([21473787](../commit/21473787e171f94d9830074f47e91c8918e16d45))

## Alvin Siu
  - [x] Changed discount_amount to have a min of 1 (so we never have multiple… (#1467) ([ab92d382](../commit/ab92d382f78de155852b5e1fe324e1d2f208da21))
  - [x] Modified mail.views responses to catch 401 status codes from mailgun … (#1376) ([dc593d31](../commit/dc593d31603dca379fa6abe6f12047bfc4c123d1))

## Tobias Macey
  - [x] Updated the app.json to include required env vars (#1464) ([0bf1698d](../commit/0bf1698dfafe2925864bf642f25c6aa23696382d))
  - [x] Added persistent connection settings for DB ([2f4d177d](../commit/2f4d177d0a2c00538868a3cbb58cfb6a1d3591a3))

## Giovanni Di Milia
  - [x] Added nplusone library for query profiling in app DEBUG mode ([2f374dd1](../commit/2f374dd1850d94264ae55b141ee28b7c56f40743))
  - [x] Program enrollment does not return error if already exists ([96250536](../commit/96250536d6f40dee85a7fcec8909561a108afbb4))
  - [x] Changed logic to assign the student ID ([7c0da8e2](../commit/7c0da8e253cb2253f29bdab640b8f57e36db83db))
  - [x] Fixed bug with current grade refresh and no enrollments ([14931e65](../commit/14931e65292baecb08e4d58e4c3395f282c7acc6))

## mirfark
  - [x] adds admin model for financialaidemailaudit objects (#1380) ([0deb955e](../commit/0deb955e26ab2957e83fb84492ba75e581855261))

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
Done with verification of my commits.

**Comment by aliceriot** [comment]
done!

**Comment by noisecapella** [comment]
done

**Comment by annagav** [comment]
I updated the release with the latest new commits! Please check off your new commits!

**Comment by amir-qayyum-khan** [comment]
@annagav micromasters-rc.herokuapp.com seems not up to date with latest commits

**Comment by annagav** [comment]
@blarghmatey said to give some more time to build....

**Comment by pdpinch** [comment]
I checked off @mirfark's commit.

**Comment by pdpinch** [comment]
I checked off @alvinsiu's commits. One was for a test change, so I didn't check that. I checked the Mailgun exception for the other one.

**Comment by amir-qayyum-khan** [comment]
done

**Comment by annagav** [comment]
The release was updated with new commits! Please verify! @giocalitri , @gsidebo, @aliceriot, @noisecapella, @pdpinch

**Comment by pdpinch** [comment]
If the build ever finishes, then my box can be checked off -- because if it doesn't work, it will block the build.

**Comment by aliceriot** [comment]
The build is stalled or something, in heroku it just says 'Unable to display build output'

**Comment by noisecapella** [comment]
Yeah, I tried to restart it but I don't have permission. @blarghmatey needs to look at this

**Comment by pdpinch** [comment]
It looks like the build did finish (even if it required some intervention?), so I checked off my box.

**Comment by annagav** [comment]
@amir-qayyum-khan, @aliceriot, @gsidebo There are few more left!

**Comment by amir-qayyum-khan** [comment]
done

**Comment by aliceriot** [comment]
done!

**Pull request merged**
