### PR TITLE
Release 0.21.0

### PR DESCRIPTION
**Pull request by gsidebo**
## Gavin Sidebottom
  - [x] Made small optimization to user serialization for search results ([fcf535cc](../commit/fcf535ccfae886f56fa14506976d2c4ae4a0505d))
  - [x] Fixed course date issue in alter_data command ([80e6b5a1](../commit/80e6b5a1c852cbce0c7a4e786bdf6c56c6917f9d))

## Alice Pote
  - [x] Made sure we&#39;re root when doing pip install in travis-web container build ([27809d6c](../commit/27809d6c144a3237ec49aaf25c29cf7444ec34e7))
  - [x] Implemented inline validation ([d729f53c](../commit/d729f53c980af3baa6cbdd7caf050265d1a2f7a5))
  - [x] Made changes to speed up CI builds ([67d1cc82](../commit/67d1cc82c16e03d2ddcfd3c1e5ccf00a9ae54042))
  - [x] Added development to the industry vocabulary ([27d3b715](../commit/27d3b7157799aebb46d4841c54de60c2cfdefcb3))

## George Schneeloch
  - [x] Fixed pending JS tests (#1631) ([a3d7c287](../commit/a3d7c287f65cb5505e0fea0c6f6987d3e39323b1))
  - [x] Refactored Education frontend components (#1606) ([3f7154d4](../commit/3f7154d4035c48eac0c62bbedc2d72a88b3d007a))
  - [x] Split enrollments reducer into programs and courseEnrollments (#1586) ([19db3459](../commit/19db3459c719a561cc6b24da0ab70cc405b16f2f))

## Amir Qayyum Khan
  - [x] Fixed alignment of Current Residence on search page (#1607) ([bdbb6f1f](../commit/bdbb6f1fe3d4efd060a0cc22ffeb3eddcabc156b))
  - [x] Fixed header of search page (#1624) ([73875c88](../commit/73875c881a0f1bf082a3f2b71e7b7269ca08149a))
  - [x] Shown message when no search results (#1449) ([40e4dd42](../commit/40e4dd42786538feea714bd478aa23c8e0644682))
  - [x] Fixed View on edX url inside dashboard (#1591) ([ac0ffa43](../commit/ac0ffa4341ccf1925da121eadaa418cfa2c99f0f))

## David Baumgold
  - [x] Use DRF API correctly (#1625) ([4165c723](../commit/4165c7230282ba305cd22dfc2ed6aa517db38a0e))
  - [x] Replace `SETTINGS.username` with `SETTINGS.user.username` (#1615) ([56c3fbdd](../commit/56c3fbdd6e9cf13ace0e675aea3684e6ef3f4877))
  - [x] Zendesk prepopulate name/email (#1482) ([12006403](../commit/1200640308fc947dce31d0df65400d7afba6b413))

## Giovanni Di Milia
  - [x] Added indices for all dates in the CourseRun model ([f76273fa](../commit/f76273fa91b1ede31259d3bded3794e39ac0632c))
  - [x] Fixed bug with search visibility ([09ca02c3](../commit/09ca02c310c6f59c743b0e9e1771246607828eaf))
  - [x] Handling n+1 queries in dashboard ([2dc0dd8f](../commit/2dc0dd8fe2559998c127792434a3b43750842019))

## Peter Pinch
  - [x] addied cybersource settings to app.json (#1601) ([2c0dc55b](../commit/2c0dc55b4c1e5d2184a589b3c00de6f0365c8084))

## Robert W House
  - [x] Small change to width of modals on mobile (#1609) ([af67318a](../commit/af67318ad8bf1e136f6cb47e03b0bf73f12ed3f0))
  - [x] Small PR to make header say MITx MicroMasters (#1610) ([6c3dfb81](../commit/6c3dfb81772bd958b68636365a3a2c26a75c6585))

### CODE REVIEW

**Comment by giocalitri** [comment]
done

**Comment by pdpinch** [comment]
Thanks Gavin. There are some user-visible changes here that folks have been waiting for, so we should proceed with a release as soon as reasonably possible. 

I checked off my box.

**Comment by pdpinch** [comment]
@amir-qayyum-khan you're the last one

**Comment by amir-qayyum-khan** [comment]
@pdpinch @gsidebo behavior of https://github.com/mitodl/micromasters/commit/40e4dd42786538feea714bd478aa23c8e0644682 is not fine

- Enroll in multiple proframs.
- Make yourself staff in only one program.
- go to learners/ page.
 - change programs from nav bar towice

screen shot 2016-11-04 at 7 19 12 pm

screen shot 2016-11-04 at 7 19 20 pm

**Comment by gsidebo** [comment]
checking this out now

**Comment by gsidebo** [comment]
@amir-qayyum-khan it looks like there's some incorrect logic around displaying the "no results" message. here's a code snippet on the release-candidate branch:

```javascript
renderFacets: Function = (currentProgramEnrollment: ProgramEnrollment): React$Element<*> => {
    if (_.isNull(this.getResults())) {
      return (
        <Card className="fullwidth" shadow={1}>
          <div className="no-hits left-nav">
            {`There are no users in the ${currentProgramEnrollment.title} program.`}
          </div>
        </Card>
      );
    }
```

here's a screenshot of some `console.log` lines i put in to debug this:

ss 2016-11-04 at 11 28 40

`this.getResults()` is not returning `null`. it's returning an object with no hits. this should be logged as a new bug. @pdpinch i'm going create a new issue for this and go ahead with the release given the urgency

**Pull request merged**
