### PR TITLE
Updating logos and favicon

### PR DESCRIPTION
**Pull request by annagav**
### What are the relevant tickets?
Fix https://github.com/mitodl/hq/issues/3338

### Description (What does it do?)
Updating logos and favicon

### Screenshots (if appropriate):
Screenshot 2024-02-28 at 10 02 36 AM

Screenshot 2024-02-26 at 4 14 59 PM

Screenshot 2024-02-27 at 9 13 22 AM

### CODE REVIEW

**Comment by mbilalmughal** [comment]
@annagav LGTM 👍

**Review by shanbady — CHANGES_REQUESTED** [review]
there are a few references to logos that were deleted that i see:
- in cms/templates/cms/program_page.html i see a reference logo-mitxonline.png
- in ui/templates/background-images.css i see references to micromasters_logo_programs.svg and micromasters_logo_on_programs.svg

**Comment by annagav** [comment]
Now the program page has mitxonline logo:

Screenshot 2024-03-05 at 2 32 53 PM

**Review by shanbady — APPROVED** [review]

**Comment by shanbady** [comment]
LGTM

**Pull request merged**
