### PR TITLE
Make program selector use full dialog width

### LINKED ISSUE #1281: Dashboard: when enrolling in DEDP, the program title doesn't fit.
screen shot 2016-10-06 at 9 17 04 am

screen shot 2016-10-06 at 9 17 08 am

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1281

#### What's this PR do?
Makes the select take up the full width of the dialog
#### Screenshots (if appropriate)
screenshot from 2016-10-13 17-18-59

### CODE REVIEW

**Comment by noisecapella** [comment]
@roberthouse54 @pdpinch Is this a solution you had in mind, or should it have some other width?

**Comment by pdpinch** [comment]
this works for me

**Comment by roberthouse54** [comment]
It doesn't need to be full width, but it should be about 2x what it was previously. And if it extends past that width, it should truncate, or overflow hidden (not scroll).

**Comment by noisecapella** [comment]
Should be ready for review

**Comment by gsidebo** [comment]
i'll take over from here

**Pull request merged**
