### PR TITLE
Added program title to dashboard

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
- fixes https://github.com/mitodl/micromasters/issues/2517

#### What's this PR do?
- Adds program title to dashboard page.

#### How should this be manually tested?
- http://192.168.99.100:8079/dashboard

@pdpinch 

screen shot 2017-02-15 at 9 16 06 pm

### CODE REVIEW

**Comment by roberthouse54** [comment]
Amir, I'd like to request a few changes:

change the font weight to 400.
change to margin: 10px auto 29px;
change the element from h5 to h2, but with the same font size (20px)

**Comment by roberthouse54** [comment]
Also, is there any reason that you did not put the header inside the double-column element?

**Comment by amir-qayyum-khan** [comment]
@roberthouse54 `double-column` is a flex row.  if i add h2 there it takes it as column

**Comment by amir-qayyum-khan** [comment]
Done with changing style

**Comment by roberthouse54** [comment]
👍 Looks good.

**Pull request merged**
