### PR TITLE
Release 0.15.0

### PR DESCRIPTION
**Pull request by annagav**
## Tobias Macey
  - [x] Added configurable basicauth to uWSGI ([68e6c59c](../commit/68e6c59c79d8a133b8f89c9bd81b1f1bfd25b352))

## David Baumgold
  - [x] Improve social links with Google+ (#1208) ([e37794d8](../commit/e37794d862d64368c3592f4bdbb2f0585ff70fd4))
  - [x] Responsive program page (#1152) ([38df4ce7](../commit/38df4ce77bb8ae5c3f7ec8d63a623a22ca341ec4))
  - [x] More accessibility improvements (#1148) ([d26ab5ea](../commit/d26ab5ea382e2f18b5dbb16abb348d9fd8ce938b))
  - [x] Responsive home page (#1143) ([ca2ffe9d](../commit/ca2ffe9d262f25b6664f2624212f7972da82397f))
  - [x] Accessibility improvements (#1133) ([c78d4477](../commit/c78d447739002c39d7581995fbd9b7d9281b4177))
  - [x] Faculty carousel (#1079) ([b9b006e9](../commit/b9b006e916f4006f422bb1cc97f32c21a1d6d544))

## Gavin Sidebottom
  - [x] Added pre-enroll dashboard course states ([dbab3ab3](../commit/dbab3ab3738ca21b407a98b7c15cd2586db23132))
  - [x] Added course price API call to front end ([c3fb6789](../commit/c3fb67895d9970cfa530814de197f034645e03c5))
  - [x] Changed names and values for course statuses ([03483587](../commit/0348358700960209eee5a1d6112cf8a589f6dca1))

## annagav
  - [x] Add course description and page link (#1209) ([994e3e4e](../commit/994e3e4e8d8e0a785ccf2f6eb68146a83de1e0d6))
  - [x] Set unique URL for tabs in program page ([ee8a89cd](../commit/ee8a89cd04276e36a3d41043028edbfa6470cf88))
  - [x] Add social sharing buttons to public pages ([cd2564be](../commit/cd2564be62728c2db0928ff82f7a49b72a20e418))
  - [x] Leave Courses on FAQs page ([63843d83](../commit/63843d8347215bdfa84292c8731dc3be73f43068))
  - [x] Update homepage text ([8f9cae28](../commit/8f9cae28e638e80830ddf20ab41d1b18788694ad))
  - [x] Add social meta tags ([7e7b6073](../commit/7e7b60735466ebbfdca5a79e76b9aec64e029da1))
  - [x] Add description, keywords meta tags, title text ([a881c233](../commit/a881c23383434ae31f94c992c79b5de0b28bfe19))
  - [x] Display courses with enrollment status on ProgramPage ([276e73e2](../commit/276e73e2ccc1dd6625153e75838bd8236ee9d266))

## Giovanni Di Milia
  - [x] Added batch refresh of current grades ([8329f6e7](../commit/8329f6e79488c1380f65c51e52f4817857f0a949))
  - [x] Exposed the financial aid obj ID in dashboard API ([fd1ecddb](../commit/fd1ecddbf4cd493563106865b8d8608e6457ee8a))
  - [x] Exposed financial aid documents flag on MMTrack ([c3127298](../commit/c31272980749ae42c4ea99897c06802150a7a8fa))
  - [x] Custom exception handler ([d61bffef](../commit/d61bffef6112e1e70a2167e5b169cde6e96793c1))
  - [x] Implemented abstraction for MM Track ([4c79283e](../commit/4c79283ec426c7ebeb32184b55533f5a720e44c9))
  - [x] Fixed some mail tests that were failing in case of environment variable set ([73911120](../commit/7391112092849881e770c668b76210684e41eedb))
  - [x] Added support for current grades fetching and caching ([cf66f58a](../commit/cf66f58a7ba01eaa970f46351cd0aee2291df4bc))

## Robert W House
  - [x] centered the tabs on the program page and added max-width (#1206) ([4db0e85d](../commit/4db0e85db2bb0f4f4acc2a6f036110f0d29261e5))
  - [x] Rh/responsive style tweaks (#1169) ([3ffeccbe](../commit/3ffeccbeb14600acf28b981f9f26ab1e87bd8669))
  - [x] Added photo of reif ([e2e0392d](../commit/e2e0392d39c21deabd353a342732c31caf8185e1))
  - [x] slight text change ([c97dd9d7](../commit/c97dd9d7f621075007265e6f8c7a430baaa93358))
  - [x] added reif quote ([1c68ff71](../commit/1c68ff712a6601e511c333455b60ebfd88736b3a))
  - [x] Several Small Style changes (#1158) ([7c82eeb7](../commit/7c82eeb711f91a9dcf27a183953c61a7deba197d))
  - [x] Tweaks to the style of the faculty carousel (#1139) ([caffad1f](../commit/caffad1fcc1c306a62f549a6ebee258e32826afa))
  - [x] Changed the header with Micromasters logo, and so that home and program page use the same partial file for the navbar html ([2132b7ea](../commit/2132b7eaa561ad41a06d8dcc337115ea607f2629))
  - [x] Rh/even more tweaks gio (#1129) ([0a4291ef](../commit/0a4291ef544444985aa1fc88af71fc7b0b9a52a5))

## George Schneeloch
  - [x] Added missing migration (#1215) ([b44d88e5](../commit/b44d88e5c6c80df9822e62cd0e8bee9809dcc0de))
  - [x] Fixed terms of service signup and login buttons (#1183) ([335726e5](../commit/335726e5f8156fc6fea75d56c0cafa52e1ff52cf))
  - [x] Implemented UI for financial aid states (#1185) ([9ab79c7b](../commit/9ab79c7be0b5a2ec476471c85d3d7dded241807e))
  - [x] Extracted DateField from boundDateField (#1186) ([678fef21](../commit/678fef215542184d8789c30ea80850451d07821e))
  - [x] Removed filter on program enrollments in dashboard API (#1194) ([f1776b37](../commit/f1776b37e1385f247386ea158b5c8e64cb9d55ea))
  - [x] Implemented personal pricing for ecommerce (#1159) ([3d428902](../commit/3d428902632f841e83c9504365ec062438026d9a))
  - [x] Refactored checkout API to work with non-financial aid programs (#1145) ([bb99a967](../commit/bb99a967f8e1762451c61000fc82b6e3efcc512b))
  - [x] Switch to Django JSONField (#1124) ([212f0816](../commit/212f0816f705a19abc83379061a04fcf90a78215))
  - [x] Removed program enrollment from dialog (#1128) ([e3e3d580](../commit/e3e3d580dc70b47d69d4895428d74daf0cc4102a))
  - [x] Fix signup button ([7bb833c7](../commit/7bb833c7038f6cf5426598b2893364c46b446962))
  - [x] Used fill rule to crop faculty images (#1136) ([da68ee38](../commit/da68ee38efd1190499a53f607073ed854a02a860))
  - [x] Set default staff page to learner search (#1126) ([1496e12d](../commit/1496e12d7bc65ae54d52f1806614868d8cdcf413))
  - [x] Implemented enrollment after course purchase (#1092) ([9c89453e](../commit/9c89453ed2720828d5c54ab58f0fa4670aa2f849))
  - [x] Added order receipt and cancellation UI (#1085) ([af2bf857](../commit/af2bf857a021b82157af86976278b99009010c89))

## Amir Qayyum Khan
  - [x] Added select progam to profile tab (#1117) ([3eac2e75](../commit/3eac2e75c8c9dc8f0136362b03b6658b7d8ad9c1))

## Alvin Siu
  - [x] Implemented email templates for financial aid status change emails (#1188) ([dae2d4a3](../commit/dae2d4a3c2329be5343c704088f8f05268ad20e4))
  - [x] Implemented API for learners to skip financial aid and pay full price (#1175) ([9fb3350e](../commit/9fb3350ef4b208b229cad9ab47f2481d94642e3e))
  - [x] Implemented API endpoint for submitting date documents were sent (#1162) ([1e1349f6](../commit/1e1349f65788eba321e26fa3d75c3adff7e25cfd))
  - [x] changes to income cutoffs (15-&gt;25, 100-&gt;75) and associated tests (#1174) ([387a8ffe](../commit/387a8ffe6bd837f0529684ca6409599f9e63caae))
  - [x] Currency Conversion (#1146) ([a6878dd6](../commit/a6878dd618cc3b6c5bffadbd7b44b668d564322d))
  - [x] Financial Aid Auditing (#1138) ([a9f479f9](../commit/a9f479f9dc8e65ee52acda459699b8dcb65abbeb))
  - [x] Added management command for creating Tiers/TierPrograms (#1147) ([8b5ff881](../commit/8b5ff88166a430e4eb7a2fce7d8ba5934bcb0f91))
  - [x] Financial Aid: Implemented endpoint for retrieving a learner&#39;s course price (#1099) ([d33090fd](../commit/d33090fd4dcad50cfe2183f7784c38a6e7b011bb))
  - [x] Financial Aid: Implemented review page backend actions (#1096) ([f8f300f6](../commit/f8f300f65f66c69ac2a576314a03aa7c2e674d2c))
  - [x] Overrode save method on FinancialAid to ensure uniqueness between Use… (#1104) ([f3d7aa54](../commit/f3d7aa541a083228f1cdb39c838c9e75708a7506))

## Peter Pinch
  - [x] more useful fields in admin list views (#1178) ([c9de17a8](../commit/c9de17a8e7445b905d7ee89b1c8cba822f8e8b65))
  - [x] updated django to 1.9.10 (#1176) ([cc7b3506](../commit/cc7b3506951ac583ae3c6ffc050cc5f19c19ceb2))

## Alice
  - [x] refactor getPreferredName (#1156) ([32a4ed5a](../commit/32a4ed5ae37b3d00b191bcc52cb1633d32a37c7f))

## Ferdi Alimadhi
  - [x] Update home_page.html (#1164) ([4e7d349d](../commit/4e7d349d5f48cd762358c760b30ac732dbb3a4bb))

## Alice Pote
  - [x] Removed &#39;Are you a member?&#39; ([9218b262](../commit/9218b262a902479d5acb133fe89538a33ce59961))
  - [x] Added financial aid calculator ([08185c9e](../commit/08185c9e3564b3a1d3dd82ee621a408a2793b3f8))
  - [x] Added profile image to profile API and to frontend ([4fd8060b](../commit/4fd8060b8f571582d00b42f7ed82aa8b7f596599))

### CODE REVIEW

**Comment by annagav** [comment]
Please verify your commits!
https://micromasters-rc.herokuapp.com/

**Comment by amir-qayyum-khan** [comment]
verified my commit.

**Comment by noisecapella** [comment]
done

**Comment by aliceriot** [comment]
oops haha I'm done now too

**Pull request merged**
