### PR TITLE
Exception logging on user api calls

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
- fixes https://github.com/mitodl/micromasters/issues/1374

#### What's this PR do?
- handle exception on user api(s) to avoid crash on pipeline

@pdpinch @giocalitri

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@giocalitri any thoughts?

**Comment by noisecapella** [comment]
It seems like if we are unable to request the username from edX we can't find which user to log in as. I'm not sure if this solution would help anything.

**Comment by amir-qayyum-khan** [comment]
should we logout user then? and show toast or error message?

**Comment by pdpinch** [comment]
@giocalitri @noisecapella what should we do with this PR? 

Was the goal here just to make sure that we know there is a serious issue with the edx APIs?

**Comment by noisecapella** [comment]
I feel like it should be closed, I'm not sure it gets us anything. If the API call fails with an uncaught exception we should see it in sentry I hope. If we fail to get the username for the user from edX then there's nothing we can do to help the user

**Pull request closed without merging**
