### PR TITLE
Support local SSO with edx devstack

### PR DESCRIPTION
**Pull request by collinpreston**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested
- [x] Settings
  - [x] New settings are documented and present in `app.json`
  - [x] New settings have reasonable development defaults, if applicable

#### What's this PR do?
This allows developers to more easily get OAuth SSO working between Micromasters and edX (Devstack) when running both locally.  As part of this change, I am using `EDXORG_BASE_URL` as the outbound base URL for edX and `EDXORG_CALLBACK_URL` for the inbound base URL for edX which is why you will see a lot of the original instances of `EDXORG_BASE_URL` have now been changed to `EDXORG_CALLBACK_URL`.

#### How should this be manually tested?
Follow the updated instructions for setting up Micromasters.  If you already have Micromasters running locally, then replace the following with the values shown in your `.env` file:
```
EDXORG_CALLBACK_URL=http://host.docker.internal:18000/
EDXORG_BASE_URL=http://edx.odl.local:18000/
OPENEDX_HOST_ENTRY=localhost:127.0.0.1
```

Verify the functionality of this PR be ensuring that you can create a new Micromasters account via SSO with edX as well as login to an existing Micromasters account via SSO with edX.

### CODE REVIEW

**Comment by collinpreston** [comment]
Secret key warning appears to be a false positive triggered by formatting the settings.py file.  No value has been added or changed on this branch.

**Review by rachellougee — APPROVED** [review]
This changes work for me. I am able to signin with no issue. Nice work.

Question: Do we need to ask DevOps to add `EDXORG_CALLBACK_URL` to Heroku for RC and production since there is a new env variable added?  This is more a deployment issue though

**Comment by collinpreston** [comment]
@rachellougee, yes before we release this we should create the `EDXORG_CALLBACK_URL` environment variable and set it equal to the same value used for `EDXORG_BASE_URL` in RC and Production.

**Comment by collinpreston** [comment]
Related DevOps ticket for adding the environment variable: https://github.com/mitodl/ol-infrastructure/issues/1247.

**Pull request merged**
