### PR TITLE
Switched to hosted jquery and bootstrap

### LINKED ISSUE #1264: Host jquery, bootstrap, google fonts locally
This would prevent problems when one of the CDNs goes down like jquery's did this morning

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1264 

#### What's this PR do?
Includes bootstrap css and jquery in the static directory and updates links on base.html. The bootstrap JS is already included using public.js

#### How should this be manually tested?
Make sure the mailing list button still works, make sure everything looks ok in general

### CODE REVIEW

**Comment by pdpinch** [comment]
Is there a way that we can pull this in at build time, instead of adding jquery to the repo? I know it leaves in vulnerable to network problems -- but only at build time.

**Comment by noisecapella** [comment]
I'll see about adding it to NPM

**Comment by noisecapella** [comment]
Ready for review again

**Comment by giocalitri** [comment]
Everything seems to work

**Comment by giocalitri** [comment]
👍

**Pull request merged**
