### PR TITLE
Release 0.22.0

### LINKED ISSUE #1410: Multiple CoursePrice objects for same CourseRun marked is_valid causes 500
Is there a way we can prevent this data be entered, instead of throwing a 500 when it happens?

See https://sentry.io/mit-office-of-digital-learning/micromasters/issues/170962083/

### PR DESCRIPTION
**Pull request by annagav**
## George Schneeloch
  - [x] Removed react-loader, use react-mdl react (#1653) ([b93d155c](../commit/b93d155cf97b0f613d5e80b6a4e2837107a16de5))
  - [x] Added country_of_residence to FinancialAid model (#1650) ([4230b973](../commit/4230b9731f4783c44b6eb94266410d7e6ecf9e43))
  - [x] Fixed education/employment deletion when uploading images (#1675) ([148630fc](../commit/148630fc4fa7d819b9b63d34fa4f89bd4325c031))
  - [x] Fixed program enrollment listing bug in signup page (#1674) ([f5749293](../commit/f57492939b9d2439f6cbb1cfbb9a049d8ac10eae))
  - [x] Refactored dashboard API (#1569) ([402689ca](../commit/402689ca5bbd896dd1944df7edf6679928152dc8))
  - [x] Changed education and employment titles (#1629) ([e5c2e10f](../commit/e5c2e10fa51bfd33e9fa03d17f4937333ceb8b70))

## David Baumgold
  - [x] Correctly handle faculty without images (#1634) ([394dc34c](../commit/394dc34c4be4c920f19ff285b7962358913c0ac1))
  - [x] Upgrade Wagtail to 1.7 (#1635) ([e0788ba9](../commit/e0788ba973b23e383fd36f3022aa394fcd25e5d3))
  - [x] Improved chai assertions (#1647) ([f8b0931a](../commit/f8b0931a80d48bc9491d1b13d59169f4737522d5))
  - [x] Upgrade Pillow to 3.4.2 (#1637) ([34669f43](../commit/34669f43c8add1b09f235b01c3b3160aee227867))
  - [x] Upgrade python-social-auth to 0.2.21 (#1643) ([395a7ac6](../commit/395a7ac613a85d66e7ca431ee759a3ecb6ab9dd6))
  - [x] Upgrade Django REST Framework to 3.5.2 (#1638) ([7b1b6d6a](../commit/7b1b6d6a87208cee08372f335ee0ebfd2abae6ca))
  - [x] Upgrade NewRelic to 2.72.1.53 (#1642) ([b21246ea](../commit/b21246eafb74751de542db606fee85ac9af6107e))

## Amir Qayyum Khan
  - [x] Allow to use save button only if photo is selected on &#39;photo upload dialog&#39; (#1654) ([95c90f0f](../commit/95c90f0f9e934f3d55682126d85eb71912166aca))

## Giovanni Di Milia
  - [x] Dashboard model for edx cache refresh timestamps ([89b4cca6](../commit/89b4cca60ff70035801c76ff14e642eff503c6f0))
  - [x] Changed url precedence ([0ea95728](../commit/0ea9572895d119695af1091719098639e43a4ba2))
  - [x] removed list of panels ([36a1d54a](../commit/36a1d54a0dbf10141b319817514e282141213bfa))
  - [x] Added Django Debug Toolbar in Debug mode ([8467fd42](../commit/8467fd42fb55b543233f3f9781e45aa7d4e3f91b))

## Tobias Macey
  - [x] Removed cheaper setting for uWSGI (#1673) ([a448b3c9](../commit/a448b3c9be1a9eb51b224fd1aeec3553c7ac65f9))
  - [x] Updated uWSGI to properly use threads and handle static assets (#1648) ([e0bbcb66](../commit/e0bbcb669b04906aa96b4264882edafd23f45978))

## Alice Pote
  - [x] Reorganized CSS ([a6e7cd2d](../commit/a6e7cd2dc7a621e3c5ca63fc005596516c1958fe))

## annagav
  - [x] ProfilePage scroll top between steps ([32a78e2b](../commit/32a78e2bf6d6c68a10b370d62123e9b2d46e8120))
  - [x] Save leading zeros in month field ([334799f3](../commit/334799f349951e0bca775bbcbb6c10d996f287f2))
  - [x] Change Company Name field ([b06ba9e7](../commit/b06ba9e7213d273f99fc8dc9384885a6598719de))

## Nathan Levesque
  - [x] Added model validation to CoursePrice to fix #1410 ([4d2a4507](../commit/4d2a4507ac892923547f8e04c18be9a7eb481056))

### CODE REVIEW

**Comment by giocalitri** [comment]
Done (also @blarghmatey and @singingwolfboy PRs)

**Comment by aliceriot** [comment]
done!

**Comment by noisecapella** [comment]
done

**Comment by annagav** [comment]
@giocalitri, @singingwolfboy Please check off your commits!

**Comment by giocalitri** [comment]
done

**Comment by singingwolfboy** [comment]
done

**Pull request merged**
