### PR TITLE
add 'program' after 'MITx MicroMasters' in footer

### LINKED ISSUE #4290: Commendation Letter: add 'program' after 'MITx MicroMasters' in footer
edX has requested that the letter's footer be changed to, for example, "MITx MicroMasters program in Supply Chain Management" 

I don't think it needs a ® symbol, but I'll check before the PR is reviewed.

### PR DESCRIPTION
**Pull request by pdpinch**
#### What are the relevant tickets?

fixes #4290

#### What's this PR do?

adds the word "program" to the end of the letter 

#### How should this be manually tested?

View a commendation letter (an existing one should be adequate) 

#### Screenshots (if appropriate)

I need to generate a screenshot for SCM's review before this is merged.

### CODE REVIEW

**Comment by pdpinch** [comment]
@tasawernawaz can you get a screenshot of this change for me, so I can get the SCM folks to review it?

**Comment by tasawernawaz** [comment]
@pdpinch 
Screen Shot 2019-04-03 at 1 22 30 PM

**Comment by pdpinch** [comment]
Thanks for the screenshot. I'm checking it with the SCM team.

**Comment by pdpinch** [comment]
Thanks for the screenshot. This has been approved by SCM.

**Pull request merged**
