### PR TITLE
Add pre and post compile hooks (migrations and git hash)

### LINKED ISSUE #38: Add pre and post compile hooks from TeachersPortal
The pre-compile hook writes the git hash to the static file dir.
The post-compile hook runs migrations automatically.

### PR DESCRIPTION
**Pull request by bdero**
#### What are the relevant tickets?
Closes #38 

#### What's this PR do?
This PR adds in the pre and post compile hook straight from TeachersPortal. It allows for running migrations and

#### Where should the reviewer start?
See if the PR app (listed in this PR with a squirrel icon) has successfully deployed (meaning the build passed without error). If it deploys, the migration command returned a success signal.

#### How should this be manually tested?
Check if the git hash is being served from the static files on the review app: https://[pr-app].herokuapp.com/static/hash.txt
If the hash is shown, that means the pre_compile hook successfully ran when Heroku was generating the build artifacts, and that static files are configured properly.

### CODE REVIEW

**Comment by bdero** [comment]
Uh oh, looks like it had problems deploying.

**Comment by bdero** [comment]
Well, this is awkward:

**Comment by bdero** [comment]
I pushed this to release-candidate in order to test:

```
-----> Using set buildpack heroku/nodejs

-----> Node.js app detected

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NPM_CONFIG_PRODUCTION=true

       NODE_ENV=production

       NODE_MODULES_CACHE=true

-----> Installing binaries

       engines.node (package.json):  unspecified

       engines.npm (package.json):   unspecified (use default)

       

       Resolving node version (latest stable) via semver.io...

       Downloading and installing node 5.6.0...

       Using default npm version: 3.6.0

-----> Restoring cache

       Loading 2 from cacheDirectories (default):

       - node_modules

       - bower_components (not cached - skipping)

-----> Building dependencies

       Pruning any extraneous modules

       Installing node modules (package.json)

-----> Caching build

       Clearing previous node cache

       Saving 2 cacheDirectories (default):

       - node_modules

       - bower_components (nothing to cache)

-----> Build succeeded!

       ├── babel@6.5.2

       ├── babel-core@6.6.4

       ├── babel-loader@6.2.4

       ├── babel-plugin-jsx@1.2.0

       ├── babel-preset-es2015@6.6.0

       ├── babel-preset-react@6.5.0

       ├── react@0.14.7

       ├── webpack@1.12.14

       └── webpack-dev-server@1.14.1

       

-----> Using set buildpack heroku/python

-----> Python app detected

-----> Running pre-compile hook

-----> Writing out SOURCE_VERSION to static/hash (3b6a02a8c78da64f503a09e250d2d6ca2480ddf5)

     $ pip install -r requirements.txt

       Collecting djangorestframework==3.3.2 (from -r requirements.txt (line 10))

         Downloading djangorestframework-3.3.2-py2.py3-none-any.whl (634kB)

       Installing collected packages: djangorestframework

       Successfully installed djangorestframework-3.3.2

     $ python manage.py collectstatic --noinput

       79 static files copied to '/app/staticfiles'.

-----> Running post-compile hook

-----> Running django migrations

       /app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py:399: RemovedInDjango110Warning: The 'migrate --list' command is deprecated. Use 'showmigrations' instead.

         output = self.handle(*args, **options)

       

       admin

        [ ] 0001_initial

        [ ] 0002_logentry_remove_auto_add

       auth

        [ ] 0001_initial

        [ ] 0002_alter_permission_name_max_length

        [ ] 0003_alter_user_email_max_length

        [ ] 0004_alter_user_username_opts

        [ ] 0005_alter_user_last_login_null

        [ ] 0006_require_contenttypes_0002

        [ ] 0007_alter_validators_add_error_messages

       contenttypes

        [ ] 0001_initial

        [ ] 0002_remove_content_type_name

       courses

        [ ] 0001_initial

       sessions

        [ ] 0001_initial

       ui

        (no migrations)

       Operations to perform:

         Apply all migrations: admin, courses, sessions, contenttypes, auth

       Running migrations:

         Rendering model states... DONE

         Applying contenttypes.0001_initial... OK

         Applying auth.0001_initial... OK

         Applying admin.0001_initial... OK

         Applying admin.0002_logentry_remove_auto_add... OK

         Applying contenttypes.0002_remove_content_type_name... OK

         Applying auth.0002_alter_permission_name_max_length... OK

         Applying auth.0003_alter_user_email_max_length... OK

         Applying auth.0004_alter_user_username_opts... OK

         Applying auth.0005_alter_user_last_login_null... OK

         Applying auth.0006_require_contenttypes_0002... OK

         Applying auth.0007_alter_validators_add_error_messages... OK

         Applying courses.0001_initial... OK

         Applying sessions.0001_initial... OK

-----> Discovering process types

       Procfile declares types -> web

-----> Compressing...

       Done: 67.2M

-----> Launching...

       Released v10

       https://micromasters-rc.herokuapp.com/ deployed to Heroku
```

The build succeeded and the hash is here: https://micromasters-rc.herokuapp.com/static/hash.txt

**Comment by noisecapella** [comment]
Code looks good, I'll try the hash after the deployment succeeds

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
