### PR TITLE
Fixed layout user card safari

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/micromasters/issues/1982

#### What's this PR do?
Fix `LearnerInfoCard.js` layout issue on  `/learner/{learner name}` for safari 9.1.2.

#### How should this be manually tested?
- open your `/learner/{learner name}` page on safari 9.1.2

@pdpinch 

screen shot 2017-02-28 at 7 08 43 pm

### CODE REVIEW

**Comment by roberthouse54** [comment]
Hi Amir. It seems patly fixed, but if I make the browser less wide (on mobile for example), the name still seems to go underneath the user image. (See screenshot below)

image

**Comment by roberthouse54** [comment]
The layout is still not working on mobile width devices:

image

**Comment by amir-qayyum-khan** [comment]
Done @roberthouse54 

screen shot 2017-03-08 at 6 19 01 pm

screen shot 2017-03-08 at 6 20 02 pm

screen shot 2017-03-08 at 6 21 14 pm

**Comment by roberthouse54** [comment]
Amir this is still not quite right. It is not breaking the way I want it to. But I think I have found a solution.

On the div .col.user-info, remove the width: 75%, and add flex-grow: 2. Also change the margin-left from 10px to 20px. So it should look like this:

.col.user-info {
    margin-left: 20px;
    word-wrap: break-word;
    flex-grow: 2;
}

**Comment by roberthouse54** [comment]
Looks good to me 👍

**Pull request merged**
