### PR TITLE
Fixed jumbled text when entering text in search mail dialog in chrome

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/micromasters/issues/3365

#### What's this PR do?
Fixed jumbled text when user use tab on email composer

#### How should this be manually tested?
go to email compose and use tab to set subject and body

@pdpinch @aliceriot

### CODE REVIEW

**Comment by aliceriot** [comment]
@amir-qayyum-khan we have to use `this.state` to hold the `editorState` object because it's not a plain JS object, it's an [Immutable](https://facebook.github.io/immutable-js/) object, which can't really be stored in the redux store.

**Comment by noisecapella** [comment]
It looks like this fixes the issue on Chrome but I'm seeing a problem on Firefox. Can you investigate further?

**Comment by pdpinch** [comment]
@amir-qayyum-khan what's happening with this PR?

**Comment by amir-qayyum-khan** [comment]
@noisecapella please review thsi

**Comment by noisecapella** [comment]
Confirmed that IE, Firefox and Chrome work fine now

**Pull request merged**
