### PR TITLE
Responsive program page

### PR DESCRIPTION
**Pull request by singingwolfboy**
Making the program page responsive. @roberthouse54, could you review this?
top of program page
middle of program page
faculty on program page

### CODE REVIEW

**Comment by Ferdi** [comment]
@singingwolfboy is there anyway  to keep "Faculty" as carousel with one image per slide ?

**Comment by roberthouse54** [comment]
@Ferdi I requested that on mobile, we just switch to a stacked vertical layout, since users will be vertically scrolling anyway. My concern is that it will be an awkward layout on mobile, and users may not realize that there is more than one faculty.

**Comment by roberthouse54** [comment]
I am thinking I would like to merge this as is, since it is mostly all working. I will want to go through both this and the home page and make some tweaks for mobile layout, but I'd like to do that as a separate PR.

**Comment by singingwolfboy** [comment]
@roberthouse54 Sounds good to me. Let's wait for all the tests to pass on Travis CI, and then you're clear to hit the merge button, as far as I'm concerned.

**Comment by roberthouse54** [comment]
👍

**Pull request merged**
