### PR TITLE
Use poetry for python dependency management

### PR DESCRIPTION
**Pull request by annagav**
# What are the relevant tickets?
Fixes https://github.com/mitodl/micromasters/issues/5343
# Description (What does it do?)
Use poetry for python dependency management.
Removes requirements files.

# How can this be tested?
Nothin should break.
Run `docker-compose build --no-cache web celery`
CI tests should pass.

### CODE REVIEW

**Review by mbertrand — CHANGES_REQUESTED** [review]
Looks great! A couple minor suggestions:

- Can you add poetry to the `buildpacks` section of `app.json`?  It won't really have any effect unless MM is reinstalled on heroku from scratch, but it might be nice to have in there anyway like in the other apps that have been migrated.  PS this buildpack will need to be manually added to heroku or else the deployments will fail.

```
  "buildpacks": [
    {
      "url": "https://github.com/heroku/heroku-buildpack-apt"
    },
    {
      "url": "https://github.com/heroku/heroku-buildpack-nodejs"
    },
    {
      "url": "https://github.com/moneymeets/python-poetry-buildpack"
    },
    ...etc
```

- Add [a section to the README](https://github.com/mitodl/mitxonline/pull/1800/files) on how to update dependencies on poetry.

**Comment by annagav** [comment]
@mbertrand I this poetry is already added to `buildpacks` here: https://github.com/mitodl/micromasters/pull/5345/files#diff-96677aa35debfefd031d9d34d9c70369754ee3acb2d9a9d4090e98612efee6f5R11-R13

**Comment by annagav** [comment]
@mbertrand I addressed all your comments. Thank you for the review!

**Review by mbertrand — APPROVED** [review]
Looks great! 👍

**Pull request merged**
