### PR TITLE
After login the user is redirected to dashboard

### PR DESCRIPTION
**Pull request by giocalitri**
#### What's this PR do?
The redirect after the login is to the user dashboard page

### CODE REVIEW

**Comment by Ferdi** [comment]
I thought they'd go to dashboard ?

**Comment by giocalitri** [comment]
I thought the idea was that they had to go to profile and then, if the profile was complete, go to the dashboard.
Honestly now it is not a problem either way

**Comment by noisecapella** [comment]
Maybe we should change this to redirect to /dashboard instead? Then in our future PR we would redirect to /profile in the frontend if they have not filled out the profile yet

**Comment by giocalitri** [comment]
fine with me

**Comment by giocalitri** [comment]
done

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
