### PR TITLE
Removed dialog from profile validation

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/micromasters/issues/285

#### What's this PR do?
- Removed popup message for missing contents in fields
- Added highlight validation.

#### Where should the reviewer start?
see Apps.js and utils.js

#### How should this be manually tested?
- Left any filed content missing on profile tab
- Move to last tab and press save and continue
- You will be navigate to profile where you have missing contents.
- The filed with missing contents will be highlight

@aliceriot @noisecapella @pdpinch 

#### Screenshots (if appropriate)

- screen shot 2016-05-16 at 4 04 11 pm
- screen shot 2016-05-16 at 4 04 21 pm
- screen shot 2016-05-16 at 4 04 11 pm

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@aliceriot,
- I accidentally merged PR without squashing commits and rebasing https://github.com/mitodl/micromasters/pull/314.
- Then I revert it https://github.com/mitodl/micromasters/pull/409.
- Now i made this PR, can I merge it?

**Comment by noisecapella** [comment]
Reverting that commit won't fix the squashing, that's in master. If the squash is the only problem with that commit I would have recommended not reverting it at all

**Comment by aliceriot** [comment]
agreed, those commits are already in master, reverting only means we have additional noise in the commit history.

**Comment by aliceriot** [comment]
that said, obviously we now need to merge this in order to have the change in master, so :+1:, but in the future don't push

**Comment by amir-qayyum-khan** [comment]
So should i merge it?
@aliceriot @noisecapella

**Comment by aliceriot** [comment]
yes

**Pull request merged**
