### PR TITLE
ensure a validator is available on this.props in the about me dialog

### PR DESCRIPTION
**Pull request by aliceriot**

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
Do you need to update https://github.com/mitodl/micromasters/blob/master/static/js/components/UserPageAboutMeDialog.js#L12 ?

**Comment by amir-qayyum-khan** [comment]
you need to remove https://github.com/mitodl/micromasters/blob/master/static/js/components/UserPageAboutMeDialog.js#L6 and update https://github.com/mitodl/micromasters/blob/master/static/js/components/UserPageAboutMeDialog.js#L32

**Comment by aliceriot** [comment]
can you comment ont he pull request directly? it is much easier to read that way.

**Comment by aliceriot** [comment]
do you mean change that to pull the validator out of `this.props` instead?

**Comment by amir-qayyum-khan** [comment]
i cant see these lines in diff

**Comment by aliceriot** [comment]
you can expand the diff to show other lines.

comments should be addressed.

**Comment by amir-qayyum-khan** [comment]
👍

**Pull request merged**
