### PR TITLE
navbar changes

### LINKED ISSUE #2564: Add Navigation - Sidebar
The goal of this issue is to add a navigation drawer (sidenav) that will be available on all pages in the app, on both desktop and mobile. The sidenav will have links to all pages, including the links that are currently in the user dropdown into the side nav. The "context switcher" will remain in the topnav, but move to the right side where the user dropdown is now. For mobile devices, the context switcher will be in the sidenav (as it is now).

The sidenav, when open, will cover the content on the page. The menu icon will open and close the sidenav. A chevron arrow will close the sidenav, or swiping left will also close the sidenav.

Staff users, faculty and other admin users who have links to admin pages, we see links to those pages above the "My Profile" link.

_In the future we may change this so the sidenav will be open by default if the device is wide enough to have it be open without covering the content of the page._

navigation_new 2x

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #2564 

#### What's this PR do?

This puts the navbar on all desktop-width pages, and changes around which links show up for staff, which for learners, etc. Check the issue for details on the changes there.

#### How should this be manually tested?

go to any page. you should see a little hamburger in the upper left, which should open the nav menu. there's a little chevron icon which, when clicked, should close the menu again. clicking outside the menu should also close it.

If you're a staff user you should see the following:

asdfasdfasdf

if you're not you should see:

fasfffjfj

to simulate 'learner' status you can set `SETTINGS.roles` to `[]`.

### CODE REVIEW

**Comment by noisecapella** [comment]
When I hover over the chevron it looks a little strange:
screenshot from 2017-03-09 13-20-58

**Comment by aliceriot** [comment]
oh oops I meant to fix that, sorry

**Comment by aliceriot** [comment]
@noisecapella just pushed a little styling change that should fix that!

**Comment by noisecapella** [comment]
It looks like the selenium test is failing due to the user menu being removed. Can you update the test to use the new slider link instead?

Also can you force push to redeploy to heroku? Yarn had a timeout

**Comment by aliceriot** [comment]
I always forget about the selenium tests! looking into it now

**Comment by aliceriot** [comment]
ok I think I fixed it!

**Pull request merged**
