### PR TITLE
Capture user's full address

### PR DESCRIPTION
**Pull request by singingwolfboy**
#### What are the relevant tickets?
Part of #2285. Adds two fields to the user profile form: street address, and postal code. The street address field is limited to 100 characters, a limitation that is reflected in the database backend. The postal code field only shows up if the country is "United States" or "Canada".

Note that the "state" field is present and required in all cases, even though Pearson only cares about it in some cases.

#### How should this be manually tested?
Play with these new fields. Make sure they accept valid input, and that they throw a validation error on invalid input (empty fields). Refresh the page, and make sure that the values are re-populated after being saved. Be sure that you can save an address outside of the United States and Canada without a postal code, and that you can't save an address within those two countries without a postal code.

#### Screenshots (if appropriate)
screen shot 2017-01-10 at 3 07 22 pm
screen shot 2017-01-10 at 3 08 03 pm

### CODE REVIEW

**Comment by roberthouse54** [comment]
Visually looks good to me 👍

**Comment by Ferdi** [comment]
@singingwolfboy How are we dealing with zipcode input ? is it required ?

**Comment by singingwolfboy** [comment]
@Ferdi the postal code is required if the country is set to United States or Canada. Otherwise, it doesn't appear in the UI.

**Comment by pdpinch** [comment]
Does this change apply to /learner/{username} as well as /profile/personal, so users can update their phone number?

If it's a lot of work, I'm ok with opening another issue. I'd really like to see this deployed this week.

**Comment by rhysyngsun** [comment]
@pdpinch this applies to both pages, although this PR is only for the address fields. Alice is doing the phone number work in #2240.

**Comment by rhysyngsun** [comment]
@roberthouse54 is this error message ok if users enter a non-latin street address? I'll be adding a similar message for postal code as well.
selection_015

**Comment by rhysyngsun** [comment]
Postal code error message
selection_016

**Comment by roberthouse54** [comment]
Both of those are good.

**Comment by aliceriot** [comment]
@rhysyngsun for trying this out, what things do I need to have enabled for my API key? I have one that I set up before to review https://github.com/mitodl/micromasters/pull/2167

**Comment by aliceriot** [comment]
^^ nvm! haha

**Comment by aliceriot** [comment]
functionality looks good!

**Comment by aliceriot** [comment]
@annagav I'm reviewing :)

**Comment by aliceriot** [comment]
oh nvm didn't see you were already on it! nvm

**Comment by rhysyngsun** [comment]
Waiting on #2352 to merge.

**Comment by rhysyngsun** [comment]
@annagav I see you approved the PR, but didn't change the tag back to `Waiting on Author` - was your review done?

**Comment by singingwolfboy** [comment]
I rolled #2364 into this pull request, due to test failures: https://travis-ci.org/mitodl/micromasters/jobs/192719704

**Comment by singingwolfboy** [comment]
Based on feedback from @rhysyngsun and @noisecapella, I've removed #2364 from this pull request, and I'm changing the migration dependency to point to `0028_auto_20170113_2133`.

**Pull request merged**
