### PR TITLE
Release 0.13.0

### PR DESCRIPTION
**Pull request by annagav**
## Alice Pote
  - [x] Added &#39;jump to error&#39; on profile forms
  - [x] Removed .name call on anonymous functions for createActionHelper ([70fcc7e2](../commit/70fcc7e24345bb6a9f39bae4562eb18b5ecb1029))
  - [x] Installed Searchkit and implemented basic learners search ([538bdfc6](../commit/538bdfc6ef0a4dbb538033e8391124a8295968b4))
  - [x] Implemented ValidationAlert to alert user to problems in form dialogs ([0e953ab8](../commit/0e953ab8870e9db8f2ed471d8de0f1b8f35bccc0))
  - [x] Refactored `actions/index.js` ([e0b69ad7](../commit/e0b69ad7d7bb41cf3d9a0c6338f9e2e700d8c002))
  - [x] Fixed a bug with clearProfileEdit ([03dc346f](../commit/03dc346f49fededece3bf8a809c04344905a890d))
  - [x] Implemented new design for user menu ([9436c43d](../commit/9436c43d1b6d76f06e9e6559e3cffa2a0a4dd03c))
  - [x] Added bpython to test_requirements.txt ([2738a1e5](../commit/2738a1e55cea1359253eee0798cd4255ca0a060e))
  - [x] Removed box-shadow from Navbar ([d3d42727](../commit/d3d42727e4e907d7ce156a92924685518db9f3d6))
  - [x] Implemented new navbar design ([07785ee4](../commit/07785ee42ccc93d2caf0d95291c7323b40f4252e))
  - [x] Added new ProfileImage component ([9c32ac28](../commit/9c32ac28f6434dac68532ca6ef93af6001e69512))
  - [x] Refactored ProfileFormContainer to remove boilerplate ([c1a38461](../commit/c1a3846140e4a34f5e3888058ccddcc9bdc1634e))
  - [x] Updated validation state when editing fields ([77143744](../commit/771437443b6fecf872e9a65819dc20c9931c6c20))
  - [x] Moved ErrorMessage tests into separate file ([5c2af368](../commit/5c2af368b5aca4f8900df01ba087b8807719bee3))
  - [x] Fixed bug where validation errors showed up on first login ([bd4f2a6d](../commit/bd4f2a6d1338ace37f688618d00a535e466df9bb))
  - [x] Changed getPreferredName to show last name ([dc94bf3a](../commit/dc94bf3a9e7dd69a95127715fa27d6f3d6ccbade))

## George Schneeloch
  - [x] Added roles to SETTINGS (#783) ([fff4afab](../commit/fff4afabd195d188f02a6d4dfe7f67e4bff12eb0))
  - [x] Added indexing for Certificate and Enrollment ([8e0832de](../commit/8e0832de5d267325a4182abe1ae3b28daca623b8))
  - [x] Added models for Enrollment and Certificate and code to populate them on dashboard load ([a3b6dfa2](../commit/a3b6dfa2f6217d7fbbfb0ffd1d6df7eb421e87bb))
  - [x] Pinned html5lib to fix build (#722) ([cae3f0a5](../commit/cae3f0a53ed5aea008a7b65fdb5f0a948124a497))
  - [x] Added Elasticsearch index, indexing for Profile and related models (#706) ([934d1414](../commit/934d1414640cf18f7d3f758fa984c330a50947fa))
  - [x] Added get_social_username, updated existing code to use it (#705) ([36462b3d](../commit/36462b3d9a1e58fc69c1fd80645f2509e25e59d8))

## Giovanni Di Milia
  - [x] Added celery start command to Procfile 
  - [x] Changed ProgramEnrollment with more efficient update ([dd3bb3ee](../commit/dd3bb3ee0e5eb0b00af3717dfbc9edf4a3c2deaa))
  - [x] Fixed signals for indexing Cached ceritficates and enrollments ([df23d190](../commit/df23d19084eddee3f57c2859fb1df8a878fb2e41))
  - [x] Modified caching logic: now all runs get an entry in the cache ([b890d4fb](../commit/b890d4fb7b3a786a6512da0379c66c3d0a9242dc))
  - [x] Added custom roles definition. ([29b0d578](../commit/29b0d5781e83068402580daf26f0f11918b2cb44))
  - [x] Added celery, elasticsearch, redis ([a92cf6d8](../commit/a92cf6d86a33a1f7bdeaa3fba5c7940e5495f219))

## annagav
  - [x] Added ProgramEnrollments to dashboard ([ac65fda9](../commit/ac65fda99e71d16b23d525362b2dda1d8e039f26))

## Gavin Sidebottom
  - [x] Created management command to generated realistic-looking fake users ([585d91d9](../commit/585d91d92ec58ed3ff2cd937a30d837bd0e83e1c))

## Amir Qayyum Khan
  - [x] Mocked certificate to api in test suit to run even if edx instance is close/shutdown ([f32484eb](../commit/f32484eb5195fd48983a5196bca1d606444adcf9))
  - [x] Added e-mail opt-in to user settings ([cc12f93d](../commit/cc12f93dbc2d16a567a0046421be689cc45de698))

## Brandon DeRosier
  - [x] Update to Django 1.9.8 ([9e22e8e9](../commit/9e22e8e9de644a4bae2ac25993316e05e8a675d9))

## Peter Pinch
  - [x] Updated README with basic CMS docs (#688) ([ff77dc23](../commit/ff77dc238da23c1d69ce522c2cffa7ff2430a0e5))

### CODE REVIEW

**Comment by annagav** [comment]
@giocalitri, @aliceriot , @noisecapella, @gsidebo, @amir-qayyum-khan, @pdpinch, @bdero Please verify your commits!

**Comment by pdpinch** [comment]
Done! =)

**Comment by aliceriot** [comment]
Something's messed up, I'm getting an error when I try to open forms in the profile:

error_thing

anyone else seeing that? could be a particular of my user account.

**Comment by noisecapella** [comment]
Yes I'm seeing it too...

**Comment by aliceriot** [comment]
I don't see it locally on master, hm

**Comment by noisecapella** [comment]
It seems like a name mangling error... :scream_cat: I'll investigate further

**Comment by noisecapella** [comment]
It looks like it was introduced in this PR: https://github.com/mitodl/micromasters/pull/713

**Comment by noisecapella** [comment]
It looks like that PR is using `actionCreator.name` as a key value but the minifier is mangling that name

**Comment by aliceriot** [comment]
Ah, unforseen side effects. I had originally written that code without
.name so I can quickly fix it tomorrow.

**Comment by amir-qayyum-khan** [comment]
@aliceriot verified commits

**Comment by noisecapella** [comment]
@annagav can you recreate this release to incorporate @aliceriot's PR that fixes the issue?

**Comment by annagav** [comment]
This PR was updated with Alice's fix.

**Comment by giocalitri** [comment]
I verified my commits and also Brandon's and Gavin's ones.

**Pull request merged**
