### PR TITLE
Updated heroku stack in app.js file

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/micromasters/issues/3918

#### Run these commands from hero cli:
```cli
heroku stack:set heroku-16 -a <app name>
git commit --allow-empty -m "Upgrading to heroku-16"
git push heroku master
```
https://devcenter.heroku.com/articles/heroku-16-stack#upgrading-an-app-to-heroku-16

I dont have permission but admin need to go to app (lets say micromasters-ci) settings and
screen shot 2018-04-20 at 3 55 55 pm
 inside info section press the button

cc @mitodl/devops 

#### What's this PR do?
it updates heroku stack.

#### How should this be manually tested?
see the heroku version of this PR

@pdpinch

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops should i run these command or you guys will do that?

**Comment by blarghmatey** [comment]
:+1:

**Comment by amir-qayyum-khan** [comment]
@blarghmatey  @mitodl/devops someone needs to do steps mention in description of this PR. Then i will merge it.

**Comment by shaidar** [comment]
I set `heroku-16` stack to run on the next deployment to `micromasters-ci`

**Pull request merged**
