### PR TITLE
Fixed failed to execute getComputedStyle on Window error on zendesk script

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
#### What are the relevant tickets?
fixes https://github.com/mitodl/micromasters/issues/3602

#### What's this PR do?
it updates css select on `zendesk_widget.js`, it appears that zendesk changed style on their end, to match with it i need to change the selector.

#### How should this be manually tested?
login to your MM and see console (Probably on dashboard)

@pdpinch

### CODE REVIEW

**Comment by pdpinch** [comment]
do you think this will fix https://github.com/mitodl/micromasters/issues/3435 as well?

**Comment by amir-qayyum-khan** [comment]
No @pdpinch this will not fix #3435 , that error messages are temporary and we are logging them

**Comment by amir-qayyum-khan** [comment]
@pdpinch these are temporary errors. 
Should i remove `console.error(`couldn't find Zendesk iframe: ${name}`) // eslint-disable-line no-console` from [here](https://github.com/mitodl/micromasters/blob/master/static/js/entry/zendesk_widget.js#L215). because app retries by itself

**Comment by noisecapella** [comment]
I think this fix will work until zendesk changes something again and our CSS selector stops working. Can we look through our zendesk code to see where else we may run into this problem?

**Comment by amir-qayyum-khan** [comment]
there are many `document.querySelector` selectors in [code](https://github.com/mitodl/micromasters/blob/master/static/js/entry/zendesk_widget.js) which can create same issue in future.

**Pull request merged**
