### PR TITLE
Reorganize JS code

### LINKED ISSUE #920: reorganize JS code
@gsidebo has suggested many time that `util` is not a great name for a directory that contains a bunch of somewhat unrelated functions and react components. I think we should think a little bit about how best to organize things. Currently the `static/js` directory looks like this:

```
├── actions
├── components
│   ├── dashboard
│   ├── inputs
│   ├── search
│   └── utils
├── containers
├── flow
├── public
│   └── components
├── reducers
├── store
└── util
```

I think we should have some discussion about how best to reorganize it, and what would make sense. As a way to get the discussion going, here's one proposal:

```
├── actions
├── components
│   ├── dashboard
│   ├── inputs
│   ├── search
│   └── utils -> shared
├── containers
├── flow
├── public
│   └── components
├── reducers
├── store
└── util -> lib
```

So basically renaming the `utils` directory to `lib`, and renaming `components/utils` to `components/shared`. We could also move the few component-ey things that are currently in `util` into `components/shared`, and maybe think about gradually refactoring some more of the methods that return components which live in `util` into full fledged components (not necessarily classes, but living in their own file, having a name, having separate tests, etc).

Then `lib` would really be a bit more focused and would only really contain libraries we've written, such as the validation library, the api library, sorting functions, etc.

What do you think @noisecapella @gsidebo ?

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #920 

#### What's this PR do?

Big ol' JS reorganization. Compare `tree -d ./static/js`:

`master`:

```
./static/js
├── actions
├── components
│   ├── dashboard
│   ├── inputs
│   ├── search
│   └── utils
├── containers
├── financial_aid
├── flow
├── public
│   └── components
├── reducers
├── store
└── util
```

this branch:

```
./static/js
├── actions
├── components
│   ├── dashboard
│   ├── inputs
│   ├── search
│   └── utils
├── containers
├── data
├── entry
├── financial_aid
├── flow
├── lib
│   └── validation
├── reducers
├── store
└── util
```

The big changes are:

- moving a bunch of things from `util` to `lib` (like the validation code, currency code, etc)
- moving all webpack entry scripts into `entry`
- moving all big data files (country names and so on) into `data`
- deleting dead code in `public`

These changes are all individual commits, so we can revert any of these changes as we see fit - consider the PR as-is to be a proposal.

@noisecapella @gsidebo what do y'all think?

### CODE REVIEW

**Comment by noisecapella** [comment]
Yeah, all this looks like an improvement to me

**Comment by singingwolfboy** [comment]
Looks good to me. I haven't manually tested this, but assuming that you already have (and everything still works), 👍 from me.

**Comment by pdpinch** [comment]
Do you think this will reduce our JavaScript download size at all (see #1500)?

**Comment by noisecapella** [comment]
No, it's just a reorganization, there's nothing removed

**Comment by noisecapella** [comment]
@singingwolfboy mentioned that we do remove some parts of the public.js bundle, so that may be smaller. I'll look at the filesizes

**Comment by noisecapella** [comment]
-rw------- 1 u26513 dyno  255189 Oct 24 20:18 course_list.js
    -rw------- 1 u26513 dyno 2377133 Oct 24 20:18 dashboard.js
    -rw------- 1 u26513 dyno  174740 Oct 24 20:18 faculty_carousel.js
    -rw------- 1 u26513 dyno  431214 Oct 24 20:18 financial_aid.js
    -rw------- 1 u26513 dyno   48060 Oct 24 20:18 public.js
    -rw------- 1 u26513 dyno   24321 Oct 24 20:18 sentry_client.js
    -rw------- 1 u26513 dyno  785813 Oct 24 20:18 signup_dialog.js
    -rw------- 1 u26513 dyno  676474 Oct 24 20:18 style.js
    -rw------- 1 u26513 dyno  229752 Oct 24 20:18 style_public.js
    -rw------- 1 u26513 dyno    1197 Oct 24 20:18 zendesk_widget.js


It looks like the public.js bundle is 20k smaller, other than that the changes are not significant

**Comment by aliceriot** [comment]
I deleted some code that was added in a home page redesign back in April which was not being used (stuff that was included in the `public.js` bundle).

**Comment by aliceriot** [comment]
@noisecapella do you think this is good to merge?

**Comment by noisecapella** [comment]
I need to do a functionality test just to make sure the file paths all still line up

**Pull request merged**
