### PR TITLE
Upgrade Raven

### PR DESCRIPTION
**Pull request by singingwolfboy**
Raven is the error-reporting client for [Sentry](https://sentry.io).

* [Python Changelog](https://github.com/getsentry/raven-python/blob/master/CHANGES)
* [JS Changelog](https://github.com/getsentry/raven-js/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by aliceriot** [comment]
same comment about `npm-shrinkwrap.json` :)

**Comment by singingwolfboy** [comment]
Fixed.

**Comment by noisecapella** [comment]
:+1:

**Comment by aliceriot** [comment]
The `npm-shrinkwrap` change seems to cover almost every dependency we use - is it possible you're using a different version of `npm` than the one we use in the docker container (3.9.5)?

**Comment by singingwolfboy** [comment]
@aliceriot Because I'm on a Mac, I'm using a `node`/`npm` installation local to my Mac, managed via Homebrew. I like to keep things up to date, so I'm currently running `npm` version 3.10.9. I didn't realize that would be a problem.

Homebrew makes it hard to downgrade -- not impossible, but hard. Would you like me to try to do so, to get this pull request smaller? I'm not clear on how the `npm-shrinkwrap` file is affected by different versions of `node` and `npm`.

**Comment by aliceriot** [comment]
I think generally you should try to use the version of node / npm we're standardized on. I'm not sure about the differences b/tw npm 3.9.5 and 3.10.9, but regardless we should be using the same versions of language runtimes and package managers everywhere.

The [node version manager](https://github.com/creationix/nvm) might be helpful in doing this.

**Comment by singingwolfboy** [comment]
@aliceriot I just installed Node 6.2.2 and npm 3.9.5, and still got the same changes to the npm-shrinkwrap file when I did `npm install --save raven-js`. Maybe it's a mac-vs-linux thing? I'm confused.

**Comment by aliceriot** [comment]
huh that's weird. idk! It's weird that it is changing lines for unrelated packages, that doesn't happen on linux.

what steps did you do exactly?

**Comment by aliceriot** [comment]
bah `npm === pain`, we're just going to check in the big thing.

**Pull request merged**
