### PR TITLE
Fixed IE11 support for image upload

### LINKED ISSUE #1401: Unable to upload a profile image in Edge & IE11
It is not possible for a user to upload an image to their profile using either Edge or IE11.
Steps to Reproduce:
Log into MicroMasters
Create a new profile on edX.
Click on the camera icon on the top of the first profile page/tab and
attempt to upload an image.
When a user clicks the save button on the popup, a spinny appears briefly, but no image is uploaded.

This functionality works on Firefox & Chrome.

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #1401

#### What's this PR do?
Fixes image upload for IE11 and edge

### CODE REVIEW

**Comment by gsidebo** [comment]
code looks good here. is @j2tausig supposed to test the fix, or should i?

**Comment by noisecapella** [comment]
Either works for me. Do you already have IE11 and edge set up?

**Comment by gsidebo** [comment]
i have ie11 in a win7 virtualbox

**Comment by j2tausig** [comment]
I'm happy to test it, whatever works best for you...

**Comment by gsidebo** [comment]
@noisecapella @j2tausig for some reason, loading a locally-running MM in my IE11 VM completely fails to load static assets. works on my host machine just fine. until we can figure that out, it's probably better for @j2tausig to test the functionality

**Comment by gsidebo** [comment]
ss 2016-10-20 at 13 00 36

**Comment by j2tausig** [comment]
@noisecapella @gsidebo is there a build that I can use to test this?

**Comment by gsidebo** [comment]
@j2tausig creating now. will be available at https://dashboard.heroku.com/apps/micromasters-ci-pr-1402 soon

**Comment by gsidebo** [comment]
got it working locally, and it looks good 👍  (@j2tausig no need to test!)

**Pull request merged**
