### PR TITLE
Release 0.53.4

### PR DESCRIPTION
**Pull request by noisecapella**
## Amir Qayyum Khan
  - [x] Enroll and pay later: Load dashboard page without reloading (#2821) ([2975e890](../commit/2975e890b388587d3563749a9f0a270a0e844a5c))
  - [x] Added full name search support (#2940) ([da0e1cb6](../commit/da0e1cb62cc9b36197d67a9deba0e2846de7371c))

## Giovanni Di Milia
  - [x] Added model and admin for Proctorate Exam Grades ([e7ad6661](../commit/e7ad66610454620504cb1d8650348b4f48fede84))

## Anna Gavrilman
  - [x] Changed course description to show: Auditing or Paid (#2936) ([bc172c85](../commit/bc172c85c40e631ad73dddd0bdbb5e1aec1ff891))

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops for my PR `Added full name search support` deployment on prod or rc, you need to reindex.

cc @noisecapella

**Comment by amir-qayyum-khan** [comment]
@noisecapella please reindex https://micromasters-rc.herokuapp.com

**Comment by noisecapella** [comment]
@amir-qayyum-khan Doing it now

**Comment by noisecapella** [comment]
@amir-qayyum-khan Should be done now

**Pull request merged**
