### PR TITLE
Clean up how API keys are passed into templates

### PR DESCRIPTION
**Pull request by singingwolfboy**
We're currently using two different Javascript APIs that require API keys (Google Analytics and Smartlook), and with #2135 it looks like we'll be adding a third (Google Maps, required to use the Google Places Javascript API). This pull request tries to clean up our existing API usage, to make it easier and more understandable to add more API keys in the future.

Note that this pull request does make one important change to the behavior of the website. Previously, the Google Analytics Javascript would be loaded regardless of whether a tracking ID was set in an environment variable. This pull request now checks to see if we have a tracking ID, and only loads the Google Analytics Javascript if that tracking ID is defined.

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
looks good, is their any view test of this object APIKEYS?

**Comment by amir-qayyum-khan** [comment]
👍

**Comment by singingwolfboy** [comment]
@amir-qayyum-khan no, we don't seem to have any tests for template contexts, and I think that's OK.

**Comment by noisecapella** [comment]
@singingwolfboy Please delete your branches after you merge the PR!

**Comment by singingwolfboy** [comment]
I need to find a Chrome extension or something that will do that for me, automatically...

**Comment by singingwolfboy** [comment]
This looks promising: [Auto branch delete for Github](https://chrome.google.com/webstore/detail/auto-branch-delete-for-gi/cadicbdpppmnmfaepeiolnoeomkoickn). Source is here: https://github.com/robin-drexler/github-auto-delete-branch-chrome-extension A little rough around the edges, but it'll do.

**Pull request merged**
