### PR TITLE
switch from travis to github actions

### LINKED ISSUE #4680: switch from travis -> github actions
Travis will be limited open source projects build time soon, so we need to transition to github actions. 

Take a look at how we did it [open discussions](https://github.com/mitodl/open-discussions/pull/3204)

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
fixes #4680 

#### What's this PR do?
Switch from travis to github actions 

#### How should this be manually tested?

- Tests should pass
- Codecov still works

### CODE REVIEW

**Comment by umarmughal824** [comment]
@annagav Now, it's ready for review.

**Review by annagav — APPROVED** [review]
👍

**Comment by umarmughal824** [comment]
@pdpinch Should I merge it or do we need any input from the #devops teams?

**Comment by pdpinch** [comment]
I don't think we need any further review. Please merge. 

@mitodl/devops FYI

**Pull request merged**
