### PR TITLE
Release 0.8.0

### PR DESCRIPTION
**Pull request by annagav**
## Brandon DeRosier
  - [x] Use Django OAuth Toolkit ([279c0bf1](../commit/279c0bf189457480eaec1b9d0c0ae007eb94319a))

## George Schneeloch
  - [x] Turned on dialog scrollbars ([7d584e07](../commit/7d584e07766257b1b9aaa031b6b9db063ac99a8a))
  - [x] Fixed clear profile edit bug ([96a87a03](../commit/96a87a0371726d2227145a09f0db0e8a4b3aa0a3))
  - [x] Refactored profiles reducer to handle multiple profiles ([f76f3dd6](../commit/f76f3dd6df3225dbe665d9147a6e225039ea6cc2))
  - [x] Implemented UI for showing course runs in dashboard ([7b3dae6c](../commit/7b3dae6c4a0f91a9bf8abef72317822b8041bb5b))
  - [x] Used state select field for education tab ([502d1cf7](../commit/502d1cf7499de4bfe84f97da9344e4c17742b762))
  - [x] Added tests for api functions ([02f4fc57](../commit/02f4fc5716055a31c38fbba2e225b759b5ac161d))
  - [x] Marked profile as incomplete when it&#39;s being filled out and as complete when it&#39;s done ([22841e0b](../commit/22841e0b03fcfd2403b5fbb36457c551020a9204))
  - [x] Added fake values for employment and education constants ([827cd8a8](../commit/827cd8a85a65724ed15d431b9f964b913d5f87d4))
  - [x] Fixed profile submission to wait for a 200 ([0eb6b7fb](../commit/0eb6b7fb3c5e7d759b8dfc2b013fa5b941804ab5))
  - [x] Removed onBlur callback from AutoComplete ([59158112](../commit/591581122f30c1e276c254a7610fe191a5867878))
  - [x] Removed hello_test.js ([8a2fe970](../commit/8a2fe97041b2cf09bfa92531705769d33240d140))
  - [x] Added field for month/year ([20bb6c26](../commit/20bb6c264cbd541fe160b30122d294ee5640aa93))
  - [x] Added material-ui AutoComplete ([a0204e88](../commit/a0204e88c1b89615bb30dcca3588b859913bb00e))
  - [x] Added material-ui, replaced react-mdl Dialog with material-ui Dialog ([444338fa](../commit/444338fa043c054f47d8eaf29dcb1c47e7f06250))
  - [x] Updated redux-asserts ([2bff9326](../commit/2bff932685de2330585bb4ca8a2bda7f544c0362))
  - [x] Updated profile PATCH code to use return value as new profile ([edc47cc4](../commit/edc47cc4bdd1dc686c07425c90d97e90c6611ee2))
  - [x] Updated date to datetime to match CourseRun fields ([d97955e4](../commit/d97955e43e684bc1ae9bc3ab17eb8fcd8b8bb806))
  - [x] Upgraded npm packages ([780eaf41](../commit/780eaf415afe8d2ceb92415bff9be988b3395311))
  - [x] Added field for state or territory ([17f0a855](../commit/17f0a855ffa1b6093d4227c3704f27e718a1d17b))
  - [x] Removed programs and courses APIs which are replaced by dashboard API ([87560483](../commit/875604831dfda6ae1f4a375f1d0dbf7d1553cf2e))

## Giovanni Di Milia
  - [x] Redirect to profile if the profile is not complete ([6700c8d7](../commit/6700c8d705ebb29407c9679ca88c03fd34cffb67))
  - [x] Removed not implemented links in dropdown menu ([98c69a36](../commit/98c69a362df9183fac81cb10c7a000264f463c77))
  - [x] Only live programs are available in dashboard ([4dfcf7cf](../commit/4dfcf7cfbdd327f99e10474e47716d63a56e4914))
  - [x] Additional changes to the admin ([da0cd4ba](../commit/da0cd4ba7b64123f203fb4434d1d9044d34b1305))
  - [x] Implemented refresh token ([916e9ae5](../commit/916e9ae58315d6a30f2a348f44a09ceb8fdcf0d9))
  - [x] Upgraded to latest django ([f6e5ef77](../commit/f6e5ef7744ff6ca2a9a657f26bc8755407f25e92))
  - [x] Old not passed courses in dashboard API ([fa00acf4](../commit/fa00acf4124ca54df6bd0e870562b593e665ae75))

## Alice Pote
  - [x] Moved education reducers and actions into `ui` ([c91e71cd](../commit/c91e71cd277f0e96e094c5b536d56fe0b009fbb7))
  - [x] Added prefer-template eslint rule ([971499b2](../commit/971499b2d53173fe4c315b1529ce1acf5b45dadb))
  - [x] Added &#39;delete&#39; functionality to education entries ([9da8ef4f](../commit/9da8ef4fe30f90307ca1485f5daa4d9130d52772))
  - [x] Changed location order to Country -&gt; State -&gt; City ([5ebb64fa](../commit/5ebb64fa87867cbf98a615a306e3d7d50e840707))
  - [x] Changed all class properties to use es7 class property syntax ([d3aad9df](../commit/d3aad9dfaa84cd341985a034c2e5adf27cdd5033))
  - [x] Implemented new employment page design ([93cd1329](../commit/93cd1329b077596a03c28ad23a20b8474e3fb743))
  - [x] Added requirement for state_or_territory on PersonalTab ([4fcfff3a](../commit/4fcfff3af3750291587bc7c5ca18667f778ba7e0))
  - [x] Added no-var and camelcase eslint rules ([63b9d061](../commit/63b9d061a31ba14681c00f3b32c2c7f0ad2e4bd7))
  - [x] Added check for profile completeness before visiting dashboard ([0e8cc743](../commit/0e8cc743c2354a1c79d631456176e6bcd25b70ea))

## Gavin Sidebottom
  - [x] Updated micromasters documentation ([1f7da9c1](../commit/1f7da9c1ffa8bea376cfca2874afe8611a6a0726))

## Amir Qayyum Khan
  - [x] Fixed urls for enroll and upgdate course in a program ([a399d700](../commit/a399d700af68a2999561a06e08da9355cff51204))
  - [x] Removed dashboard link from dashboard page and added this link to username on header dropdown. ([36468207](../commit/36468207cafedeb04957dd9101bbde752615e38f))
  - [x] Added dashboard links to enroll and upgrade courses, and a disabled button to apply for masters on campus. ([e1ae1726](../commit/e1ae17261d34c29abfb6f4221b474c66b1827316))
  - [x] Created employment history table and migration ([3325c8b6](../commit/3325c8b68b9f2fdf3e492c0bc43d4045fbaa1876))

## Peter Pinch
  - [x] added edx_course_key to courserun list display in admin ([86a028eb](../commit/86a028ebc63a0fac936c5bfaaf2ede7e25927ba1))

## annagav
  - [x] education tab ([e1e52d75](../commit/e1e52d7576ff571e8e310ca3c1a988c96c90d994))
  - [x] change account_privacy error message ([7ddd1111](../commit/7ddd11111d8f4646f61383ab73a6da4f65691eee))
  - [x] fix pipeline_api tests ([e7ef42e6](../commit/e7ef42e69d4254f5024602347edd814986a9261f))
  - [x] Added Privacy tab to profile ([0d113c6e](../commit/0d113c6edafdc4302c5ca1d8dedc43e6b1687e3b))

### CODE REVIEW

**Comment by annagav** [comment]
Please verify your commits! @aliceriot, @noisecapella , @giocalitri , @amir-qayyum-khan , @gsidebo , @pdpinch.

**Comment by amir-qayyum-khan** [comment]
@annagav can you share url of instance where we i can validate my commits.

**Comment by annagav** [comment]
@amir-qayyum-khan, Please verify your commits at https://micromasters-rc.herokuapp.com/.

**Comment by amir-qayyum-khan** [comment]
@bdero i got this email on registration to edx on micromasters

> Thank you for signing up for Your Platform Name Here.

Change your life and start learning today by activating your Your Platform Name Here account. Click on the link below or copy and paste it into your browser's address bar.

  https://localhost/activate/86b5282831e94e86a9815e83d2149e51
If you didn't request this, you don't need to do anything; you won't receive any more email from us. Please do not reply to this e-mail; if you require assistance, check the help section of the Your Platform Name Here website.

**Comment by amir-qayyum-khan** [comment]
@annagav @pdpinch 

- Link on enroll button is not correct (Program -> course -> Enroll).  It seems https://github.com/mitodl/micromasters/commit/a399d700af68a2999561a06e08da9355cff51204 not working

**Comment by bdero** [comment]
@amir-qayyum-khan That generic and erroneous enrolment email is expected, if you're having trouble logging into micromasters.d, let me know and I can help with that.

**Comment by amir-qayyum-khan** [comment]
thanks @bdero i am able to login.

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you take another look at your remaining checkbox here?

Fixed urls for enroll and upgdate course in a program (a399d700)

**Comment by amir-qayyum-khan** [comment]
@pdpinch @annagav are you guys ok with [this issue](https://github.com/mitodl/micromasters/pull/362#issuecomment-220691678)? If this is ok with you guys then i can click the check box, Because of this issue enroll button is taking me to ``No course found page``.


screen shot 2016-05-23 at 8 05 56 pm

**Comment by amir-qayyum-khan** [comment]
@pdpinch and @annagav verified my commits. Thanks

**Pull request merged**
