### PR TITLE
show signup dialog on start

### LINKED ISSUE #4248: When login is required, display the login dialog
As a user, when I access a page that requires login, I find it confusing to get directed to the MicroMasters home page. 

There are two possible UX solutions. The preferred solution is that the user is directed to a route that displays the home page with the login dialog display. The "next" parameter needs to be passed effectively through the edX login flow for this to work. 

A less desirable solution is to direct the user immediately to the edX log in page. Again, the "next" parameter needs to be passed, but it only needs to make it through one level of redirect. 

No matter what the solution is, it also has to work with users logging in from open-discussions. 

### related issue
- #4190 next parameter doesn't work if user is already logged in

### PR DESCRIPTION
**Pull request by tasawernawaz**
#### What are the relevant tickets?
Fixes #4248 

#### What's this PR do?
Show login dialog at the start, if user is not logged in.

#### How should this be manually tested?

- Logout from micromaster
- Hit any of the following URLs, you will see login/signup popup.
  - http://0.0.0.0:8079/dashboard
  - http://0.0.0.0:8079/learners
- Signup will not be shown on home page 
  - https://0.0.0.0:8079

### CODE REVIEW

**Comment by annagav** [comment]
@tasawernawaz @pdpinch I don't know if I missunderstood the issue, but I don't think we want the sign up dialog to appear when hitting the homepage ` https://0.0.0.0:8079`.

**Comment by pdpinch** [comment]
The dialog should only be appearing on routes that require login, i.e. /dashboard, /learners and maybe a couple of others. 

Definitely not the home page, and any routes served by wagtail.

**Comment by tasawernawaz** [comment]
@annagav thanks for your review. @pdpinch I will update the PR.

**Comment by tasawernawaz** [comment]
@annagav I am looking for the workaround here, I don't think its good idea to use `window.location.href` here, is there any other workaround given our codebase to differentiate that we are at home page or not ?

**Comment by pdpinch** [comment]
Can I propose a simpler solution? The issue is that users who need to login are routed to /?next=<url> — why don’t we just display the pop up when that parameter is present?

**Comment by tasawernawaz** [comment]
@pdpinch I have updated code according to your suggestion.

**Comment by annagav** [comment]
@tasawernawaz some tests are failing

**Comment by tasawernawaz** [comment]
> @tasawernawaz some tests are failing

Fix tests

**Pull request merged**
