### PR TITLE
use our fork of iso-3166-2.js with English names for Israel's districts

### LINKED ISSUE #3430: Use English names for Israeli sub-divisions
The iso-3166-2.js library that we're using for countries and sub-divisions uses a mix of Arabic and Hebrew names for the sub-divisions in Israel (IL). 

I've opened a [PR to the library](https://github.com/olahol/iso-3166-2.js/pull/20) to use the English names. When the PR is merged, we can update the dependency in Yarn.

### PR DESCRIPTION
**Pull request by pdpinch**
#### What are the relevant tickets?

fixes #3430 

#### What's this PR do?

Uses mitodl/iso-3166-2.js with English names for Israel's districts. 

#### How should this be manually tested?

Go to the learner profile, change the country to Israel and confirm that the district names are in English, not Arabic or Hebrew. 

For the English names, see 
https://github.com/mitodl/iso-3166-2.js/blob/3466fbed3fe7b961d1548e4272b992f41f97677a/data.csv#L1851

#### Any background context you want to provide?

There is a PR open on the upstream repository, but no one has responded to it.

See https://github.com/olahol/iso-3166-2.js/pull/20

### CODE REVIEW

**Comment by pdpinch** [comment]
What kind of tests (if any) does this need?

**Comment by aliceriot** [comment]
I don't think we need to do any testing for an external dependency, we should be ok.

**Comment by aliceriot** [comment]
It looks in our fork like the relevant commit is only on the `pdpinch/israel-districts-english` branch - could we merge it into `master`, just so it's clearer for anyone looking at this going forward?

**Comment by aliceriot** [comment]
functionality here works great though!

**Comment by pdpinch** [comment]
I merged my PR into master of mitodl/iso-3166-2 and updated the commit reference. I'll merge this once tests pass.

**Pull request merged**
