### PR TITLE
Adding course option to CourseCertificateSignatories

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
None

#### What's this PR do?
Adds a course panel to CourseCertificateSignatories

Go to cms to edit the program page, and try to add course certificate signatories to the program, you should see an option to select a course.

### CODE REVIEW

**Comment by pdpinch** [comment]
I don't understand how this regression happened. When you add that field, what is the UI for choosing the course?

**Review by pdpinch — COMMENTED** [review]
:shipit:

**Comment by annagav** [comment]
The change was in this PR https://github.com/mitodl/micromasters/pull/4590, where we changed `content_panels` to `panels`.

**Comment by annagav** [comment]
@pdpinch The ui looks as a dropdown of all courses for the program.

**Comment by annagav** [comment]
Screen Shot 2021-04-05 at 12 13 05 PM

**Pull request merged**
