### PR TITLE
Update the pillow version

### PR DESCRIPTION
**Pull request by asadiqbal08**
#### What are the relevant tickets?
https://github.com/mitodl/micromasters/network/alert/requirements.txt/Pillow/open

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@ahmed-arbisoft can you look is that the pillow version that causing the build failure ?

**Comment by asadiqbal08** [comment]
@pdpinch It seems pillow version update in this PR is not compatible with wagtail one. Need suggestion.

**Comment by pdpinch** [comment]
I can't really tell how serious the issue is with Pillow. What do you think?

Does it look like Wagtail will upgrade Pillow? do they have an issue for it?

**Comment by asadiqbal08** [comment]
@pdpinch , After updating the `Pillow` to `7.1.0`, It was complaining for wagtail version that I have updated too in the PR but in the latest release of `wagtail==2.9.3`, getting warning over Travis build pointing to 

```
warnings.warn(
        'wagtail.core.middleware.SiteMiddleware and the use of request.site is deprecated. '
        'Please update your code to use Site.find_for_request(request) in place of request.site, '
        'and remove wagtail.core.middleware.SiteMiddleware from MIDDLEWARES',
>       RemovedInWagtail211Warning
    )
```
that will require further in depth look around code updation.

**Comment by asadiqbal08** [comment]
one more thing, `test.py` [file](https://github.com/mitodl/micromasters/blob/master/micromasters/test.py#L36) under micromaster is patching to `'wagtail.core.middleware.SiteMiddleware',`

**Comment by ahmed-belal** [comment]
@asadiqbal08 any progress on this?

**Comment by pdpinch** [comment]
@asadiqbal08 what's the status of this?

**Comment by pdpinch** [comment]
Now that we've upgrades [Wagtail to 2.9.3](https://github.com/mitodl/micromasters/pull/4624), can we try to upgrade Pillow again?

**Comment by asadiqbal08** [comment]
@noisecapella Can you please take a look over this PR ?

**Review by arslanashraf7 — APPROVED** [review]
Looks good 👍 Just to mention, I think we should close #4687 along with this PR.

**Pull request merged**
